### ISSUE TITLE
[TASK] Update localstorage to store an object indexed by create2 address

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1006]
## Overview

The usage of `localStorage` in the bridge causes disruption and failures when new deployments are done. Developers have to clear storage or know exactly what notes are valid for any given deployment. 

We should update how we store encrypted data in localStorage and index the object by create2 address being used in the dApp. It would provide a clear distinction between localStorage objects that can then be removed. We are currently storing by `<NoteAccountPublicKey : {encryptedNotes... }>`. The limitation here is that most developers are making use of the same address to create their Note Account resulting in the appending of notes to this object even though the bridge deployment addresses may have changed. 

### Potential Solution

I potential approach could be to update storage to be <Create2Address: `{NoteAccountPublicKey: {encrypedNotes...}>`. This would provide clear distinction if deployments had changed and reducing the amount of times the dApp fails due to an old notes from a previous deployment. 

Thoughts here @AtelyPham ?

**Comment by drewstone** [comment]
The way I initially envisioned this is to index everything under the specific contract addresses in question:
```
{
	[anchorAddress]: {
		[notePublicKey]: { ...encryptedNotes },
		leaves: [ ...arrayOfLeaves ]
	}
}
```

**Comment by drewstone** [comment]
Scratch my exact thoughts above, instead I think we should be indexing these objects by the `ResourceId` that we use universally around the system. This makes it much easier for us to separate between Substrate / EVM as we are currently planning to handle. The new scheme would then look something like
```json
	[resourceId]: {
		leaves: [ ... ],
		notePublicKey: [ ... ],
	}
```

CC @AtelyPham
