### ISSUE TITLE
[TASK] Improve destination chain component to show correct chains

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1014]
1. I'm connected to `optimism`
2. I have a deposited `webbETH` balance
3. I switch to `transfer` tab, I select the destination chain to make a transfer (It shows only `optimism`)

If we are showing only the chain on which the deposited asset is on (In this case `webbETH` and `optimism`) why do we need `destination` chain selection component? In this case I think we should pre populate the destination chain input field with the only one option (In this case `optimism`). Is this the intended behaviour or are we supposed to show other chains too?

https://user-images.githubusercontent.com/53374218/219767921-a7afb409-e41b-43bd-af84-f3bcb0fa0625.mov

_Originally posted by @devpavan04 in https://github.com/webb-tools/webb-dapp/issues/985#issuecomment-1435134354_

**Comment by dutterbutter** [comment]
@devpavan04 can you confirm this task is still an issue?

**Comment by devpavan04** [comment]
> @devpavan04 can you confirm this task is still an issue?

Yes @dutterbutter

**Comment by AtelyPham** [comment]
Close in favour of https://github.com/webb-tools/webb-dapp/pull/1264.
