### ISSUE TITLE
[TASK] Improve add token to wallet experience 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1035]
## Overview

Our goal is to simplify the process for users to add the bridged asset to their MetaMask wallet and view their balance. Currently, the implementation in PR #1028 allows users to add the token by hovering over the symbol and clicking the + icon. However, this approach may not be intuitive for most users. Therefore, we are exploring ways to make the process more explicit.

@monaiuu has proposed a few design ideas, but they assume we can check whether the user has already registered the token in their wallet. The proposed change can be seen in the video below. The `wallet_watchAsset` method in the MetaMask API [documentation](https://docs.metamask.io/guide/rpc-api.html#wallet-watchasset) indicates this may be possible, which could potentially solve this issue. However, according to a [Stack Exchange post](https://ethereum.stackexchange.com/questions/107253/metamask-api-how-to-detect-if-token-already-registered), this method may always prompt the user to register, which could be more of an annoyance than a convenience.

### Task Checklist 

- [x] Investigate how best to display 'Add Token' button given the inability to check if the user has done so already 

### Initial Proposed Design

https://user-images.githubusercontent.com/109539270/222511922-2ff743f9-5033-4cd8-b3c3-cef63bad3727.MOV

**Comment by monaiuu** [comment]
## Add Token to Wallet Design Hand-off
Below is the details to hand off the above-proposed design as indicated in the screen-recording. In the demonstrated flow, we enable user to add tokens to wallet in the Select Token Card by including a link button that says `add to wallet` when user hovers over a token that has **not** been added to the connected wallet previously. 

To accommodate this change, we will make an update to token selection for List Items in the Design System. To elaborate, we will make a distinction between a token selection that has been added to wallet (display `balance`; could be `0`), and a token selection that has not been added to wallet (display `-`, hover display `add to wallet`) 

Let me know if there are any issues, questions, or feedback. Thanks!! 

### Screenshot [[Design System]](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1200%3A16033&t=ZGm88FJbAgtMOqy9-1)
<img width="518" alt="Screenshot 2023-03-03 at 2 15 20 PM" src="https://user-images.githubusercontent.com/109539270/222840150-82bbb543-527e-48eb-b1b2-40ccf8c9a334.png">

This change is reflected in the latest Prototype & End-to-End wireframes for Bridge UI, which has also been updated in the [Notion Prototypes Doc](https://www.notion.so/hicommonwealth/Hubble-Bridge-add061088d44425a9402c3ca9fe97df4?pvs=4). The update is reflected in all `Token Selection Cards`.
### [Updated Prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?page-id=940%3A139772&node-id=2460%3A468247&viewport=-5536%2C3856%2C0.64&scaling=scale-down&starting-point-node-id=2460%3A468247&show-proto-sidebar=1)
### [Updated Wireframes](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=940%3A139772&t=e2URdXHVXlFtU6aj-1)


### Screen Recording
https://user-images.githubusercontent.com/109539270/222511922-2ff743f9-5033-4cd8-b3c3-cef63bad3727.MOV
