### ISSUE TITLE
[FEAT] Add twitter follow button to every blog post and other social links

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1052]
# Task
- Add the twitter follow button to each blog post
- Add discord join button
- Consider any other missing buttons and links that we could add

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/13153687/225103145-64cdfd71-a660-414a-87e5-c86c6a322f41.png">

**Comment by drewstone** [comment]
Duplicate this at the top of the blog post IMO
<img width="265" alt="image" src="https://user-images.githubusercontent.com/13153687/225103365-01b3ab40-cb70-4395-bc85-c332a1aa142a.png">

**Comment by monaiuu** [comment]
https://user-images.githubusercontent.com/109539270/229256596-98aea264-c262-4c8c-817f-765b8dfccbfa.MOV
