### ISSUE TITLE
[CHECKLIST] Implement Hubble bridge statistics UI 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1056]
## Overview 

We intend to provide users with a statistics UI fro the Hubble bridge. Providing insights into the liquidity, volume, fees etc. on a set of bridges. The backend of the statistics page will implemented in [webb-tools/webb-graphql ](https://github.com/webb-tools/webb-graphql) of which the UI will interact with. **This task outlines the scope for the UI implementation.** 

## Hubble Bridge Statistics | Design

Please see below for the handoff of Hubble Bridge Statistics Page. This handoff involves the Hubble Overview Page, and the Pool/Token Stats Page. 

For the Overview Page, the following is displayed:
* General statistics/data of Hubble Bridge
* List of shielded tokens available
* List of shielded pools available 

For the Pool/Token Page, the following is displayed:
* General info of pool/token
* General statistics/data of pool/token
* Distribution of token composition amongst various chains
* List of transactions 
* Pool-specific metadata

### Screen Recording
https://user-images.githubusercontent.com/109539270/225698825-6b9b3789-aadf-41c1-9ec0-fcb60dad0d0c.mp4

### Task Checklist 

- [x] #1057
- [x] Create new hubble bridge stats app in `apps/` directory 
- [x] #1058
- [x] #1059

**Comment by monaiuu** [comment]
Initial PRD can be found here:
https://www.notion.so/hicommonwealth/Hubble-Bridge-Statistics-PRD-81561e68aef6486dbf48c0e6203e6a4e?pvs=4
