### ISSUE TITLE
[CHECKLIST] Implement detailed bridge stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1059]
## Overview

When a user selects a given bridge we need to display detailed information about the given bridge. The scope of this task will be to implement the detailed bridge stats page. 

### Task Checklist 

- [x] #1345
- [ ] #1346
- [x] #1347
- [x] #1453
- [x] #1348
- [x] #1349

**Comment by AtelyPham** [comment]
Moved https://github.com/webb-tools/webb-dapp/issues/1346 to checklist https://github.com/webb-tools/webb-dapp/issues/1058 to close this issue.
