### ISSUE TITLE
[TASK] Add Input States to Bridge dApp Control Cards for Improved Visual Feedback

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1080]
## Description

Our bridge dApp control cards do not currently provide visual feedback to users on the status of their actions within the dApp, which can cause confusion and accessibility issues. By implementing input states for our control cards, we can provide users with clear visual feedback on the status of their actions, enhancing the user experience and accessibility of our application.

**Comment by monaiuu** [comment]
dependency: https://github.com/orgs/webb-tools/projects/7/views/19?pane=issue&itemId=25251569

**Comment by dutterbutter** [comment]
@monaiuu can you add the relevant figma links and options here.

**Comment by monaiuu** [comment]
https://github.com/webb-tools/webb-experiences/issues/132

**Comment by monaiuu** [comment]
Addressed in V2.
