### ISSUE TITLE
[FEAT] Add Hubble bridge statistics widget

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1084]
**Note:** This task is dependent on the completion of https://github.com/webb-tools/webb-graphql/issues/59

## Widget Handoff

Please see below for the handoff for the UI widget integration within Hubble Bridge. This widget will encompass two views: the education stepper view & bridge stats data view that can be toggled back and forth. In the default state, we will render the Hubble Overview instead of the education view -- assuming most would find that more helpful if they are not first-time users.

### Hubble Overview (Default State)
The bridge stats data view will provide users with the Hubble Overview or the Pool View. In the default state, the Hubble Overview will be displayed to showcase general data of Hubble Bridge. 
<img width="1843" alt="Screenshot 2023-03-23 at 5 59 22 PM" src="https://user-images.githubusercontent.com/109539270/227397565-3fa0eca3-21a5-4c6e-bb2e-77b6cb3b09ea.png">

### Pool View (Bridge Token Selected)
Once the bridging token (pool) has been selected, the interface will render the specified pool data to inform users of the activity of the selected pool.
<img width="1815" alt="Screenshot 2023-03-23 at 5 59 12 PM" src="https://user-images.githubusercontent.com/109539270/227397794-678e6f37-cb02-4369-b91d-cdac23b9cc92.png">

### Transaction in Progress (Collapsed View)
Once the transaction is in progress, the interface will remove the display of the widget altogether. 

### Education Stepper View
The education stepper view will provide a step-by-step walkthrough to users, as initially implemented in various states (deposit, transfer, withdrawal), but with an updated stepper component to improve status visibility.

<img width="1859" alt="Screenshot 2023-03-23 at 6 02 43 PM" src="https://user-images.githubusercontent.com/109539270/227398003-966cab17-d663-4a1f-bee9-78ec0cc84428.png">

## Design System Updates
To address this issue, the following components have been added/updated within the [design system](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=66%3A3687&t=nnWJsBr8ltFxWG61-1):

- Charts components have been added with dark mode (see page '🟢  Charts' in the design system). These chart components are also implemented in the Hubble Stats UI. 
- Stepper components have been added to the education widget view (see page '🟢  Stepper' in the design system).

### [Wireframes](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=940%3A139772&t=QLFS2kd5LO6UrNi8-1)
The end-to-end wireframes have been updated the reflect the latest addition of the widget view. Please reference to above wireframes for a more detailed look at how the components interact holistically. The end-to-end [prototype](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?page-id=940%3A139772&node-id=2763-350527&viewport=-23%2C758%2C0.05&scaling=scale-down&starting-point-node-id=2763%3A350527&show-proto-sidebar=1) has also been updated to reflect the latest changes.

### Walkthrough
https://user-images.githubusercontent.com/109539270/227401928-1080255a-87d4-4eea-883a-8e2c7027c505.mp4

### Notes

- Due to the swapping between the left and right components, the background image has been temporarily removed from the prototype. I will recreate the background image in the upcoming week.

**Comment by AtelyPham** [comment]
Close in favor of Hubble Bridge Stats as a separate app with the Hubble Bridge (check out this issue https://github.com/webb-tools/webb-dapp/issues/1056).
