### ISSUE TITLE
[TASK] Informative error messaging if relayer or DKG disruption

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1092]
## Overview

The dApp is dependent on the relayer network. When a user attempts to withdraw and the transaction failed due to a relayer specific issue we should inform the user that their funds are not in jeopardy. 

We will need to check the origination of the error, if its due to the relayer we will report a more supportive message. Potential messaging could be:
- "Relayer network under maintenance. Please try again later."
- "Relayer network is currently experiencing issues. Please try your transaction again at a later time."
- "Your funds are safe, but the relayer network is currently under maintenance. Please try again later."

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1048.
