### ISSUE TITLE
[TASK] Create Banner for Hubble Bridge

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1094]
## Description
Create a banner for Hubble Bridge that will be used in the upcoming blog post and future marketing. The banner should be consistent with the Webb Banner and Tangle Banner previously created.

**Comment by monaiuu** [comment]
### Link to Asset:
https://www.notion.so/hicommonwealth/Hubble-Assets-406bbd10499a40f5b16e10b3abd43473?pvs=4

**Comment by dutterbutter** [comment]
Completed with above banner ^
