### ISSUE TITLE
[TASK] Remove 'Unwrap' toggle in Bridge Withdrawal Flow

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1099]
## Description

The current "Bridge Withdrawal Flow" includes an Unwrap `toggle`, which allows users to convert their shielded tokens into underlying tokens during the withdrawal process. Upon reevaluation, this user action can be confusing since users can also withdraw the token in its native form (i.e., WebbETH) and in this flow we do not display that. The notion of 'unwrap' may be unnecessary & creates added confusion. 

Proposing to remove the "Unwrap" toggle from the Bridge Withdrawal Flow to simplify the process and improve the user experience.  

### Screenshot

![Image](https://user-images.githubusercontent.com/109539270/230965638-74a0df53-2933-4021-90e8-8b6588618e13.png)

### Figma File
https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=3171%3A287222&t=2IQKbeiiTNXJwQjq-1

@dutterbutter

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/webb-tools/webb-dapp/issues/1099
