### ISSUE TITLE
[BUG] Drag and Drop file in the Upload Spend Note Modal Not Working

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1105]
Currently, when we try to drag a file into the drag and drop section in the upload spend note modal, it is not working, previously it works fine, but not sure why it does not work right now!

## Expected Behavior

The drag and drop section in the upload spend note modal should work when we drag a `.json` file into it.

### Current Behavior

It is not working, when I tried to drag a `.json` file into the drag and drop section, it is not working and I don't get any feedback 🤔.

### Possible Solution

- Maybe try to update the `react-dropzone` to the latest version (I tried to disable everything, just left a `div` and an `input` to test like the basic example of the library, but it did not work too).

## Steps to Reproduce

1. Scroll down to the note account table
2. Click the `Manage` dropdown, then click the `Upload` option
3. You'll see the Upload Spend Note modal opened, try to drag a `.json` file into the drag and drop section
4. You'll see it does not work

### Screenshot 

https://user-images.githubusercontent.com/60747384/231695740-cb833566-0794-4976-9859-b10dc5f6b611.mp4

### Log output

<details>
  <summary>Log Output</summary>
  
 No log output
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by devpavan04** [comment]
@AtelyPham I tried reproducing the issue on the latest develop branch, and it seems to be working fine on my end. @dutterbutter Could you please try to reproduce this?

We're currently using latest version of `react-dropzone` i.e version `14.2.3`


https://user-images.githubusercontent.com/53374218/232097772-d1cd6082-7ea8-4767-9adc-1e2149aa0c78.mov

**Comment by dutterbutter** [comment]
@devpavan04 @AtelyPham I was not able to reproduce this on `develop`. Works fine for me.
