### ISSUE TITLE
[BUG] Ensure proposals are correctly being tracked and displayed 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1123]
## Overview

When an `AnchorUpdateProposal` or any proposal is signed by the DKG we should accurately display the proposal on the stats page. Currently, these proposals are being tracked but are being displayed as "Unknown". 

This could be due to a types issue mentioned in this issue: https://github.com/webb-tools/webb-graphql/issues/73

### Screenshot

![proposal](https://user-images.githubusercontent.com/29983536/233463058-52b34cd9-5c66-496d-9227-a19755868bd3.png)

### Task Checklist

- [ ] Investigate issue with types to see if this resolves this issue
- [ ] Reproduce issue locally to ensure it works as intended

**Comment by devpavan04** [comment]
This issue was resolved in `webb-graphql` with this [PR](https://github.com/webb-tools/webb-graphql/pull/85).
