### ISSUE TITLE
[FEAT] Destination Chains on Transfer Flow Can Be Any Chains with the Same Bridge Deployment

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1124]
**Is your feature request related to a problem? Please describe.**
Currently, users can only select the destination chain of the transfer note on the transfer flow. However, the destination chain can be any chain with the same bridge deployment.

**Describe the solution you'd like**
I propose implementing the following solution:

1. Filter the available destination chains based on the selected transfer notes. 
2. Display the available destination chains on the UI for users to select.
3. Pass the selected destination chain when generating the transfer UTXO.
4. Check the transfer flow with different destination chains.

With this solution, users will be able to select any chain with the same bridge deployment as the destination chain for their transfers, which should be more convenient and efficient. 

### Steps to implement this feature

- [ ] Filter the available destination chains (based on the selected transfer notes)
- [ ] Display the available destination chains on the UI for users to select
- [ ] Pass the selected destination chain when generating the transfer UTXO
- [ ] Test the transfer flow with different destination chains to ensure the feature works properly.

**Comment by drewstone** [comment]
It's already implemented correctly in deposit, this shouldn't be overcomplicated. Just use the same logic as is used on deposit here and de-duplicate the code if possible.
