### ISSUE TITLE
[TASK] Update Webb Faucet UI to fetch data from faucet backend 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1135]
### Task Checklist

**Comment by AtelyPham** [comment]
Essentially, we need to obtain this [data](https://github.com/webb-tools/webb-dapp/blob/0dcc454c304dbdb65ea3f1e4df9bca5ef4181b0c/apps/faucet/src/provider/index.tsx#L94-L120) from the backend, parse it, and display it on the UI. By doing so, we can ensure that the Faucet App does not contain hardcoded data and the workflow operates as intended.

**Comment by AtelyPham** [comment]
Depends on https://github.com/webb-tools/webb-faucet/issues/6.
