### ISSUE TITLE
[TASK] Update BG image to include Tangle token

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1148]
## Description

Please update all dApps with swirl background image. See below for the updated background with Tangle token added in SVG format. 

![Property 1=Dark](https://user-images.githubusercontent.com/109539270/234718086-8c050382-d031-4ed7-ae5b-0f983ebb9382.svg)
![Property 1=Light](https://user-images.githubusercontent.com/109539270/234718090-42eaf2c0-32ab-4817-8942-bd6de4dc9269.svg)

### Screenshots
Below is how the bridge will look with the updated background image.
<img width="1475" alt="Screenshot 2023-04-26 at 3 14 34 PM" src="https://user-images.githubusercontent.com/109539270/234718629-77171a3e-e438-4c79-bce4-acfe7cd6f275.png">

Bridge Stats Page
<img width="876" alt="Screenshot 2023-04-26 at 3 43 18 PM" src="https://user-images.githubusercontent.com/109539270/234718561-891d649a-dd3e-4c44-9c2d-3205a90d9a17.png">

Faucet
<img width="1054" alt="Screenshot 2023-04-26 at 3 50 11 PM" src="https://user-images.githubusercontent.com/109539270/234719404-50e2e6fb-a2f1-4fc3-971a-ab5e95907fcd.png">

Figma File of background image can be accessed below:
https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=3332%3A308518&t=6og603fZR8Zs33b6-1

**Comment by dutterbutter** [comment]
Note: this task also includes the change of orientation of the bridge dApp.

**Comment by dutterbutter** [comment]
@AtelyPham and @devpavan04 I see we have this on development environment for the bridge. Can this be closed?

**Comment by devpavan04** [comment]
Closing in favour of #1234 #1235
