### ISSUE TITLE
[DISCUSSION] Determining Bridge Connection for Substrate <> EVM Transactions

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1158]
**Is your feature request related to a problem? Please describe.**
Currently, the bridge dapp detects bridge connections by the anchor addresses. However, this approach will not work if we include Substrate in the connection because Substrate does not have an anchor address. Instead, it only has a tree id which is not the same as the anchor address.

**Describe the solution you have**
To resolve the issue, we can use the APIs provided by the protocols (EVM or Substrate) to get the connection between the anchor address and tree id dynamically queried by the bridge dapp.

**Describe alternatives you've considered**
We also considered hardcoding the bridges connection in a new configuration in the ApiConfig class. However, this approach has the disadvantage of requiring updates whenever the anchor address or tree id changes. Therefore, it is not a desirable solution.

cc: @drewstone @shekohex.

**Comment by drewstone** [comment]
Can't we just detect that it's not an anchor address and a tree instead and switch to the Substrate chain? Do we have resource IDs corresponding to the anchor in question? If so, we can just parse the chain ID from it and figure out how to switch based on that.

**Comment by AtelyPham** [comment]
The issue here is to determine the available destination chains for the current active source chain. Currently, we detect these chains by anchor address and display the available destination chains that share the same anchor address as the source chain. However, the Substrate chain does not have an anchor address.

If we use resource IDs, how can we find the connected resource IDs with the current resource ID?

**Comment by drewstone** [comment]
We query the anchor for its linked Edges, parse the resource ID from the edge data, then parse the typed chain IDs from the resource IDs.

**Comment by AtelyPham** [comment]
The proposed approach works! We will proceed with the approach and submit a PR 👍.
