### ISSUE TITLE
[TASK] Create leaderboard page for Tangle website 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1172]
## Overview

We need to create a dedicated page for the incentive campaign. See campaign details below.

**Tangle Testnet Incentive Campaign**
As we prepare for the launch of the Tangle Network, we're excited to announce our Testnet Incentive Campaign! This program is designed to encourage users to explore, utilize, and improve the Tangle Network, contributing to the development of cutting-edge privacy tooling. By participating in various activities, users can earn points that will entitle them to a percentage of the Tangle Network's airdrop.

**Points Scheme**

| Activity                                           | Points    |
|----------------------------------------------------|-----------|
| Relay 1 tx/day for 1 week/month                    | 0         |
| Make 1 deposit over X amount                       | 0         |
| Make 1 withdraw                                    | 0         |
| Run a validator                                    | 1         |
| DKG Authority (get voted in)                       | 5         |
| Bug Bounty with PR Fix Submission                  | 50        |
| Deposit → Transfer → Withdraw                      | 10        |
| Vote in Governance                                 | 1         |
| Propose and Pass in Governance                     | 1         |
| Author a Protocol Extension                        | 3         |
| Scripts to make Transactions                       | 10        |
| Publish a video or tutorial on Tangle or Webb.     | 20        |
| Tweet about Webb                                   | 3         |
| Tweet a Semaphore identity w/ Webb                 | 20        |
| Tweet an ETH address or ENS domain                 | 15        |
| Tweet a hash of your address + a secret number     | 20        |
| Bug Report                                         | 10        |
| Use Case Concepts (Asset protocols, Maps, Identity, Social) | 10   |
| Creative Contribution — Have an idea for something that doesnt fit here? Show us! We’ll assign points based on merit. | Variable |

CTA: Join our Discord's Testnet channel to participate, report your contributions, and more. (JOIN)

**Comment by AtelyPham** [comment]
Closing this, in favor of https://github.com/webb-tools/webb-dapp/issues/1343.
