### ISSUE TITLE
 [BUG] Open metamask wallet too slow

### ISSUE THREAD

**Issue by jaxrunboo** [webb-tools/webb-dapp#1173]
Open metamask wallet too slow.

## Expected Behavior
When I start to link my wallet ,it should be open right now.

### Current Behavior
When I want to link my wallet.It's will spend for 3 minutes to open the metamask.

### Possible Solution
I think maybe the code for open the wallet should be change.

### Screenshot 
![image](https://user-images.githubusercontent.com/24749957/236876564-6e33172f-9d68-461a-a56a-4ed79dc3c91d.png)

## Context (Environment)
url： https://app.webb.tools/#/bridge

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment]
@jaxrunboo Thanks for filing an issue! We will review and investigate.

**Comment by AtelyPham** [comment]
Hey @jaxrunboo, thank you for opening the issue. I suppose the reason behind this is that we fetch the token data on-chain after you connect your wallet, which causes a delay in obtaining the on-chain data. We have had a task with this optimization, which I will address soon.
