### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by Myronrdk** [webb-tools/webb-dapp#1174]
At first glance, the choice of amount is not clear to me as a user. I think these options, a fixed amount and a custom amount, should be open and more understandable at once.
![web N1](https://user-images.githubusercontent.com/132988122/237032840-dea31e70-e842-44eb-a123-1004f6ef56cc.jpg)
fee 17eth)))

**Comment by dutterbutter** [comment]
Thanks for the suggestion! We have added the task to our design sprint.
