### ISSUE TITLE
[FEAT] 

### ISSUE THREAD

**Issue by chenzipeng453** [webb-tools/webb-dapp#1177]
增加25%，50%的比例
![1683640847686](https://github.com/webb-tools/webb-dapp/assets/109653981/2a9b9fba-0d19-41a9-b70f-00d682b3c914)

**Comment by monaiuu** [comment]
@chenzipeng453 Thank you for your feedback; your suggestion has been added to the upcoming design task list.

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/webb-tools/webb-dapp/issues/1184
