### ISSUE TITLE
[UI] Make custom amount selection more explicit on Withdraw flow

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1181]
## Overview

In the current implementation the "Custom Amount" option is not explicitly obvious for users to make use of. We need to surface this option more deliberately. 

### Task Checklist 

- [ ] Update the Withdraw flow to make the "Custom Amount" option more explicit and clear

**Comment by monaiuu** [comment]
Closing in favor of https://github.com/webb-tools/webb-dapp/issues/1405; added `switch` in withdrawal flow to enable easy toggle between fixed and custom amount.
