### ISSUE TITLE
[UI] Experiment with adding % values to deposit flow operation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1184]
### Overview

Users have expressed interest in adding % value buttons on the deposit flow in % increments (e.g. 25%, 50%) to quickly indicate the amount they wish to deposit. 

### Task Checklist 

- [ ] Experiment with deposit flow UI to include % buttons for quick deposit amounts

**Comment by monaiuu** [comment]
on hold until further user feedback after v2 launch.
