### ISSUE TITLE
[TASK] Improve error message on transfer container amount input field

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1188]
### Overview

In the current implementation, when the user enters the `amount` to transfer, input filed error message is thrown which says `Insufficient Funds, You need more than 0.003 <token symbol> to cover the fee` which could be confusing for the user.

We need to improve this error message or come up with a better solution of notifying the user that `0.003` is the minimum input required to cover the fee.

https://github.com/webb-tools/webb-dapp/assets/53374218/002b4b91-f058-4b04-896f-40b685c436c0

**Comment by AtelyPham** [comment]
It seems you haven’t pulled `develop`, I've fixed this case. In a case like the video above, we shouldn’t display that error message, because the user does not select the relayer so the fee will be paid by the user balance, not the note account balance.

**Comment by dutterbutter** [comment]
Fixed previously.
