### ISSUE TITLE
[BUG] Update failed txn alert messages

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1190]
### Overview

We need to update the transaction alert messages to be user friendly rather than just showing txn `Error` messages like below.

![CleanShot 2023-05-08 at 12 57 37](https://github.com/webb-tools/webb-dapp/assets/53374218/9021fe7a-cba5-4098-ae2f-d7866b359490)

**Comment by AtelyPham** [comment]
We have closed this issue for now and will revisit it once we shift our focus to Substrate.
