### ISSUE TITLE
[BUG] Unable to withdraw funds to the Gourly network

### ISSUE THREAD

**Issue by pape12377749** [webb-tools/webb-dapp#1191]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by pape12377749** [comment]
Unable to withdraw funds to the Gourly network
![Снимок экрана (311)](https://github.com/webb-tools/webb-dapp/assets/91692742/7be9fcac-f0f7-4c39-8938-d3cdf7ef5f86)

**Comment by dutterbutter** [comment]
This should be resolved now @pape12377749. Please try again! Closing this issue for now, feel free to open if issue persists.
