### ISSUE TITLE
[BUG] Relayer1 endpoint received but not enabled in Relayer selection modal

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1195]
## Overview

When selecting relayer usage during Withdrawal, relayer1 is not present yet the endpoint is received and configured for the same bridge as relayer2. Relayer1 endpoint: `https://relayer1.webb.tools/api/v1/info`.

### Task Checklist

- [x] Determine why relayer1 is not present in relayer selection modal 
- [x] Provide a fix to address issue

**Comment by AtelyPham** [comment]
Relayer1 contracts `eventsWatcher` is not `enabled`. So it does not show on the dApp. But relayer2 does so it is shown on the dApp.

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/af4392c4-87e9-48e7-8fab-6635ae2558ac)

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/372209a1-64ca-4c63-bc5d-0789c81c8768)

**Comment by AtelyPham** [comment]
Fixed by removing the `eventsWatcher` check when filtering the available relayers in https://github.com/webb-tools/webb-dapp/pull/1205
