### ISSUE TITLE
Error Connecting to Metamask Wallet

### ISSUE THREAD

**Issue by AOIshola** [webb-tools/webb-dapp#1201]
**Not able to connect to my MetaMask wallet extension on my chrome browser**

## Expected Behavior

On clicking "Connect Wallet" and selecting "Metamask", my metamask is expected to pop-up and be able to approve connection to the website.

### Current Behavior

On every first click on "Connect Wallet", there is an error connecting to the wallet. On subsequent tries, a tab showing chrome extension page is opened

## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment]
Thanks for posting! This is a duplicate, and closing in favour of: https://github.com/webb-tools/webb-dapp/issues/1193
