### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SAVAGEE96** [webb-tools/webb-dapp#1202]
## Steps to Reproduce

1.
2. site not responding fast and sometimes lagging
3.
4.

##
### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
![Screenshot 2023-05-12 at 10 58 20 AM](https://github.com/webb-tools/webb-dapp/assets/126209061/de73ff43-38dd-49a8-878c-11608237595e)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment]
Duplicate, closing in favour of: https://github.com/webb-tools/webb-dapp/issues/1210
