### ISSUE TITLE
[BUG] Transfer section not working properly

### ISSUE THREAD

**Issue by Chifire001** [webb-tools/webb-dapp#1204]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by drewstone** [comment]
Hi @Chifire001 can you please add details as far as what the bug is? Steps to reproduce, it all helps! Thank you for posting :)
