### ISSUE TITLE
[BUG]  slow working 

### ISSUE THREAD

**Issue by ks8164890** [webb-tools/webb-dapp#1209]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment]
Duplicate, closing in favour of: https://github.com/webb-tools/webb-dapp/issues/1210
