### ISSUE TITLE
[BUG] Fetching leaves during transfer causes web page to become unresponsive 

### ISSUE THREAD

**Issue by xbaystore** [webb-tools/webb-dapp#1211]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by xbaystore** [comment]
![image](https://github.com/webb-tools/webb-dapp/assets/133549630/61784ed7-a6fe-40c6-83aa-ca820aa6f5f0)

network eror in transfer

**Comment by drewstone** [comment]
Thank you for sharing! We'll look into this asap.

**Comment by dutterbutter** [comment]
Closing in favour of: https://github.com/webb-tools/webb-dapp/issues/1210
