### ISSUE TITLE
[BUG] I can't see m token after bridging goerly to agor

### ISSUE THREAD

**Issue by mohit704798** [webb-tools/webb-dapp#1213]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment]
Closing this issue as not enough details were provided. Please re-open issue, with relevant details of the issue, screenshots, and description of the problem. You may also try: 

**Please try connecting to the destination chain you bridged to, and sync your notes by navigating to the account component like so:** 


![CleanShot 2023-05-15 at 09 38 46@2x](https://github.com/webb-tools/webb-dapp/assets/29983536/f2189916-67b2-4836-95c4-7a486bedd0e4)

**Comment by mohit704798** [comment]
Nice one
