### ISSUE TITLE
[BUG]  Failed to fetch max fee info Relayer fee error: `Failed to fetch token price for token: AGOR`

### ISSUE THREAD

**Issue by rabiulhhp** [webb-tools/webb-dapp#1214]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by rabiulhhp** [comment]
Failed to fetch max fee info
Relayer fee error: `Failed to fetch token price for token: AGOR`

**Comment by shekohex** [comment]
Hey, thanks for reporting this issue, I will make sure that we solve it into our Relayers asap.

**Comment by AtelyPham** [comment]
Closed because the relayer now supports Arbitrum.
