### ISSUE TITLE
[BUG] Relayer commitment issue 

### ISSUE THREAD

**Issue by rabiulhhp** [webb-tools/webb-dapp#1215]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by rabiulhhp** [comment]
Transaction Failed
Relayer has not yet relayed the commitment to the destination chain

**Comment by drewstone** [comment]
We're you doing a transfer or a withdrawal? What error was output?
