### ISSUE TITLE
[BUG] in Destination Chain not showing a other chains only showing blank page please fix it 

### ISSUE THREAD

**Issue by Tauop11** [webb-tools/webb-dapp#1219]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by Tauop11** [comment]
I'm facing the problem in Yendex Browser 
![Screenshot_20230515_213617](https://github.com/webb-tools/webb-dapp/assets/133684354/0b504371-7b0b-474e-bce9-aa501aeeafbd)

**Comment by Tauop11** [comment]
Please fix it

**Comment by AtelyPham** [comment]
Close because the issue is resolved.
