### ISSUE TITLE
[BUG] I was bridging from sepolia goerli to scroll buh it kept on loading when i tried to generate note

### ISSUE THREAD

**Issue by TheChaNiel** [webb-tools/webb-dapp#1223]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by drewstone** [comment]
You bridged from
1. Sepolia -> Goerli (successfully)?
2. Goerli -> Scroll (unsuccessfully)?

Can you share more details and even take a screen-capture video if possible?
