### ISSUE TITLE
[FEAT] Display Warning Modal for In-progress Transactions When User Exits or Reloads Page

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1225]
**Is your feature request related to a problem? Please describe.**
When a transaction is in progress, if the user reloads or exits the page, a browser warning modal should be displayed with information about the current transaction. For example: "Transaction in progress, exiting now may result in loss of funds."

**Describe the solution you'd like**
To solve this issue, we propose utilizing the `beforeunload` event on the `window` object in the browser. Resource links for further exploration have been provided below.

**Describe alternatives you've considered**
We have evaluated the provided resource links and will choose the best solution based on performance, usability, time of implementation, and the added size of the solution to the app. As an alternative, we may choose to clone the library instead of installing it directly into the app if doing so would not take much time.

**Additional context**
We want to implement a warning modal that will pop up when the user attempts to exit or reload the page while a transaction is in progress.

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/1f11c507-5ef4-4b6f-8336-f82d0046d7c3)

## Resource links

- Learn more about the `beforeunload` event on Stackoverflow (https://stackoverflow.com/a/7317311).
- Check out the React hook for the `beforeunload` event (https://github.com/jacobbuck/react-beforeunload).
- Compare different `beforeunload` support libraries (https://npmtrends.com/before-unload-vs-react-beforeunload-vs-react-beforeunload-component-vs-unload).

**Comment by yurixander** [comment]
@AtelyPham Is this still relevant? 👀 If so, I think I have an idea on how to go about implementing this.

**Comment by yurixander** [comment]
Closing the window when a transaction was sent won't stop that transaction from completing -- it'll just not notify the user of its completion/status updates. Closing as it needs some semi-complex code to implement and it won't provide a benefit.
