### ISSUE TITLE
[FEAT] Migrate All Usage of `web3`, and `ethers` to `wagmi` and `viem` for the Web3 Provider

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1226]
**Is your feature request related to a problem? Please describe.**
Currently, we are using 2 similar libraries in the Web3 provider `web3.js` and `ethers.js`. We should consider migrating to `viem` and `wagmi` libraries to reduce the code and size of the bundles. It also supports TypeScript typings really well.

**Describe the solution you'd like**
Go through the Web3 provider classes and migrate all usage of `web3.js` and `ethers.js` to `viem` and `wagmi`. We might need to think about how we can convert our own configs (wallets, chains, ...) to be compatible with `wagmi` configs.

**Additional context**

- [wagmi docs.](https://wagmi.sh/core/getting-started)
- [viem docs.](https://viem.sh/docs/getting-started.html)

**Comment by rahulsingh3526** [comment]
Could you assign me this issue.

**Comment by AtelyPham** [comment]
You can just proceed with the implementation and submit a PR without the assignment because this issue has not yet been started.

**Comment by AtelyPham** [comment]
Any progress here @rahulsingh3526? We plan to do this task this sprint!

**Comment by AtelyPham** [comment]
Indeed, the repo is quite large, containing multiple libs and apps. Given the magnitude of this task, I would suggest starting with a smaller one in order to familiarize yourself with the repo code and how we utilize libs within the apps. Regardless, thank you so much for your interest in contributing to the repo.

**Comment by rahulsingh3526** [comment]
Yes I just understood about the lib part just a few hours ago. I earlier though the @webtools was like a npm package. I tried searching it but It wasn't in the npm . can now start learning more about monorepo and how they work. Thanks for the quick reply.
