### ISSUE TITLE
Diposit coin not successful [BUG] 

### ISSUE THREAD

**Issue by Aj741968** [webb-tools/webb-dapp#1227]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by AtelyPham** [comment]
@Aj741968 Can you provide more info here like:

- What is the error message in the notification?
- What is the error message in the browser console?
- Which chain did you deposit?
