### ISSUE TITLE
[BUG] 链接钱包后总是页面加载不出来

### ISSUE THREAD

**Issue by zhuxiaohui1177** [webb-tools/webb-dapp#1236]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by monaiuu** [comment]
Translation: Page often does not load upon wallet connection

@zhuxiaohui1177 can you provide more details on the device you are on & the browser type? 
能否提供有关使用的设备和浏览器类型的更多详细信息？
