### ISSUE TITLE
[UI] Show static image before lottie animation loads on webb marketing site.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1242]
**Is your UI update related to a problem? Please describe.**
The animation loading time takes some time and we should try to resolve it so that it feels entirely seamless. There shouldn't be any sudden changes to the picture when it loads (as best we can get it).

**Describe the solution you'd like (include image or link to prototype)**
Use a static image of the swirl without the animated objects in view, so that it looks exactly as the animation starts up. Use this static image until the animation has loaded.

Consider all different screen sizes when adding the background image, so that it matches exactly to the animation upon loading.

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1580.
