### ISSUE TITLE
[BUG] when ever you transfer funds the page gets hanged

### ISSUE THREAD

**Issue by rixdorwani** [webb-tools/webb-dapp#1250]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by drewstone** [comment]
Closing in favor of #1210
