### ISSUE TITLE
[BUG] Key rotation height is not consistent

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/webb-dapp#1260]
The key rotation is shown in the `keys` page is not correct. It does not match the last session rotation block as reflected in the chain.

## Expected Behavior
Session 80 rotated at block 29555
<img width="704" alt="Screenshot 2023-05-24 at 4 59 25 PM" src="https://github.com/webb-tools/webb-dapp/assets/106580853/4af0aabf-7fa4-465b-8664-a651f865f676">

### Current Behavior
UI shows session 80 rotated at block 29097
<img width="1265" alt="Screenshot 2023-05-24 at 4 59 20 PM" src="https://github.com/webb-tools/webb-dapp/assets/106580853/92b8357f-1787-4888-97ab-4e4cf8259abc">

**Comment by devpavan04** [comment]
@1xstj As discussed this issue will be closed by adding `Rotated` status in the `Timeline` component after `Generated` status.

![CleanShot 2023-08-31 at 10 55 26](https://github.com/webb-tools/webb-dapp/assets/53374218/b53174e1-b5bd-49c8-86e9-caefd0f93b08)
