### ISSUE TITLE
[BUG] Proposal signers are always listed as `abstain`

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/webb-dapp#1261]
In the details of a proposal, signed or unsigned all the authorities are listed as `abstain`

**Unsigned Proposal**

<img width="715" alt="Screenshot 2023-05-24 at 5 08 58 PM" src="https://github.com/webb-tools/webb-dapp/assets/106580853/de010dcf-7cc1-410c-a5d1-1eb98171445c">

**Signed Proposal**

<img width="712" alt="Screenshot 2023-05-24 at 5 01 21 PM" src="https://github.com/webb-tools/webb-dapp/assets/106580853/d688c735-0e9d-463d-89ed-d89c2576c858">

**Comment by devpavan04** [comment]
Closing this as we're currently not showing proposer votes of proposal batches in `stats-dapp`.
