### ISSUE TITLE
[BUG] Time calculation is based on UTC

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/webb-dapp#1262]
The UI uses UTC time to perform calculations, this ends up producing wrong assumptions in the UI. aka a proposal signed right now will show as signed X hours before.

Proposal signed just a minute before:
<img width="707" alt="Screenshot 2023-05-24 at 5 01 33 PM" src="https://github.com/webb-tools/webb-dapp/assets/106580853/94897345-9b8f-4410-ba2b-50164cc7d22c">

**Comment by rahulsingh3526** [comment]
What would you like the time to be based on then ??
