### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mina12df** [webb-tools/webb-dapp#1267]
## Steps to Reproduce

1. I can not withdraw anymore
2.
3.
4.I can not transfer anymore

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by Mina12df** [comment]
I can not withdraw and transfer anymore, Your network is so low

**Comment by AtelyPham** [comment]
Hello @Mina12df! Thank you for opening the issue! Could you please provide us with more information about the transaction that you made?

- On which chain did you deposit?
- From which chain did you withdraw or transfer?
- Did you use the relayer or not?
- What does the error show on the notification?
- What is the output in the browser console?

This information will help us to more easily determine the issue and resolve it. Thank you.

**Comment by Mina12df** [comment]
I deposit source chain sepolia from ETH token to Webbalpha. I unwrap from
Webbalpha to ETH token and I also use relayer, you can see the picture that
i attached. The withdrawal process only went 1/4 of the way and then it
failed to record anymore, causing my screen to freeze too. it also doesn't
let me sign anything like in the deposit process.  Please tell me more
about  browser console, i am not familiar with it. Thanks alots
