### ISSUE TITLE
[TASK] Investigate and Fix Distorted Heading Text on Mobile Devices for Marketing Websites

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1281]
## Description

Distorted heading texts appear on mobile devices for marketing websites. Please investigate the issue's cause and ensure consistent rendering with desktop & figma views. See below Netlify preview screenshot for reference.

![Image](https://user-images.githubusercontent.com/109539270/242420811-ac95b542-c845-4c83-b201-b0d4e0079203.png)

Please note that this doesn't seem to be an issue when going into mobile breakpoints on desktop view:

![Image](https://user-images.githubusercontent.com/109539270/242423722-7ee74b91-e336-4ba0-9ccf-1476325da86e.png)

**Comment by vutuanlinh2k2** [comment]
@monaiuu I have spent some time investigating this task today. Here are some interesting facts that I noticed: 

- the **error** occurred on **iPhone and iPad only** (applied to all browsers), which means for Desktop (all browsers) and Android phones, this works fine
- the difference appears because the font **Satoshi-Variable** is not being applied in those cases, but the **default** font is
- however, for **normal text**, the **Satoshi-Variable** is still being applied

=> Since only the text with font-weight 900 is not being applied, I think you should check back the font files for both [normal](https://github.com/webb-tools/webb-dapp/blob/develop/libs/webb-ui-components/src/fonts/Satoshi-Variable.ttf) and [italics](https://github.com/webb-tools/webb-dapp/blob/develop/libs/webb-ui-components/src/fonts/Satoshi-VariableItalic.ttf) that we are currently using.

Let me know if you have any follow-up questions or concerns 😊

**Comment by monaiuu** [comment]
@vutuanlinh2k2 Thanks for taking the time to investigate this issue. 

Given that the issue with the Satoshi Variable font's weight of 900 is only occurring on iOS devices and not on other platforms, I think this might be less likely to be an issue with the font file itself and more likely a compatibility issue with iOS's font rendering.

To address this, I propose using the static Satoshi font as a fallback specifically for iOS devices. This would involve including the Satoshi static font file with a weight of 900 in our font assets and updating our CSS to use this font when the Satoshi Variable font weight of 900 is not rendered properly.

In this scenario, the browser will attempt to use the Satoshi Variable font. If it's unable to render correctly, it will fall back to the static Satoshi font.

Let me know your thoughts or if there's an alternative suggestion!

**Comment by monaiuu** [comment]
I believe we already have the static fonts in the files shown below:

<img width="889" alt="Screenshot 2023-06-22 at 11 06 48 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/19c8d555-17d1-40ef-819b-1b033e2fa03d">

**Comment by AtelyPham** [comment]
Sounds good to me 👍

**Comment by AtelyPham** [comment]
You can try this by adding the `'Satoshi'` after the `'Satoshi Variable'` [here](https://github.com/webb-tools/webb-dapp/blob/0dcc454c304dbdb65ea3f1e4df9bca5ef4181b0c/libs/webb-ui-components/src/css/typography.css#L103-L104) @vutuanlinh2k2.

**Comment by vutuanlinh2k2** [comment]
@monaiuu I'm adding the `Satoshi` font as a fallback for the `Satoshi Variable` font but still got the same result, meaning that the `Satoshi Variable` is actually being applied here. So for IOS devices, it still can load the `Satoshi Variable`, but the display of the font is different 😅 Let me know your thought on this.

Here is the difference between the `Satoshi` and the `Satoshi Variable` if it's on mobile:

## Satoshi:
If I put `'Satoshi', -apple-system, BlinkMacSystemFont, Arial, sans-serif` as the font
![IMG_2377](https://github.com/webb-tools/webb-dapp/assets/69841784/130fef84-7117-4b0b-b712-96127437e422)

## Satoshi Variable:
If I put `'Satoshi Variable', 'Satoshi', -apple-system, BlinkMacSystemFont, Arial, sans-serif` as the font
![IMG_2378](https://github.com/webb-tools/webb-dapp/assets/69841784/01de1514-6d1d-4e6f-8cb6-50aa970ef718)

**Comment by monaiuu** [comment]
> @monaiuu I'm adding the `Satoshi` font as a fallback for the `Satoshi Variable` font but still got the same result, meaning that the `Satoshi Variable` is actually being applied here. So for IOS devices, it still can load the `Satoshi Variable`, but the display of the font is different 😅 Let me know your thought on this.
> 
> Here is the difference between the `Satoshi` and the `Satoshi Variable` if it's on mobile:
> 
> ## Satoshi:
> If I put `'Satoshi', -apple-system, BlinkMacSystemFont, Arial, sans-serif` as the font ![IMG_2377](https://user-images.githubusercontent.com/69841784/248439599-130fef84-7117-4b0b-b712-96127437e422.PNG)
> 
> ## Satoshi Variable:
> If I put `'Satoshi Variable', 'Satoshi', -apple-system, BlinkMacSystemFont, Arial, sans-serif` as the font ![IMG_2378](https://user-images.githubusercontent.com/69841784/248439645-01de1514-6d1d-4e6f-8cb6-50aa970ef718.PNG)

Is there a preview link I can take a look on mobile? The first image you shared in the comment definitely looks better IMO.
