### ISSUE TITLE
[TASK] Standardize Asset and Network treatment

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1282]
## Description
Please update the network's treatment to distinguish from tokens to improve clarity and standardize how elements are represented. 

![Image](https://user-images.githubusercontent.com/109539270/230466635-8771030f-e60f-498c-a3a1-8c02ea829ae0.png)

- For `token` representation, we will remain using `circular` shapes to represent tokens.

- For `network/chain` representation, we will update to a `rectangular` shape to represent networks.

- To align with this update, the `chain chips` previously implemented will require an update to their `radius` to align with the chain representation.

### Design System Updates
These components have been added to the design system; please reference the following pages for reference:

- **'🟢  [Avatars](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=30%3A352&t=zL5xxCWbLFEeiJRw-1)'** for added relayers and shielded token/pools treatment.
![Image](https://user-images.githubusercontent.com/109539270/230469065-709781fa-d217-46ad-bc6a-3d75e82197bd.png)

- **'🟢  [Chain Icons](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=4746%3A101498&t=zL5xxCWbLFEeiJRw-1)'** for updated chain icon display & chain chips display.
![Image](https://user-images.githubusercontent.com/109539270/230469089-03e3a2e2-a37e-4883-b689-569b41d36643.png)

Please note for this update, we will also have to ensure all dependent components are updated accordingly. I have audited and reviewed the entire design system and updated the component treatments accordingly. This update has also been pushed and should now similarly apply to all project files within Figma.

**Comment by drewstone** [comment]
# Checklist
- [ ] Making updates to the webb UI kit in the design system
- [ ] Previous usage has been all circles for all items, we have to now differentiate between the different subject matter.
- [ ] Should apply to all relevant pages (Hubble bridge, Stats, upcoming Hubble Stats)

**Comment by monaiuu** [comment]
Figma Dev Mode Links:

[Avatars](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=164%3A4563&mode=dev)
[Chain Icons](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=4155%3A59526&mode=dev)

**Comment by monaiuu** [comment]
Edit: Put shielded icons ON HOLD for this issue. I will create a separate issue to address icons to represent shielded pools/assets. 

This issue is OK to merge with the completion of `token`, `chain`, and `relayer` treatment. 

@vutuanlinh2k2
