### ISSUE TITLE
[FEAT] Implement Tangle Testnet Incentive Campaign Leaderboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1284]
## Description
Please see below for the implementation details of the Tangle Leaderboard. The leaderboard will showcase top contributors based on their activities and points accrued. The activities are divided into seven categories and each category has its own corresponding badge.

### User Interface: 
This page should support mobile-responsive design and use the same background image and breakpoint system as the main Tangle website.

Develop a leaderboard table to display:

- Rank
- Identity (Avatar & Wallet Address)
- Role (Category/Badge)
- Total Points
The leaderboard should be responsive according to breakpoints.

### Badges: 
Each category should have its own unique badge represented by a specific emoji. The categories and corresponding emojis are as follows:

- 🎨 Content Creator
- 🛠️ Developer
- 🏛 Governance Guardian
- 💡 Innovator
- 📡 Relayer
- 🔁 Tx Specialist
- 🔐 Validator

The badges need to display next to the user's Identity (Avatar & Wallet Address) in the Role column.

### Checklist
- [ ] Countdown Timer: Implement a countdown timer component according to design handoff. This timer will show the remaining time for the current competition cycle.
- [ ] Search Function: allow participants to quickly find standings on the leaderboard based on searched wallet address.
- [ ] Implement CTAs
- **View Guidelines**: This will redirect users to the doc site to view the guideline & activity list for earning points.
- **Request Points**: This will redirect users to Webb's discord channel for users to request points for off-chain activities. 
- [ ] Implement Leaderboard Table
- [ ] Implement Pagination Component
- [ ] Implement desktop, tablet, and mobile breakpoints
- [ ] Implement FAQ section with accordion component
- [ ] Add background image (use the same image as Tangle Website)
- [ ] Data Integration: The leaderboard will be populated by real-time data based on the actions of the users. We will needs to integrate the leaderboard with our data sources to reflect accurate and real-time information.

### Screenshot
![Image](https://user-images.githubusercontent.com/109539270/242436225-799ae0ea-cf51-4d18-9d02-9e21fd1a1ce8.png)
<img width="1750" alt="Screenshot 2023-05-31 at 5 45 34 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/f0144f73-950c-4fbc-866d-3e9fbf67b68a">

### Figma File
https://www.figma.com/file/n9uVKE44Ib4aH5HEpRrGS3/%F0%9F%8F%86--Tangle-Leaderboard?type=design&node-id=49%3A1360&t=0XCMYqJMI9jcStiB-1

**Comment by vutuanlinh2k2** [comment]
@monaiuu @drewstone is this task requires only UI or functionalities also? If we need functionalities, can you provide a way to get the data?

**Comment by drewstone** [comment]
Yes only UI for now. For the clock if you want to implement a count down
you can do so or create a new task. In that event just use hyphens for
placeholders — — —.
