### ISSUE TITLE
[FEAT] Handle when clicking Faucet on the Navigation Menu of the Bridge Dapp

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1297]
**Problem**
There is no functionality when clicking the Faucet item in the Navigation Menu in the Bridge Dapp. This is also mentioned [here](https://github.com/webb-tools/webb-dapp/pull/1285#pullrequestreview-1455774024).

**Desired solution**
Possibly we will navigate users to the Faucet website when they click on the Faucet.

**Images**
<img width="286" alt="Screenshot 2023-06-05 at 16 47 35" src="https://github.com/webb-tools/webb-dapp/assets/69841784/bec7b5fa-c2a6-4b54-b61c-38a8853803c3">

**Comment by AtelyPham** [comment]
We have the live faucet here https://faucet.webb.tools @vutuanlinh2k2.
