### ISSUE TITLE
[FIX] Update Blog Thumbnail Images and Blog Footer

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1298]
### Overview
Our new blog implementation uses Ghost CMS and there are a few UI fixes to be made.

- [x] Fix the blog thumbnail images.
- [ ] Update the footer, use footer from webb-ui-components.
- [ ] Update the webb logo link to point to webb.tools/

![CleanShot 2023-06-05 at 07 29 10](https://github.com/webb-tools/webb-dapp/assets/53374218/9e12c2f7-c15b-4b13-a908-e4e55b4b012d)
![CleanShot 2023-06-05 at 07 33 45](https://github.com/webb-tools/webb-dapp/assets/53374218/e8b9a3c2-c5e7-4eb7-ae1a-4b75c68d0b81)

**Comment by monaiuu** [comment]
Thumbnail images have been addressed (see here: https://www.blog.webb.tools/). 

I attempted to have logo redirect to webb.tool; but was unable to find a solution directly within Ghost; may require dev help.

**Comment by devpavan04** [comment]
- Removed footer for now.
- Updated the logo link to redirect to https://webb.tools/


https://github.com/webb-tools/webb-dapp/assets/53374218/ded6244d-951e-4226-8c68-8b4c2ae74766
