### ISSUE TITLE
[TASK] Add TVL and Volume chips in the navigation panel

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1300]
## Description

<img width="548" alt="Screenshot 2023-06-05 at 10 12 55 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/fce108b0-8c4b-4074-85c9-f645dca6344f">

To implement the above task, please proceed with the following:
- [x] Implement chip component from webb UI kit

**Comment by monaiuu** [comment]
## Description
<img width="548" alt="Screenshot 2023-06-05 at 10 12 55 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/fce108b0-8c4b-4074-85c9-f645dca6344f">
- [ ] Implement chip component from webb UI kit
- [ ] Implement functionality to dynamically fetch and display the latest TVL and Volume data in the chips.

**Comment by devpavan04** [comment]
Added in #1376
