### ISSUE TITLE
[TASK] Create the key metrics table (Total txs, TVL, volume, fees)

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1302]
## Description
<img width="831" alt="Screenshot 2023-06-05 at 9 37 25 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/23dc0ae1-568e-4f38-88aa-925cceb5c825">

Please implement the key metrics table for the overall aggregated activities on Hubble for the following metrics:

- [ ] Total Transactions 
- [ ] TVL (value should be consistent as the TVL chart component above)
- [ ] Total Volume
- [ ] Total Fees

Please also implement the % change as indicated on the Figma File. For positive % use `Light/Green/70`; for negative % use `Light/Red/70`. 

Figma Link: https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=651%3A94890&t=Es5JbjODciB7fEMM-1

**Comment by drewstone** [comment]
Linked to: [#1058](https://github.com/webb-tools/webb-dapp/issues/1058)

**Comment by monaiuu** [comment]
## Description
<img width="831" alt="Screenshot 2023-06-05 at 9 37 25 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/23dc0ae1-568e-4f38-88aa-925cceb5c825">

Please implement the key metrics table for the overall aggregated activities on Hubble for the following metrics:

- [ ] Total Transactions 
- [ ] TVL (value should be consistent as the TVL chart component above)
- [ ] Total Volume
- [ ] Total Fees

Figma Link: https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=651%3A94890&t=Es5JbjODciB7fEMM-1

**Comment by rahulsingh3526** [comment]
can you assign this to me.

**Comment by drewstone** [comment]
Hi @rahulsingh3526 this is currently allocated and requires access to our figma designs. Let's chat if you're interested to help out: https://calendly.com/drewstone.
