### ISSUE TITLE
[TASK] Implement failed state modal for Faucet

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1326]
## Description
Implement failed state modal if the transaction request is unsuccessful. For the buttons, user may either 'Try Again', or 'Report Bug', which would direct the user to our GitHub to report any issues. 

<img width="1219" alt="Screenshot 2023-06-09 at 5 46 57 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/46d72a6e-b687-4593-979c-0c06243aa0c1">

Figma Link: https://www.figma.com/file/t0bIz5vsiN48ZdwoeBJUge/%E2%9B%B2%EF%B8%8F-Faucet?type=design&node-id=515%3A13804&t=DMN6JEWwD3kpKfCo-1

Lottie Link:
https://lottiefiles.com/137316-cross-loop

**Comment by shekohex** [comment]
The Faucet API returns few information, like the error message and the reason why this tx failed, in addition to that, it also returns the last time this user claimed and how much time the user have to wait between two claims (in ms). Maybe in that case you should show in the model something like "You can claim again after <TIME_HERE>" or "You have to wait [x]h [y]m to claim again." ..etc

**Comment by monaiuu** [comment]
I have added a few more possible errors modal, see below:

<img width="1219" alt="Screenshot 2023-06-09 at 5 46 57 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/8a934dbd-23d9-45f9-84dc-ffbe6e1bb6cb">
