### ISSUE TITLE
[SPEC] dApp Release Process and Proposed Improvements

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1339]
### Current Release Process on the `webb-dapp` Repo

1. Create a release branch from the **`develop`** branch.
2. Manually update the version in **`package.json`** and **`CHANGELOG.md`**.
3. Open a pull request with a **`[RELEASE]`** tag on the title, choosing the base branch as **`develop`**.
4. Run a _**force merge**_ on the **`master`** to **`develop`** after merging the release pull request on develop to trigger the release of dApps on Npm and Github.

### Current Pain Points of the Release Process

- Manually updating the version in **`package.json`** and **`CHANGELOG.md`** takes time and is cumbersome for multiple app releases.
- The release process still requires an admin to run a _**force merge**_ on the **`master`**.

### Improvement proposals

- Utilize tools to automate the updating and detection of versions and changes.
	- [Release-it](https://github.com/release-it/release-it)
	- [changesets](https://github.com/changesets/changesets)
	- [Nx plugin for versioning and CHANGELOG generation](https://github.com/jscutlery/semver)
- Implement a GA to automate the _**force merge**_ on the **`master`** to **`develop`** process.

@drewstone, @devpavan04, and @vutuanlinh2k2, please review this issue and provide your feedback. Thank you.

**Comment by drewstone** [comment]
Is there any way we can monitor changes for a specific app and execute releases for the apps only?

**Comment by AtelyPham** [comment]
I'm not entirely sure if Fleek supports this feature, but I can certainly use your question as a starting point for my investigation.

**Comment by drewstone** [comment]
Closing since I think we've found process now.

**Comment by AtelyPham** [comment]
The purpose of this issue is to automate the process. The current process still has some pain points:

- Manually updating the version in package.json and CHANGELOG.md is time-consuming and cumbersome, particularly for multiple app releases.
- The release process still necessitates an admin to execute a force merge on the master.

I believe we can automate these tasks.

**Comment by yurixander** [comment]
@AtelyPham Mind if I take a shot at this one? 👀

**Comment by AtelyPham** [comment]
This is part of the work on upgrading Nx to v19, which I'm currently working on. After upgrading to Nx v19, it will be easier to automate the deployment process. I will get back to this after submitting the PR for upgrading to Nx v19, which should be completed around today or tomorrow.
