### ISSUE TITLE
[FEAT] Tangle Leaderboard Functionalities

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1343]
**Is your feature request related to a problem? Please describe.**
The Tangle Leaderboard UI task is ready here. Need to add functionalities to it, including the clock and table data.
Also the links for the buttons and FAQ items also need to be update.

**Describe the solution you'd like**
The following categories should be done:
- [ ] **Button links**
- [ ] **FAQ**
- [ ] **Clock**

**Post-launch**
An easy tutorial for manually adding data.
- [ ] Ranking Table

**Additional context**
Refer back to the UI issue [here](https://github.com/webb-tools/webb-dapp/issues/1284)

**Comment by drewstone** [comment]
CC @thomivy to discuss the ranking table. What we plan to be manual, what we plan to automate? Should we use a Notion table and keep it all manual, etc.

**Comment by thomivy** [comment]
To clarify we need automated infra for the following, which can arrive 2-3 weeks after testnet launch at the latest, earlier the better. We have a manual submission process setup. 

https://www.notion.so/hicommonwealth/Public-Facing-Terms-and-Promo-Doc-68b4b70d37ab4e4c87100e74c31a9a22?pvs=4
