### ISSUE TITLE
Use the chart component from `webb-ui-components` to display data in pool details

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1346]
Dependency: https://github.com/webb-tools/webb-dapp/issues/1057

## Description
This task requires the implementation of the chart component on the specified shielded pool/asset page for the following metrics:
- [ ] Total Value Locked (TVL)
- [ ] Volume
- [ ] Fees
- [ ] Add network fiter to above graphs, so that users can view data for specific network (optional -- can be deferred)
- [ ] Retrieve the relevant data for TVL, Volume, and Fees from the backend API endpoints.

## Screenshot
<img width="1026" alt="Screenshot 2023-07-20 at 4 36 14 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/92747500-7f90-4371-8609-82a03e0802c3">

**Comment by rahulsingh3526** [comment]
can I have the graph link to this

**Comment by vutuanlinh2k2** [comment]
@devpavan04 since you are also working with [chart component](https://github.com/webb-tools/webb-dapp/issues/1301) on the Overview page, I think it's the best if you also do this.

Feel free to assign this to yourself if you find this ok!

**Comment by monaiuu** [comment]
@devpavan04 I believe you have already completed implementing this.

**Comment by devpavan04** [comment]
@vutuanlinh2k2 @monaiuu Yes this UI chart has been added to `webb-ui-components` already [here](https://github.com/webb-tools/webb-dapp/blob/develop/libs/webb-ui-components/src/components/ChartContainer/ChartContainer.tsx).

@vutuanlinh2k2  We can pass any type of chart as a children to this container.

**Comment by devpavan04** [comment]
@vutuanlinh2k2 @monaiuu Since UI for charts is ready, I've created a new issue to fetch data for all the chart components in `hubble-stats` here - #1493 and closing this.

**Comment by vutuanlinh2k2** [comment]
@devpavan04 I see the chart is not available on Hubble Stats at the moment, can you check that again

<img width="1152" alt="Screenshot 2023-08-03 at 15 09 08" src="https://github.com/webb-tools/webb-dapp/assets/69841784/1b8d2125-7daa-4b3b-b175-363087b18107">

**Comment by monaiuu** [comment]
@devpavan04 @AtelyPham 

I recall seeing the chart completed above in one of the preview links previously; unless I remember incorrectly. Could you guys check on the status on this?
