### ISSUE TITLE
[TASK] Implement pool data table across all networks

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1347]
## Description
The task is to implement a network table that displays key metrics such as TVL (Total Value Locked), Volume, and Fees for each side of the chain for the pool data.

### Table Tabs

- TVL: Display the Total Value Locked on each side of the chain 
- Volume: Show the trading volume on each side of the chain 
- Relayer Fees: Indicate the relayer fees generated on each side of the chain 
- 24H Deposits: Indicate the number of deposits within the pool.
- Aggregate: Show the total amount of each each category within the pool across all networks.

Note: While there is a plan to highlight tokens in the 'danger zone' due to low liquidity in the future, it will be put on hold for now as we are still in the testing phase.

## Screenshot
<img width="970" alt="Screenshot 2023-07-20 at 3 10 13 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/f86786a9-c370-4ea6-a770-d73ff27f0d03">
<img width="1641" alt="Screenshot 2023-07-20 at 3 12 43 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a12a3ab4-7b41-4734-a257-415ac1ce194e">

**Comment by vutuanlinh2k2** [comment]
@monaiuu you can update this issue based on the new design of the Pools and Tokens tables in Pool Stats or create a new one from this!

**Comment by monaiuu** [comment]
I have updated this task to only 'Pool Tables' in displaying TVL, Volume, 24H Deposits, and Relayer Fees. Will create a separate task for the 'Token Tables' to display TWL and Wrapping Fees.
