### ISSUE TITLE
[FEAT] Implement pool transactions tables (deposit, transfer, withdraw)

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1348]
## Description
The task is to implement tables for deposits, withdrawals, and transfers, each displaying specific activity details. These tables will provide a comprehensive view of user transactions within the application.

### Table Items:
- Activity Type: Indicate the type of activity (deposit, withdrawal, or transfer).
- Token Amount: Display the amount of tokens involved in the activity.
- Source Chain: Show the chain from which the tokens originate.
- Destination Chain: Indicate the chain to which the tokens are transferred.
- Time: Display the timestamp or date and time of the activity.

## Screenshot
<img width="910" alt="Screenshot 2023-06-14 at 1 37 34 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/d3bd0457-7b03-42a7-8b9f-b5603fecde67">

Figma Link:
https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=814%3A131836&mode=dev

**Comment by AtelyPham** [comment]
This issue has been assigned `3` points, considering it as a half-day task. Please react with 👍 if you agree. Alternatively, feel free to propose a different point value if you believe the task requires more or less effort. @webb-tools/dapp-team.

**Comment by AtelyPham** [comment]
The filter for this table should be addressed in a separate issue.
