### ISSUE TITLE
[FEAT] Implement pool metadata table

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1349]
## Description
Implement a pool metadata table that displays relevant information about each pool. This table will be useful for users to view details about the specified pools within the protocol.

The table should include the following attributes for each pool:
- Pool Symbol: Display the symbol or abbreviation representing the pool.
- Pool Name: Show the name or identifier of the pool.
- Various Addresses relevant to the pool
- Wrapping Fees
- Creation Date: Display the date when the pool was created.

## Screenshot
<img width="649" alt="Screenshot 2023-06-23 at 10 17 08 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/cc92e163-8f83-4476-a62c-f5c062dda033">

### Figma Link
https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=814%3A128469&mode=dev

**Comment by AtelyPham** [comment]
This issue has been assigned `2` points, considering it as a half-day task. Please react with 👍 if you agree. Alternatively, feel free to propose a different point value if you believe the task requires more or less effort. @webb-tools/dapp-team.
