### ISSUE TITLE
[TASK] Display entire token composition in notes table

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1387]
## Description
Currently, we do not display the entire token composition in the notes table, causing confusions for users, as there is no way to easily access this info. Since we do have the space within the table, let's display the entire token composition by stacking more tokens.

This update should be applied in both **Shielded Assets** tab and **Available Spend Notes** tab. 

### Current
![Image](https://user-images.githubusercontent.com/109539270/249837187-42d49b65-d4fa-41a4-bd36-e76a670499b7.png)

### Proposed Update
![Image](https://user-images.githubusercontent.com/109539270/250098666-c958324f-316b-409d-b9a3-aca78d474b16.png)

**Comment by drewstone** [comment]
Planning poker

**Comment by monaiuu** [comment]
I see this issue is closed, but I just made a new transaction and I still see the tokens as stacked in the following:

<img width="1248" alt="Screenshot 2023-07-18 at 4 05 53 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/bbe2262d-9e14-4ec4-ab44-e2e316f9d1e2">
<img width="1222" alt="Screenshot 2023-07-18 at 4 05 44 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/735f534a-ec3c-4ede-9ec2-90232a41e1c4">

As a user, I would want to see the entire token composition in the table so I know what makes up the pool. I am also curious why the composition updates between tabs.
