### ISSUE TITLE
[TASK] Implement & add `Toggle Card` component to UI Kit

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1403]
## Description
This issue involves the implementation of a new `Toggle Card` component. This component will provide users with a clear and intuitive interface for toggling between different options or settings.

Example usages:
- Enable/Disable Refund
- Enable/Disable Relayer

### Screenshot
![Screenshot 2023-07-06 at 7 30 01 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/e228310d-ed23-4f29-ad9a-df44142052a0)

**Comment by AtelyPham** [comment]
Closed in #1468.
