### ISSUE TITLE
[TASK] Implement `Transaction Input Card` component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1405]
## Description
This task involves the creation and implementation of the `TransactionInputCard` component. This component will serve as the primary interface for users to select networks, tokens, and specify the transaction amount.

This component is created with the following property types:
- Default: used in deposit & transfer
- Fixed Amount: used in withdrawing fixed amounts
- Custom Amount: used in withdrawing custom amounts

### Dependencies:

- https://github.com/webb-tools/webb-dapp/issues/1399
- https://github.com/webb-tools/webb-dapp/issues/1406

### Figma Link
https://www.figma.com/file/wQulr8fTsVqWvFk17QWdhu/%F0%9F%8C%81--Bridge-UI-v2?type=design&node-id=771%3A145294&mode=dev

## Screenshot
![Screenshot 2023-07-06 at 8 15 21 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/00601811-6cf1-4ccc-b9db-fd5d0ed7525d)

**Comment by AtelyPham** [comment]
Closed in #1548.
