### ISSUE TITLE
[TASK] Update `Selector` component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1406]
## Description
This issue involves updating the existing `Token Selector` component to ensure it aligns with the overall updated designs of the application.

**Note:** We currently already have a Token Selector component in our UI Kit, we should update with latest version accordingly: https://webb-tools.github.io/webb-dapp/?path=/docs/design-system-molecules-tokenselector--docs

## Screenshot
<img width="1341" alt="Screenshot 2023-07-07 at 11 25 55 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/3fb5047e-65a5-4fd1-a3ae-26b257467107">

**Comment by AtelyPham** [comment]
Closed in #1497.
