### ISSUE TITLE
[TASK] Update `Address Input` component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1410]
## Description
The recipient input has been improved to better accommodate the input of long addresses. Please see the various states of the recipient input depending if it is active or not. The input has also added icon button components in the right bound to enable options like pasting user's own address, or paste from clipboard, and copying the address. 

### Note

- Once an address has been inputted, it becomes truncated when the input field is not in active state. This means that only the first and last few characters of the address are displayed, making the field more manageable and less cluttered. (see bottom screen recording from [1inch](https://github.com/webb-tools/webb-dapp/assets/109539270/3fda5ec8-ae04-4e36-baa4-92bd7980c8be) for reference)

### Screenshot
<img width="799" alt="Screenshot 2023-07-07 at 2 37 55 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/3679ced1-2ced-47f3-a31d-1411e3dbb7a3">

### Screen Recording
https://github.com/webb-tools/webb-dapp/assets/109539270/9cf13511-1967-4ad9-99bf-1f9ba366f7c3

Below displays an example from 1inch of how the recipient input behaves.
https://github.com/webb-tools/webb-dapp/assets/109539270/3fda5ec8-ae04-4e36-baa4-92bd7980c8be

**Comment by AtelyPham** [comment]
Closed in #1531.
