### ISSUE TITLE
[TASK] Update `Chain Connection` component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1411]
## Description
The `Chain Connection` component has been improved visually and added hover state. Please add this component to storybook doc, as it will be repeatedly used across the applications. 

### Note
- Let's incorporate consistent conventions for displaying chains/networks, opting for a single-word representation when it aligns with the context. Consider examples like "Mumbai" rather than "Polygon Mumbai". 

### Screenshot
<img width="853" alt="Screenshot 2023-07-07 at 3 06 59 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/c5a8a42a-82ab-4f6d-a980-05df714022aa">

**Comment by AtelyPham** [comment]
Closed on #1489.
