### ISSUE TITLE
[TASK] Update `Token List` to include added properties

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1412]
## Description
Previously, all list components have been commingled (token, chain, relayer etc), proposing to separate them to improve schematic organization. 
### Updates:
- added display for fiat equivalence
- added insufficient liquidity property (this enables us to disable the list component and display warning badge to inform users)
- added rounded radius for improved visual

### Screenshot
<img width="672" alt="Screenshot 2023-07-18 at 3 28 54 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/1d969a95-03f4-4c1d-b72f-4bb5926233a2">

**Comment by AtelyPham** [comment]
Closed in #1526.
