### ISSUE TITLE
[TASK] Update `Relayer List` (add radio button)

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1413]
## Description
The relayer list should be updated with radio buttons so that this allows users select and deselect a relayer. We should also enable fees % display if possible. 

### Screenshot
![Screenshot 2023-07-17 at 5 06 04 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/afe8e95e-e99b-4858-9915-a2806020d0e2)

**Comment by AtelyPham** [comment]
Closed in #1526.
