### ISSUE TITLE
[TASK] Update `Wallet Address` component & add to  UI Kit

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1414]
## Description
To ensure consistency with the update of the `Chain Connector` component, please update the `Wallet Address` component according to figma file. We should add this component to webb UI kit as it is repeatedly used across applications.l

### Screenshot
<img width="970" alt="Screenshot 2023-07-07 at 4 56 00 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/91b1fec4-7ec9-4b3b-82ea-0f9b95823bfb">

**Comment by AtelyPham** [comment]
Closed on https://github.com/webb-tools/webb-dapp/pull/1489.
