### ISSUE TITLE
[TASK] Standardize time display format across applications

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1419]
## Description
Currently, our applications lack a standardized format for displaying time, leading to potential confusion and reduced usability. To enhance the user experience and ensure consistency, lets standardize the time display format throughout the application. 

### Proposed Solution
- Implement `date-fns`, a JavaScript date utility library, to standardize time display. ([link](https://date-fns.org/docs/Getting-Started))
- Note: we need to define a standard format for displaying time AND relative time using the formatting options provided by date-fns. 

### Screenshot
![Image](https://user-images.githubusercontent.com/109539270/245228878-223988ac-b6e8-4388-b213-6a2a158fbb6e.png)

**Comment by drewstone** [comment]
https://github.com/webb-tools/webb-dapp/issues/1262
