### ISSUE TITLE
[TASK] Add `Stepped Progressor` component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1420]
## Description
Implement and add stepped progressor component to UI kit to provide a more visual and intuitive way to track progress. The component should handle transitions between different states smoothly. 

### Screenshot
<img width="1186" alt="Screenshot 2023-07-11 at 11 35 25 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/dd285d8f-549f-4cf6-9beb-974ad1ae9dd0">

**Comment by AtelyPham** [comment]
Closed in #1531.
