### ISSUE TITLE
[TASK] Implement UI for wrapping flow

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1427]
## Description
Below details the UI implementation and requirements for the wrapping flow using Hubble v2 components. 

### Requirements
- **Source Tokens Display:** Display all available tokens on the connected network that are part of the Webb shielded pools composition.
- **Token List Display Order:** Tokens should be ranked firstly by available balance and then alphabetically.
- **Wrapping Fee and Receiving Amount:** The wrapping operation incurs a fee. Hence, the receiving amount should be dynamically rendered based on the input amount. For instance, if a user is depositing 1.00 WETH, and the wrapping fee is 1%, the receiving amount should dynamically render as 0.99 webbETH.
- **Button CTA Label Update:** Labels within the button CTA should update depending on the various states and stages as indicated in the figma file.

### Screenshot
<img width="1299" alt="Screenshot 2023-07-14 at 9 13 31 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/c9bee743-ea97-4d6d-b8c7-cc7ab34de162">

**Comment by vutuanlinh2k2** [comment]
This task also covers setting up the route and building up the UI for wrapping flow
