### ISSUE TITLE
[TASK] Improve dApp README

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1442]

**Comment by AtelyPham** [comment]
Additional tasks for this issue:

- [ ] Combine `api-provider-environment` and `react-environment` into a single library, as their functions are notably similar.
- [ ] The `fixtures-deployments` library solely contains the function for retrieving fixtures from `AWS` and caching the result in the browser. This function should be transferred to a different library (for instance, `browser-utils`), and the `fixtures-deployments` library should be subsequently removed.
- [ ]  The `storage` library exclusively houses the `Storage` class. This class should be relocated to either `dapp-types` or `abstract-api-provider`, followed by the removal of the `storage` library.
