### ISSUE TITLE
Implement functionality to dynamically fetch and display the latest TVL and Volume data in the chips.

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1448]
### Overview
Implement functionality to dynamically fetch and display the latest TVL and Volume data in the chips in `hubble-stats`.

![CleanShot 2023-07-18 at 05 04 08](https://github.com/webb-tools/webb-dapp/assets/53374218/4d4141ad-2c85-4f85-b453-d0d0c4395738)

**Comment by AtelyPham** [comment]
Dup of https://github.com/webb-tools/webb-dapp/issues/1448.
