### ISSUE TITLE
[TASK] Update useDarkMode hooks

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1450]
@AtelyPham, you can add additional context and Estimation here.

The issue was mentioned [here](https://github.com/webb-tools/webb-dapp/pull/1431#discussion_r1266678689).

**Comment by AtelyPham** [comment]
### Current problem

The current hook only reads values from local storage and does not respond to changes in these values. If we use this hook in multiple components, and one of these components updates the local storage, the other components will not be aware of these updated values and will not update accordingly.

### Propose solution

I propose we refactor this hook to both read and synchronize the state (in this context, the theme value) with local storage. We can achieve this by using the `use-local-storage-state` npm library. An example of this can be found in the `faucet` app, where you can see how I stored and synchronized values from local storage, binding these values with the React state to ensure the UI updates. Another instance where this technique is used can be found in the `SideBar` open state; I've provided a link to this example below.

### Useful links

[use-local-storage-state library](https://www.npmjs.com/package/use-local-storage-state)
[Example from Faucet app](https://github.com/webb-tools/webb-dapp/blob/0dc96be00d3b1813c53aacf7a9857b6da2391725/apps/faucet/src/store/index.ts#L2)
[Example from SideBar component](https://github.com/webb-tools/webb-dapp/blob/bb5711c5efd1a6949ee05690cc8983a8659c61ca/libs/webb-ui-components/src/components/SideBar/SideBar.tsx#L38-L43)
