### ISSUE TITLE
[TASK] Implement `Loading Pill`component for tx status

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1456]
## Description
Implement `loading pill` component within the top navigation to signify ongoing transaction(s). The spinner should remain active as long as there are ongoing transactions. When a transaction completes successfully, briefly change the spinner into a success icon, then return it to the normal spinner if there are more ongoing transactions. If it's the last transaction, display the success icon, and once user interacts `Transaction Progressor` component ([link](https://github.com/webb-tools/webb-dapp/issues/1421)), and make it disappear after interaction. 

In case of a failure, change the spinner into a failure icon. Return to loading state with spinner if there are more ongoing transactions. 

### Screenshots
![Screenshot 2023-07-24 at 12 12 12 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/e053dab5-d92a-46f2-917a-b961c03b9e2c)
![Screenshot 2023-07-24 at 12 14 26 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/5443fa8d-8e7a-4c32-a7e3-6abda0952112)

**Comment by AtelyPham** [comment]
Closed on https://github.com/webb-tools/webb-dapp/pull/1489.
