### ISSUE TITLE
[TASK] Update `Shielded Pool List` to display network

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1457]
## Description
Add variant to shielded pool list to display the network of the shielded asset by badging the `chain icon` to the shielded pool avatar & adding network name below the amount. 

This update intends to provide users with a more holistic view of their available shielded balance on networks they are not currently connected to by fetching their shielded balance via spend notes. 

### Screenshots
<img width="1263" alt="Screenshot 2023-07-24 at 2 48 59 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/9e4217e2-ad4b-42bb-af02-98b4abe9bbd6">
<img width="1536" alt="Screenshot 2023-07-24 at 2 55 18 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/2f9be0c9-3c0f-4d74-990f-c8b210b1425c">

**Comment by AtelyPham** [comment]
Closed in #1526.
