### ISSUE TITLE
[TASK] Add Bridge Hubble SideMenuBar

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1467]
Implement the SideMenuBar for Hubble Bridge, similar to Hubble Bridge.

**Example** (from Hubble Stats)
![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/a9e580af-98c2-4c74-a660-a9210b6c33e9)

@monaiuu maybe you can add more context and design for this

Mentioned [here](https://github.com/webb-tools/webb-dapp/pull/1466#issuecomment-1653431342)!

**Comment by monaiuu** [comment]
Yes let me get that to you today. Will share figma files for responsive breakpoints for Hubble Bridge & wrap/unwrap UI.

**Comment by monaiuu** [comment]
## Handoff
Please reference to below for the responsive views for Hubble Bridge. It should behave similarly in the wrap/unwrap UI. I think it might be helpful to add the top nav and side nav responsiveness into storybook for consistency across dapps. (Adding device variants -> `tablet` & `mobile`) 

### Hubble Bridge: [Figma Link](https://www.figma.com/file/wQulr8fTsVqWvFk17QWdhu/%F0%9F%8C%81--Bridge-UI-v2?type=design&node-id=1194%3A218100&mode=dev)
### Design System: [Figma Link](https://www.figma.com/file/wQulr8fTsVqWvFk17QWdhu/%F0%9F%8C%81--Bridge-UI-v2?type=design&node-id=1194%3A218100&mode=dev)

### Screenshots
<img width="1538" alt="Screenshot 2023-07-27 at 4 34 19 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/e1cdfb7d-1507-4aa4-a6da-24d7aaf8196a">
<img width="1975" alt="Screenshot 2023-07-27 at 4 36 50 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/cda094ce-0c60-4393-9b33-e730de117e31">
