### ISSUE TITLE
[TASK] Build Pool Overview Chart component for Hubble Stats

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1487]
@monaiuu I saw the task for building this component is currently missing. Feel free to add more descriptions here!

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/7f2c9b53-289c-4454-bcaf-ca50a72a35e2)

**Comment by vutuanlinh2k2** [comment]
@devpavan04 since you are also working with [chart component](https://github.com/webb-tools/webb-dapp/issues/1301) on the Overview page, I think it's the best if you also do this.

Feel free to assign this to yourself if you find this ok!

**Comment by monaiuu** [comment]
> @devpavan04 since you are also working with [chart component](https://github.com/webb-tools/webb-dapp/issues/1301) on the Overview page, I think it's the best if you also do this.
> 
> Feel free to assign this to yourself if you find this ok!

I believe this component has already been implemented by @devpavan04 on both Overview Page and Pool Details Page; let me know if I am missing any context.
