### ISSUE TITLE
[TASK] Implement functionality to dynamically fetch data for `hubble-stats` charts

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1493]
### Overview
Implement functionality to dynamically fetch and display the data for the following `hubble-stats` charts.

- [ ] Charts in overview [page](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=814-220618&mode=design&t=9YhaSSQVkq6Q1RPB-4) - TVL and Volume 24H

![CleanShot 2023-08-02 at 05 48 01](https://github.com/webb-tools/webb-dapp/assets/53374218/b8f63592-bb63-47ea-a84b-fb9b9a7a2409)

- [ ] Charts in pool [page](https://www.figma.com/file/KWLQWPgzbMMIj0p5dylcgB/%F0%9F%93%88-Shielded-Pool-Stats?type=design&node-id=814-274161&mode=design&t=9YhaSSQVkq6Q1RPB-4) - TVL, Volume and Fees

![CleanShot 2023-08-02 at 05 47 48](https://github.com/webb-tools/webb-dapp/assets/53374218/089321d5-c168-438c-89ac-4b2fd0d902b5)

**Comment by vutuanlinh2k2** [comment]
Currently, there is no effective way to get the data for the charts. There should a way we can get the data for Volume and TVL by date. This problem will be addressed in this 2 issues in `webb/graphql` repo. 
- [TVL](https://github.com/webb-tools/webb-graphql/issues/129)
- [Volume](https://github.com/webb-tools/webb-graphql/issues/131)

The is also a lack of data on Orbit live chains right now, I will run Orbit chains locally to temporarily get the data for the UI.

**Comment by vutuanlinh2k2** [comment]
New requirements: Finish the new design for Volume Chart [here](https://github.com/webb-tools/webb-dapp/issues/1550)

**Comment by vutuanlinh2k2** [comment]
Back-end ready after this [PR](https://github.com/webb-tools/webb-graphql/pull/136) got merged.
