### ISSUE TITLE
[UI] Revise Batched Proposals Table & Details Page Design

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1512]
### Overview

In the most recent [design](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?type=design&node-id=1174%3A150002&mode=design&t=5qm0Q3gPIeYUeo2B-1) implementation of the stats dapp's `Proposals` page, we need to revise the design to accurately display `Proposers` in the `Proposals Table` and `Proposal Detail Page`.

### Problem

- In DKG, while individual proposals have their respective proposers, the proposal batches do not.
- However, in the current design, the proposals table features a column intended to display the proposers for each proposal batch. - This is problematic since the backend can return only the proposers for individual proposals, not for batches.
- Similarly, on the proposal batch details page, we currently display a table of proposers for a specific proposal batch, rather than for individual proposals.

### Screenshots

![CleanShot 2023-08-08 at 05 20 44](https://github.com/webb-tools/webb-dapp/assets/53374218/3e150f45-9aea-4a10-9082-f23b99ed4264)

![CleanShot 2023-08-08 at 05 21 14](https://github.com/webb-tools/webb-dapp/assets/53374218/e646c57d-ed4a-4324-ac60-270c874f9bd0)

**Comment by monaiuu** [comment]
@devpavan04 Proposal batches do not have proposers directly, but is it correct that each proposal would still have proposers within the batches? For example, in batch X composed of 5 AnchorUpdate proposals, each would have its corresponding proposers associated.

**Comment by monaiuu** [comment]
Proposed Update for Proposal Details Page:

- Migrate 'Results' to 2nd container
- Migrate 'Proposer Details' to 2nd container

**Comment by devpavan04** [comment]
@monaiuu @drewstone 

As discussed:

### Batched Proposals Table

- Remove `Proposers` table.

### Proposal Batch Details Page

- Keep two containers - Proposal Batch general data container and Proposals data container (Pagination for all proposals in that batch)
- Move results (votes) to second container as well.

**Comment by monaiuu** [comment]
## Handoff

Please see below for hand-off of the latest proposal pages based on discussion.
Figma Link: https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--Statistics-Page-%5Bhand-off%5D?type=design&node-id=1152%3A113488&mode=dev

### Batched Proposals Table
<img width="881" alt="Screenshot 2023-08-08 at 3 12 03 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/1f2995ee-d3ef-4c81-8c49-c8dc2956f81b">

- Remove `Proposers` column within table


### Proposal Details Page
<img width="677" alt="Screenshot 2023-08-08 at 3 14 45 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/9d654d8a-7659-47e2-8749-86bc238f46a1">

- Migrate `Results` below timeline & proposal details
- Migrate `All Proposers` table to second container below `Results`
- Replace `Link Buttons` with `Utility Buttons` for proposal toggling to provide more visual emphasis for proposals toggling.
- Rearrange black height row with proposals row in first container 

### Proposal Details (side panel)
<img width="681" alt="Screenshot 2023-08-08 at 3 15 37 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/07623087-3990-4d1a-a2b2-cf8ed2c103c4">

- similar components updates are applied (see wireframes)
- add `divider` to separate general batch details & specific proposal details

**Comment by drewstone** [comment]
Closing this as I believe we've shipped all necessary updates to the DKG stats for now. Please reopen if there is a clear task and deliverable remaining.
