### ISSUE TITLE
[BUG] Relayer has not yet relayed the commitment to the destination chain

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1516]
Users frequently encounter an error while attempting to withdraw or transfer funds immediately after depositing. This issue significantly detracts from the overall user experience.

## Expected Behavior
Users should be capable of executing withdrawal or transfer transactions without hindrance.

### Current Behavior
Upon clicking the `Withdraw`/`Transfer` button to execute a transaction, users encounter an error if the note was not relayed in time. This obstacle interrupts the user flow and diminishes their experience.

### Possible Solution

As suggested by @drewstone, implementing a simple heuristic check to monitor the `commitment` might be beneficial. This would necessitate disabling the `Withdraw`/`Transfer` button until the transaction is ready to be executed:

- Retrieve all `(root, last_leaf_index)` for all chains along with their neighbors.
- Evaluate the feasibility of withdrawal by comparing my note’s `leaf_index` with the `last_leaf_index` of the neighboring chain or the chain I'm withdrawing from.

**Comment by drewstone** [comment]
Additionally, we should ensure we are spending the oldest notes first so that at the very least we are in the best position for that question to be Yes.
