### ISSUE TITLE
[BUG] Prevent Inoperable or Non-Interactive UI Elements in Hubble Bridge

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1523]
Within our current dApps, there are instances where an empty card appears upon clicking an input, or the inputs themselves are disabled. Such occurrences render the Hubble Bridge inoperable and unintuitive.

## Expected Behavior
Our goal is to ensure that users can consistently interact with the dApp. If an element is disabled or empty, we need to provide an explanation for its state and guide users on the next steps.

### Current Behavior
At times, when interacting with the dApp, clicking on inputs results in either an empty card or a disabled input, without any apparent cause or explanation.

### Possible Solution
We need to reevaluate our design and implementation strategies to ensure that the dApp remains consistently interactive for users at all times.

**Comment by drewstone** [comment]
I suggest clearer tasks. This seems open ended to the point of not leaving a clear path for a deliverable. Maybe its in your head but we need tasks that _everyone_ can take on without much cognitive overhead. Closing until we can enumerate individual instances of this issue to be solved.
