### ISSUE TITLE
[FEAT] Adding EDCSA Claim Page to the Current Hubble Bridge

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1527]
**Is your feature request related to a problem? Please describe.**
Our project necessitates the integration of an ECDSA claim page, which will enable users to claim future airdrops.

This includes:

- [ ] UI implementation
- [ ] Development of logic for claiming airdrops on EVM, including connectivity to EVM wallet
- [ ] Development of logic for claiming airdrops on Substrate, including connectivity to Substrate Wallet

### Screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/d736d967-c605-4f71-a5e1-4a0d75bc7203)

**Comment by AtelyPham** [comment]
From @drewstone.

> We will want both ECDSA and Substrate claim, it’ll function similarly to Faucet UI.
> For example it should identify if the user is claiming with substrate address or ECDSA and send the right calls.

**Comment by drewstone** [comment]
The message that needs to be signed roughly: https://github.com/webb-tools/tangle/blob/main/pallets/claims/src/lib.rs#L110-L112

The function to be hit: https://github.com/webb-tools/tangle/blob/main/pallets/claims/src/lib.rs#L355-L358

**Comment by AtelyPham** [comment]
The flow is straightfoward
- Sign the concat(message, account_to_claim_to)
- Submit the tx w/ this signature (it will support submitting an unsigned tx actually)

**Comment by monaiuu** [comment]
Note: The claim should be under Tangle rather than Webb for domain/side nav navigation. Will be updating the wireframes.
