### ISSUE TITLE
[CHECKLIST] Implement End-to-End Flows for Account Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1528]
## Overview
The Account Dashboard is a central hub for managing shielded accounts, offering features like account control, shielded balances management, transaction history, and more. By providing a centralized interface to give users a quick overview of their account, it simplifies the user experience and enhances efficiency. For the specific UI components needed to build this interface, please refer to the checklist (link). 

### Goals
- **Unified Experience:** Offer users a cohesive and streamlined experience, granting them immediate access to vital information such as account balance, recent transactions, profile details, etc. 
- **Encourage Aggregation:** Encourage users to aggregate shielded assets, thereby contributing to the growth of the protocol.
- **Compliance and Reporting**: Dashboards can assist in compliance with regulatory requirements by providing easy access to necessary reports and documentation.

### Checklist
- [x] #1529
- [x] #1530
- [x] #1532
- [x] #1535
- [x] #1536
- [x] #1537
- [x] https://github.com/webb-tools/webb-dapp/issues/1809
- [x] https://github.com/webb-tools/webb-dapp/issues/1820
- [x] #1534
- [x] #1540

**Comment by vutuanlinh2k2** [comment]
Remove #1533 from this list for now since everything is on still on testnet and currently there is no way to convert Webb tokens to fiat currency
