### ISSUE TITLE
[TASK] Integrate Wallet Connection & Account Creation Flow with Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1529]
## Description
This task involves integrating the account creation flow with the dashboard to ensure a seamless user experience. The account dashboard will be accessible only to users who have connected their wallet and created an account. When a user selects the 'account' from side nav, they will be prompted to connect their wallet. If they haven't created an account yet, they will be guided through the account creation process. 

Note: 
- The wallet connection and note account creation flow on the bridge dAPP remains consistent. This task is required for accessing dashboard directly via side nav or link. 
- Should user disconnect wallet whilst in dashboard, we can either redirect to ecosystem page or bridge dapp. 

### Screenshot
<img width="1733" alt="Screenshot 2023-08-11 at 5 29 25 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a540ad45-6515-4e23-a1e1-27299bbb70c5">

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1811.
