### ISSUE TITLE
[TASK] Synchronize Transactions and Notes Display with Hubble Bridge

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1530]
## Description
The goal of this task is to ensure that the account dashboard accurately reflects the user's successful transactions, total shielded balance, available spend notes, and transaction history table, by synchronizing this data with the Hubble Bridge. This will provide users with a consistent and up-to-date view of their account status.

### Requirements: 
- Data Integration: Establish connection between the account dashboard and Hubble Bridge to fetch and display the user's successful transactions, including `deposits`, `transfers`, `withdrawals`, and `received transfers`.
- Total Shielded Balance: Accurately calculate and display the user's total shielded balance, reflecting all successful transactions.
- Notes Table: Populate the notes table with detailed information about each note.
- Transaction History Table: Display a comprehensive history of the user's successful transactions, including transaction type, amount, date, and links to relevant block explorers etc.

### Screenshot
<img width="1576" alt="Screenshot 2023-08-14 at 2 37 25 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/1b062ce0-129e-47ef-97a2-1cd259e3062b">

**Comment by vutuanlinh2k2** [comment]
Closed in this [PR](https://github.com/webb-tools/webb-dapp/pull/1837)
