### ISSUE TITLE
[TASK] Migrate Notes Tables and Management Features to Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1532]
## Description
The goal of this task is to centralize the management of spend notes by migrating the existing notes tables and associated functionalities to the account dashboard. This migration aims to enhance user experience by providing a unified location for managing spend notes, including uploading, downloading, and deleting them.

### Details

- Migrate Notes Tables: Move the existing notes tables to the account dashboard, ensuring that all current features and functionalities are retained.

- Integrate Management Features: Implement the ability to upload, download, and delete spend notes directly from the dashboard.

- Quick Transact Feature: Enable users to quickly initiate transactions from specific spend notes. Selecting a spend note from the dashboard should redirect users to the Hubble Bridge with preselected parameters based on the chosen note.

### Screenshot
![Screenshot 2023-08-14 at 10 43 52 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/590069d9-2cb5-43dc-afdf-b411c08a3631)

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1811.
