### ISSUE TITLE
[FEAT] Display Fiat Equivalence for Total Account Balance on Account Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1533]
## Description
The objective of this feature is to provide users with a clear understanding of their total shielded balance by displaying its equivalent value in fiat currency. This involves aggregating the user's available spend notes in their account and calculating the approximate fiat equivalence based on the current market rates of the underlying token composition.

### Screenshot
![Screenshot 2023-08-14 at 11 12 57 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/69a6ad15-d918-4a4a-a9f0-ab4a2ba63977)

### Notes
I imagine we should add some tooltip or info to inform users the nature of the approximate balance here to avoid any legal implications, especially during extreme market conditions. @drewstone @thomivy

**Comment by thomivy** [comment]
@monaiuu 
Conversion Rate Disclaimer:
This rate is sourced from [SOURCE] and may not reflect real-time market prices.
Cryptocurrency prices are highly volatile and can change rapidly.
Displayed rates are for informational purposes only and may not include transaction or network fees.
Always verify rates and conduct your own research before making financial decisions.

**Comment by monaiuu** [comment]
For this task, in testnet phase we may want to display native tokens for aggregated shielded balance. May require evaluation on which denomination we want to display (i.e., webbETH? tTNT?). If we use tTNT, it would be consistent with Hubble Stats. 

cc @drewstone

**Comment by vutuanlinh2k2** [comment]
@monaiuu @drewstone We should use webbtTNT because that's we are using on Hubble Stats!
