### ISSUE TITLE
[FEAT] Enable Hide Account Data Feature

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1534]
## Description
Implement a privacy feature within the account dashboard that enables users to quickly and easily hide sensitive account information. This feature is particularly useful for scenarios where a user may be accessing their account in a public or shared space and wants to ensure that personal and financial details are not visible to others around them. 

### Screenshot
![Screenshot 2023-08-14 at 11 22 51 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/4a9904d2-6adf-4f23-9d3e-2818724b336a)

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1811.
