### ISSUE TITLE
[TASK] Implement Core Account Control Features (Receive, Deposit, Transfer, Withdraw)

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1535]
## Description
The goal of this task is to implement essential account control functionalities within the account dashboard, specifically within the account card component. These functionalities include the ability to receive, deposit, transfer, and withdraw funds, providing users with a centralized and streamlined experience for managing their shielded assets.

### Details

1. Receive:
**Action:** When the user taps on "Receive," a modal will appear, providing the user's note account public key, allowing them to copy and share it for receiving internal transfers.
**Future Considerations:** In future releases, we may enhance this functionality by enabling users to share their public key directly via private messaging applications like Signal.

2. Deposit:
**Action:** When the user taps on "Deposit," they will be redirected to the deposit tab on Hubble Bridge.

3. Transfer:
**Action:** When the user taps on "Transfer," they will be redirected to the transfer tab on Hubble Bridge.

4. Withdraw:
**Action:** When the user taps on "Withdraw," they will be redirected to the withdraw tab on Hubble Bridge.

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1811.
