### ISSUE TITLE
[FEAT] Retrieve Data for Transaction History Implementation

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1536]
## Description
Fetch and display the necessary data to provide users with a comprehensive view of their transaction history. This includes deposit, transfer, withdrawal, and received transfers for each user's note account across all networks. In addition, we need to display the input and output notes used in each transaction and redirect user to view the transaction on the respective block explorer.

### Screenshot
<img width="1063" alt="Screenshot 2023-08-14 at 2 44 21 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/52b6912e-ad19-46af-9c6b-15c06740a050">
<img width="1196" alt="Screenshot 2023-08-14 at 2 45 07 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/6a0348f0-5699-4375-b5d7-6006e41ac86f">

**Comment by drewstone** [comment]
@vutuanlinh2k2 @AtelyPham please update who is working on this task if it has changed.

**Comment by vutuanlinh2k2** [comment]
@drewstone I'm working on the frontend and Tin is working on the backend of this!

**Comment by AtelyPham** [comment]
Created a new issue for the backend data, https://github.com/webb-tools/webb-dapp/issues/1820.

**Comment by vutuanlinh2k2** [comment]
Closed in this [PR](https://github.com/webb-tools/webb-dapp/pull/1837)
