### ISSUE TITLE
[FEAT] Enable Transaction History Download Functionality

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1537]
## Description
This task aims to enable users to download their complete transaction history for various essential purposes, including offline access & record-keeping, compliance adherence, and accurate tax reporting. The downloadable file, preferably in CSV format, must encompass all pertinent details to ensure transparency and usability. This includes:

- Transaction Type: Such as deposit, withdrawal, transfer, or received transfer.
- Amount: The value of the cryptocurrency involved in the transaction.
- Fees: Any transaction fees incurred.
- Transaction ID (Tx ID): A unique identifier for the transaction.
- Relevant Addresses: Including the 'From' and 'To' addresses.
- Block Explorer Link: A direct link to view the transaction on the respective block explorer.
- Date/Time: Timestamp of the transaction.
- Additional Details: Any other relevant information that provides a comprehensive view of the transaction.

### Screenshot
<img width="1134" alt="Screenshot 2023-08-14 at 12 09 30 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a79e789d-ff7a-480f-8a73-015b74a0b74f">

**Comment by vutuanlinh2k2** [comment]
Closed in this [PR](https://github.com/webb-tools/webb-dapp/pull/1837)
