### ISSUE TITLE
[TASK] Update Hubble Stats to display native tokens(tTNT) instead fiat

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1564]
## Description

To improve the accuracy of balance displays on the testnet, switch from showing balances in fiat to native tokens (tTNT). This change will be applicable to general statistics and pool details pages.

### Screenshots
**Overview Page**
<img width="902" alt="Screenshot 2023-08-24 at 4 02 46 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/9e6c8cbe-6071-4d1c-b68e-3788afd95e2a">

### Notes
The switch back to fiat for the mainnet may be required on the introduction of aggregation of real value tokens.

**Comment by vutuanlinh2k2** [comment]
@monaiuu  I'm going to change the Chips, Overview Charts and Key Metric tables first, for other components I will update when I'm integrating back-end to those!
