### ISSUE TITLE
[TASK] Update pool details page (charts & tables)

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1573]
## Description
Based on design review, the following updates are proposed:

**Update Charts Components:**
- Remove the display for "Volume" from the charts.
- Create split views to separately display "Pool Data" and "Wrapping Data."

  - For "Pool Data," show historical data for TVL (Total Value Locked) and Relayer Earnings.

  - For "Wrapping Data," show historical data for TWL (Total Wrapped Locked) and Wrapping Fees.

**Update Edge Tables:**
- In the first edge table, update to display only TVL & Relayer Earnings across all networks.
- In the second edge table, update to display only TWL & Wrapping Fees across all networks.

For the contract address display in Token Overview container, I am proposing to display vAnchor contract address, as it is crucial for users interested in the Total Value Locked (TVL) of the pool, update with `file-copy` icon to enable users to copy the contract address. 

### Note
Amount should be displayed in tTNT rather than fiat similar to the overview page. 

### Screenshots
![Image](https://user-images.githubusercontent.com/109539270/264098832-360e404d-f2ae-40b8-93da-6b85cce657d4.png)
![Image](https://user-images.githubusercontent.com/109539270/264100770-aa8f903b-fac9-4f55-92d3-c6ba26ffa97a.png)

**Comment by vutuanlinh2k2** [comment]
this task is covered in #1583
