### ISSUE TITLE
Dynamically Generate a Block Explorer in Polkadot UI Based on the Selected RPC for DKG Stats

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1575]
The current setup is satisfactory for the time being. However, we should aim for a dynamic configuration based on the currently selected RPC. Please refer to the following links for more information:

- [populateBlockExplorer](https://github.com/webb-tools/webb-dapp/blob/6bad94a740ec2dcd63b139e4a33e878610609f90/libs/dapp-config/src/chains/substrate/index.tsx#L5-L14) in the Polkadot UI.
- [How to calculate the URL for a given block hash in the Polkadot UI](https://github.com/webb-tools/webb-dapp/blob/edb92734e13134fd9ebe1a678aa4b5f6c5b8caf7/libs/api-provider-environment/src/transaction/useTransactionQueue.tsx#L44-L47).

_Originally posted by @AtelyPham in https://github.com/webb-tools/webb-dapp/pull/1566#discussion_r1309970118_

**Comment by drewstone** [comment]
I don't understand, is this done?

**Comment by AtelyPham** [comment]
The Polkadot explorer URL is hard-coded in the constants file. The issue involves making it more dynamic, based on the current active RPC to Polkadot.
