### ISSUE TITLE
[TASK] TVL and TWL change rate calculations across components on Hubble Stats

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1597]
Need an efficient way to get the tvl and twl in 24 hours about in order to calculate the change rate on the front-end. Back-end might need to be updated.

Components that have tvl change rate includes:

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/addf1b64-0a5e-419f-8478-fe526a8626fa)

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/1fa8b05b-c4d5-4e06-9c7e-a2d6fcb0ac39)

**Comment by drewstone** [comment]
If there are challenges / open questions here please describe them so we can assist you.

**Comment by drewstone** [comment]
If getting the day data is challenging perhaps we're not collecting it as best we can. Please also describe it thoroughly so we can add to the README.

**Comment by vutuanlinh2k2** [comment]
Current approach: mentioned and resolved [here](https://github.com/webb-tools/webb-graphql/pull/158)
