### ISSUE TITLE
[TASK] Migrate necessary URLs to tangle.tools 

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1606]
- [x] Tangle stats
- [x] Tangle homepage
- [ ] Tangle leaderboard
- [x] Tangle faucet
- [x] Tangle EVM Explorer
- [x] ~GraphQL backend endpoints~
- [x] Validator / RPC node endpoints

**Comment by shekohex** [comment]
@drewstone where is Tangle leaderboard original url? is it a dApp? deployed anywhere?

**Comment by drewstone** [comment]
It hasn't been deployed yet, CC @AtelyPham @vutuanlinh2k2 to use a Tangle domain once that is up.

**Comment by drewstone** [comment]
@shekohex can you help fix the stats.tangle.tools migration? And provide the method if possible.

**Comment by shekohex** [comment]
> @shekohex can you help fix the stats.tangle.tools migration? And provide the method if possible.

will work with @AtelyPham to fix that today.

**Comment by shekohex** [comment]
This should be done by now.
