### ISSUE TITLE
[BUG] Scroll bar position & behavior on Hubble Bridge

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1615]
## Description

Ensure that the scroll bar on Hubble Bridge appears at the right edge of the screen when viewed on large displays. Currently, the scroll bar is incorrectly positioned in the middle of the screen. Update the layout to correct this issue. Additionally, the scroll bar should only appear when the user is actively scrolling, not in the default state. ([example](https://stargate.finance/farm))

### Screen Recording
https://user-images.githubusercontent.com/109539270/267635791-b3157107-ab73-4157-8809-371969aae6b0.mp4

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1610, please review it again at [link](https://develop-bridge.webb.tools). @monaiuu
