### ISSUE TITLE
[UI] Add clear link to Polkadot Apps to Tangle Site Nav

### ISSUE THREAD

**Issue by thomivy** [webb-tools/webb-dapp#1618]
**Is your UI update related to a problem? Please describe.**
In order to get to Polkadot Apps for Tangle, you have to go to Stats Dapp and then find "Tangle Standalone" in the dropdown menu in the nav. 
1. This isn't clear that this leads to Polkadot Apps- link name change needed.
3. Apps needs to be accessible from the Tangle site itself.
4. While Webb Protocol is deployed to Tangle, a convo with Drew on Sept 12 leads me to think we will reduce the primacy of Stats Dapp on Tangle Site- it's unclear why the main CTA on Tangle would lead to the DKG system regardless.

**Describe the solution you'd like (include image or link to prototype)**
1. Add a link or dropdown to Tangle site main nav that explicitly leads to Polkadot Apps. (Maybe remove or reprioritizie link to DKG Stats) 
2. REtitle the link to apps on Stats Dapp to "Tangle Network on Polkadot Apps" or similar.

**Comment by drewstone** [comment]
I believe this has been solved by our migration to webflow.
