### ISSUE TITLE
[CHECKLIST] QA - Hubble Bridge, Hubble Stats and DKG Stats dApp - Sept 13, 2023

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1620]
### Overview

- [x] Hubble Bridge - #1619 
- [x] DKG Stats - #1617 
- [x] Hubble Stats - #1624

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1787.
