### ISSUE TITLE
[BUG]  Search fails on Docs. "Search Index Fails to Load" the relevant file is not built.

### ISSUE THREAD

**Issue by thomivy** [webb-tools/webb-dapp#1623]
**Summary:**
The Nextra documentation site is specifically failing to build the file nextra-data-en-US.json and returning the error "Failed to load search index.”, resulting in the users inability to search the docs. **The local production runs successfully, suggesting the issue may lie with the Netlify environment.** Prior, our search broke, but was resolved by Dustin. It's not clear yet if this is a new bug or the same one.

**Recommendation:**
Check the Netlify environment directly. Ensure that all necessary environment variables are correctly set in Netlify, check the build logs on Netlify for more specific error messages. 

**Detailed Findings and Checks**

1. **Build Command:** The build command in netlify.toml is correctly set to next build and the publish directory is correctly set to .next.

2. **Nextra Configuration:** The Nextra configuration in next.config.js is correctly set. The unstable_flexsearch option is set to true, which enables search indexing. This functionality is marked as “unstable” which could be related to the issues. 

3. **Node.js Version:** The Node.js version specified in package.json under the engines field is 16.x, which should be compatible with Netlify.

4. **File and Directory Names:** All file and directory names in the provided codebase are in lowercase, which is the recommended practice for compatibility with Netlify's case-sensitive build system.

5. **Environment Variables:** Ensure that all necessary environment variables are correctly set in Netlify. This includes any API keys, database URLs, or other sensitive information that your application needs to function.

6. **Netlify Build Logs:** If the problem persists, check the build logs on Netlify for more specific error messages. This could help pinpoint the exact issue causing the build to fail.

**Conclusion:**
no issues were found related to the build command, Nextra configuration, Node.js version, or file and directory names. The issue might be on the Netlify environment side. I recommended to check the Netlify environment and build logs for more specific error messages.

## Expected Behavior
The search functionality should operate normally when the user types.

### Screenshot 

<img width="1482" alt="Screenshot 2023-09-13 at 1 34 14 PM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/61ff4c1a-f3c3-4f4d-81f8-5f18fb919d8c">

### Log output
`Failed to load resource: the server responded with a status of 404 ()`

**Comment by AtelyPham** [comment]
Related https://github.com/shuding/nextra/issues/2300.
