### ISSUE TITLE
[FEAT] Default Selection of Chains with Balance in Withdrawal & Transfer Flows

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1653]
**Is your feature request related to a problem? Please describe.**

At present, during the withdrawal and transfer processes, we auto-select a blockchain for users to execute transactions. The chain selection algorithm functions as follows:

If the user is already connected to a chain, this becomes the default chain.
In the absence of a connected chain, the default chain is set to the first chain listed in the chains configuration.
To enhance user experience and streamline transaction flow, we propose to automate the selection of chains where users already have a balance. This will eliminate the need for users to manually search for available chains to execute their transactions.

**Describe the solution you'd like**

In the [useDefaultChainAndPool](https://github.com/webb-tools/webb-dapp/blob/develop/apps/bridge-dapp/src/hooks/useDefaultChainAndPool.ts) hook, we should prioritize the chains where users already have a balance for auto-selection during the transfer or withdraw flows.

**Comment by monaiuu** [comment]
Here are some thoughts:

- I am concerned if the dapp automatically switches chains, it could confuse the user, and auto-switching chains may take some decision-making power away from the user.

- Curious what if the user has balances on multiple chains, how would we prioritize the auto selection.

**Comment by AtelyPham** [comment]
Indeed, the dApp does not automatically **_switch_** chains. It should be more intelligent in **_selecting_** a default chain during the withdrawal or transfer process.

For example, if I'm a user and I have my shielded balance on Polygon, the dApp should automatically select Polygon as the default when I choose to withdraw or transfer. This should occur instead of selecting other chains where I carry no balances. I believe this improvement would enhance user experience during withdrawals and transfers.

Regarding your second question, it's indeed a good one. This task should be resolved promptly, but it's quite challenging to make sound decisions when prioritizing chains that have balances.

Here are my current thoughts:

- If users have shielded balances, we should check the shielded balances and automatically select a chain that has the same bridge deployment as the active chain. The motivation for this is that, for instance, if I successfully deposited on Tangle to Athena (and I was connecting to Tangle as I just deposited), then I want to withdraw or transfer. It would be beneficial if the dApp could automatically select Athena for me when I change to withdraw or transfer by checking my balances, and finding the chain that has the same bridge deployment as my connected chain.
- When users don't have any shielded balances, the dApp should automatically select the active chain.
- When users don't connect their wallet, the dApp could select any supported chain by default.

**Comment by AtelyPham** [comment]
Please let me know if anything is unclear to you, @monaiuu.

Also, @drewstone, I'd appreciate your review on this. Am I overthinking? 🤔

**Comment by drewstone** [comment]
Doesn’t MetaMask / other wallets prompt the user when a chain is being
switched? I don’t think it takes mental steps away from a user. Users
aren’t dumb. There’s literally 100 chains, 10 different EVMs at this point,
and many more coming. Everyone that will use this app will be VERY
knowledgeable compared to the kind of person I think you’re worried about.

**Comment by drewstone** [comment]
I think it’s more confusing to have chain inputs showing a chain I’m not
connected to (on the source side). I’m saying this as myself, a user of
many apps and chains.

**Comment by monaiuu** [comment]
I think if we display shielded balances in non-connected networks during transfer and withdrawal phases should sufficiently inform users of their assets across chains, while still allowing them the autonomy to choose which network to connect to without automatic prompts.

### Screenshot
<img width="915" alt="Screenshot 2023-09-25 at 4 45 54 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/e921318e-3bca-456b-88be-e9de816b6a1e">

**Comment by drewstone** [comment]
The above doesn't fully seem like the best UX we can offer. I think after more thinking the best we can offer combines a bit of the following:
- As a user, I should have the ability to select any chain / asset where I have shielded balance without prompting a network switch in my wallet.
- As a user, I should only be prompted to switch a network when I'm at the point of submitting a transaction.
