### ISSUE TITLE
[TASK] Show chain name in proposal detail page

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1656]
### Overview

Currently, the `stats-dapp` proposal detail page displays proposal metadata. Within this block, we show `chainID` and `chainType`, which only display numbers, making it not very informative for the user. Instead, we should display the actual chain name, for example Ethereum.

![CleanShot 2023-09-20 at 09 36 14](https://github.com/webb-tools/webb-dapp/assets/53374218/d403aaad-dc37-4a5e-b9a1-b091e15cbdc0)

**Comment by AtelyPham** [comment]
One question here: do all proposals have chainType and chainID properties?

**Comment by drewstone** [comment]
Yes they do @AtelyPham @devpavan04
