### ISSUE TITLE
[BUG] Hubble Bridge Dropdown

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1668]
### Overview

Is `Network Settings` the correct heading here?
`Testnet` - https://polkadot.js.org/apps/?rpc=wss://rpc-archive.tangle.tools#/explorer
`Development` - Link is broken

![CleanShot 2023-09-21 at 09 37 19](https://github.com/webb-tools/webb-dapp/assets/53374218/bf1c0cfd-420e-49e1-a3b5-bca423039541)

**Comment by monaiuu** [comment]
@devpavan04 Let's remove theme switching, network settings, and development from the menu list. We can include substrate portal to the list for Tangle Network. Below is a screenshot to reference from.

<img width="805" alt="Screenshot 2023-09-26 at 12 06 02 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/329bbcb4-fb38-4987-bfd4-afc3c54876f6">
