### ISSUE TITLE
[TASK] Add top level stats to tangle-app EVM validator list page

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1678]
# Overview
Similar to Polkadot Apps add the top statistics to the validator list page.

![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/d1251aa4-11cd-4da0-850f-840b27044da0)

**Comment by monaiuu** [comment]
## Handoff
Please reference below for implementing a staking overview section to the Tangle EVM UI, displaying key statistics and metrics related to staking similar to Polkadot Apps. These data should be accessible to users regardless if wallet connection has been enabled. 

Note: The key metrics component has been implemented for Hubble Stats. Please reuse the same component to ensure consistency. 

### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Governance?type=design&node-id=1303%3A65337&mode=dev)

### Screenshot
<img width="800" alt="Screenshot 2023-10-10 at 10 01 43 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/73c87007-746d-4b5d-a5f2-e727e7feebde">
