### ISSUE TITLE
[TASK] Add setup nominator button and modal

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1679]
# Overview
Setup nominator is a 2 step flow. First you need to create and setup your stash account. Then you select the validators you want to nominate. There is likely a _max_ # of validators to nominate but you select all the validators you want to nominate up front. The designs below should be exactly how we implement our UI roughly. Use components that seem to match or create new components as needed.

### Step 0
Display the button at the top of the nomination page. We just need the nominator & stash button, nothing else to start.
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/bbb577ce-842c-4ffd-bd0c-c0d0ef5d63ce)

### Step 1
Clicking on the nominator or stash button should present the following modals. Note, these modals are the same just have different label text.

**Clicking from Nominator button**
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/a4e08f42-a18b-44e3-8aa1-11d7aaa50ec0)

**Clicking from Stash button**
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/89420e81-afc7-4e9d-afbc-a3ad43af6a6b)

### Step 2
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/944aa63f-55f5-401f-9e71-d2577b591efb)

### Authorize and submit
![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/aefea73f-9f14-4be5-ae9d-98aa38b46b79)

**Comment by monaiuu** [comment]
Initial wireframes can be referenced below:

<img width="2757" alt="Screenshot 2023-10-02 at 3 00 31 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/9799d1b4-2a10-46df-8e6c-6459ea458223">


### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Governance?type=design&node-id=1274%3A52127&mode=dev)

**Comment by monaiuu** [comment]
@salman01zp on the EVM side, does user need to setup both stash and controller account?

**Comment by drewstone** [comment]
Yes

**Comment by monaiuu** [comment]
Ok, I am assuming the exact same flow for account setup on EVM:
<img width="1563" alt="Screenshot 2023-10-05 at 4 59 52 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/e602a9e8-079d-4cbb-adf9-b30fc9becaa7">

**Comment by monaiuu** [comment]
## Handoff
Implement the delegation/nomination flow allowing users to stake their tokens mirroring a similar flow as PolkadotJS app. Please ensure we have necessary error handling mechanisms to capture and inform the user of any issues during the delegation process. 

### Descriptions:
**Initiate Delegation Flow:**
- Detect and handle the 'Delegate' button click from the user metrics container.
- Ensure this action is only available when a wallet is connected.

**Setup Delegator (Step 1/2):**
- Display the 'Setup Delegator' modal with relevant input fields.
- Implement frontend validation to ensure all required fields are filled out appropriately.
- Payment destination dropdown enables users to select whether or not to increase amount at stake. Specified payment account designation option is tbd. Please consult with the team on whether if this should be implemented. 
- Handle 'Next' button logic to proceed to the next step, should user have insufficient TNT balance, the button should be disabled.
- Learn more button opens up doc site on usage guide of staking UI. 

**Setup Delegator (Step 2/2):**
- Present users with a list of validators they can delegate to.
- Allow users to select their preferred validator via multi-select checkboxes; use should see how many are selected below (i.e., selected: 1/20)
- Implement the 'Stake & Delegate' action to process the delegation request.

**Authorize Transaction:**
- Once the user submits their delegation request, display an 'Authorize Transaction' modal to get user confirmation.
- Showcase the details of the transaction, allowing users to review before proceeding.
- Enable user to view contract details on Tangle Block Explorer.
- Handle the 'Submit' action which will send the transaction to the connected wallet for signing and processing.


Handle Transaction Signing:
- Intercept the wallet's signing request and handle any errors (e.g., incorrect nonce, low gas).
- Display transaction status to the user (e.g., pending, success, failure) in real-time.
- Once the transaction is confirmed on the network, provide a clear feedback message to the user, indicating the success of their delegation via Notification component.
- Update the staking overview and active validators list to reflect the new state after delegation.

### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Governance?type=design&node-id=1318%3A144693&mode=dev)

### Screenshot
<img width="1293" alt="Screenshot 2023-10-11 at 9 10 33 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/7b9d7d04-c6ff-420a-8301-88e2024f13f8">

**Comment by devpavan04** [comment]
Implemented in #1887.
