### ISSUE TITLE
[TASK] Create stashes/nomination list in tangle-app staking page

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1680]
# Overview
This should be done before #1679.

The page for listing your nomination should be separate from the validator list page. It is shown below. It can be titled "Accounts" as it is done in the Apps UI

![Image](https://github.com/webb-tools/webb-dapp/assets/13153687/9ab9126e-55bf-4481-b57a-7d98378714a3)

## Tasks 
- [ ] Create the page as a separate item in the sidebar nav.

**Comment by monaiuu** [comment]
## Handoff
Implement 'Delegation Table' to provide users with an overview of their staking activities and to manage their delegations. This table will display key information about the user's delegated funds, their rewards, and the validators they've chosen, with various action options that should be addressed in this issue.

### Requirements
**Empty States:**
- Empty State: 'Wallet Not Connected': prompt user to connect wallet via CTA.
- Empty State: 'No delegation': when the user hasn't delegated any tokens; prompt user to start delegating via CTA.

**Delegations Table**

- Validator: Display the address or identity info of the validator the user has delegated to. 
- Status: Show the current status of the delegation:
  - Active: The delegated amount is currently staked and potentially earning rewards.

- Waiting: The delegated amount is in the waiting queue and is not yet staked.
  - Amount Delegated/Staked: Display the exact amount of tokens the user has currently delegated to the validator.
  - Pending Rewards: Indicate any unclaimed rewards that the user can claim from their staking. This should update in real-time.
- Auto-Compound Percentage: Show the percentage at which rewards are being automatically compounded. The user should be able to adjust this value if needed.
- Actions: 
  - Add Stake: Allow users to add more tokens to their existing stake. This should open a dialogue or modal where they can specify the amount and confirm the action.
  - Unbond Funds: Provide an option for users to start the unbonding process for a portion or all of their staked tokens. This may have a cooldown or waiting period associated.
  - Remove Stake: Allow users to remove their stake from a validator, potentially after the unbonding period.
  - Change Reward Destination: Let users specify a different account or address where their staking rewards should be sent.
  - Update Validator: If users wish to change their validator preference, provide an option to do so. This may involve choosing a new validator and potentially re-staking or moving their stake.

### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Governance?type=design&node-id=1328%3A21446&mode=design&t=P2GgCxJ81rwIMOIA-1)

### Screenshot
<img width="998" alt="Screenshot 2023-10-11 at 3 17 35 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/8b9effb8-44b6-4976-b31a-b18c689e37a4">
<img width="1233" alt="Screenshot 2023-10-11 at 3 02 05 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/79fab633-f4e2-4f5f-b25e-05f261bb6f88">

**Comment by devpavan04** [comment]
Implemented nomination list table in #1863.
