### ISSUE TITLE
[BUG] Receiving amount input on withdraw is configurable when it should be disabled.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1690]
## Expected Behavior

The receiving amount input should be disabled and only show the amount the user will receive (before/after refund). It shouldn't be configurable as it is now.

### Current Behavior

It is configurable and a bit odd as the state is updatable in 2 places. It doesn't adhere to the design.

### Possible Solution

Implement according to the design in Figma.

### Screenshot 

<img width="691" alt="image" src="https://github.com/webb-tools/webb-dapp/assets/13153687/6412ac1a-a67d-4ae6-90dd-f9a4e0bcbc75">

**Comment by vutuanlinh2k2** [comment]
This issue has been covered [here](https://github.com/webb-tools/webb-dapp/issues/1699)
