### ISSUE TITLE
[TASK] Add Relayer Info to Fees Component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1697]
## Description
To improve the visibility of relayer information for each transaction, proposing to incorporate the relayer info within the existing Fees Component (expanded state) of the Hubble Bridge interface. User should be able to view details of relayer via opening the hyperlink icon. 

Note: this update will be reflected in the bridge card & confirmation card to display relayer used below relayer fees. 

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/47daf65e-3062-4715-b6b9-f0c0578c32ca)

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1771.
