### ISSUE TITLE
[BUG] Hubble stats URL resolves to bad gateway

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1698]
## Description

When visiting `hubble-stats.webb.tools` from:

<img width="396" alt="Screenshot 2023-09-26 at 7 31 24 PM" src="https://github.com/webb-tools/webb-dapp/assets/29983536/f9534da8-0dcc-428c-8913-e9c31b43e724">

**Results in:**

<img width="1236" alt="Screenshot 2023-09-26 at 7 28 42 PM" src="https://github.com/webb-tools/webb-dapp/assets/29983536/0f20ed3f-697c-43c0-8989-24e32eaf7cbc">

---

❤️ Webb ❤️

**Comment by monaiuu** [comment]
@vutuanlinh2k2 it seems like https://hubble-stats.webb.tools/ is experiencing intermittent 502 Bad Gateway errors. I attempted to open the link in multiple attempts, and sometimes the link is fine other times I get an error as well (see below). 

### Screenshot
<img width="1084" alt="Screenshot 2023-09-26 at 7 42 36 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/85b408e0-0bca-476d-b023-e86f2280309c">

**Comment by vutuanlinh2k2** [comment]
cc @AtelyPham

**Comment by AtelyPham** [comment]
Related https://github.com/webb-tools/webb-dapp/issues/1669.

**Comment by vutuanlinh2k2** [comment]
Closed as this was fixed with #1669
