### ISSUE TITLE
[CHECKLIST] Enhancing Faucet Integration within dApp Ecosystem

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1702]
## Overview
The objective of this checklist is to refine the integration of the Hubble Faucet within our dApp ecosystem to ensure a seamless and consistent user experience across all platforms. This will be achieved through the addition of a side navigation to the Faucet, ensuring uniformity with other dApps like bridge, stats, wrapper, etc., and the introduction of a dark mode to the Faucet UI to align with the theme options available in other dApps. Currently, all our dApps support both light and dark modes, and transitioning from a dark mode in other dApps to a light mode in Faucet creates a disjointed user experience. 

### Checklist
This checklist is aimed at adding a dark theme option to the Faucet UI to ensure theme consistency across all dApps within our ecosystem. The following sub-task is identified to accomplish this:
- [x] #1704
- [x] #1703
- [x] #1705
- [x] #1706
- [x] #1707
- [x] #1769

### Checklist
The goal of this chceklist is to introduce a side navigation bar to the Hubble Faucet, in both light and dark modes, to maintain consistency with the navigation experience in other dApps (bridge, stats, wrapper, etc.). The following sub-tasks are identified to accomplish this:

- [x] #1708
- [ ] #1770
- [ ] #1775 
- [ ] #1783

### Screenshots
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/73e01214-fe06-4577-a07a-9b2415c258d2)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/4ad1109d-466d-4950-8777-ed050a1eac16)

**Comment by drewstone** [comment]
Awesome looks great @monaiuu
