### ISSUE TITLE
[TASK] Dark Theme Input Field, Texts, and Footer Updates

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1706]
## Description
To ensure a cohesive user interface for the dark theme implementation, update the input, selector, texts, and footer components in accordance with Figma file for dark theme display.

### Specifications:
**Input and Selector Components:**
- Update the background-fill of all input and selector components to Monochrome/160.
- Ensure that the text and icon colors within these components are updated to match the dark theme color palette.

**Footer Component:**
- Update footer to use dark theme component

**Text Updates:**
- Update all text colors provided in the Figma file for dark theme display.

### Screenshot
<img width="1093" alt="Screenshot 2023-09-27 at 1 53 45 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/1c50e515-ffbf-4041-bcd8-d9fe39304d1a">

**Comment by vutuanlinh2k2** [comment]
Forget to mention to close this issue in this [PR](https://github.com/webb-tools/webb-dapp/pull/1778)
