### ISSUE TITLE
[BUG] Missing & Incorrect Note Account Render

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1711]
## Description
Issue: note account is not being rendered despite having a note account associated with wallets. In addition, when I select `switch wallet` from account component, my wallet is switched but the previous note account public key is being rendered with the new wallet. Refer to the attached screenshots for reference.

### Screenshots
In below image: my note account public key is not being displayed, despite I have a note account (as seen in 3rd pic)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/85488eb4-8f8f-4a4f-aae0-b43c3da62a47)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/0da2a531-b7eb-45bf-b2ea-c06d8df561df)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/f1e7ca48-8bc8-44cd-96ff-5c180e689234)
In below image, a new wallet has been connected, but the previous note account is being displayed. See the public key & wallet address display, and compare with above image.  
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/863e19a8-56a1-4a8e-a58f-13007552be6e)

**Comment by AtelyPham** [comment]
Related to https://github.com/webb-tools/webb-dapp/issues/1658, https://github.com/webb-tools/webb-dapp/issues/1692.
