### ISSUE TITLE
[BUG] Faucet twitter login error

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1719]
## Description

Cannot login with twitter with the latest [faucet](https://faucet.tangle.tools/) deployment. 

### Screenshot

![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/2d132da0-01b6-494f-bb5d-008d44a50ba0)

**Comment by AtelyPham** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/1724.
