### ISSUE TITLE
[TASK] Update Balance Display on Transaction Inputs on Hubble Bridge

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1727]
## Description
Currently, the balance display on Hubble Bridge is inconsistent from design. Updates are required for balance display on transaction input component across deposit, transfer, and withdrawal flows on Hubble Bridge to show shielded balance from user's available shielded balance (fetched from spend notes) instead of wallet balance in certain touchpoints.

### Flows
**Deposit Flow:**
- Replace wallet balance with shielded balance in `destination transaction input`; fetch shielded balance from user's available spend notes (e.g., 1.00webbETH on Polygon Mumbai).
- Display shielded balance for reference only (disabled); as destination amount input should be disabled.
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/c97946bf-90ed-4685-a3f1-3b0d0a64a8f7)

**Transfer Flow:**
- Replace wallet balance with shielded balance in `source transaction input`; fetch shielded balance from user's available spend notes (e.g., 1.45webbETH on Polygon Mumbai).
- Enable input of entire shielded balance amount on selection, akin to wallet amount button functionality in deposit flow.

![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/24db23b6-aeaa-4642-9bf7-6d14f6df149e)

**Withdrawal Flow:**
- Replace wallet balance with shielded balance in `source transaction input`, fetched from user's available spend notes (e.g., 1.45webbETH on Polygon Mumbai).
- Disable in fixed amount; enable only for custom amount input.
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/b9f1783e-fb76-48f3-9bdd-670fb895ba27)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/5866890c-3d05-4015-8aad-d016a38e759b)

**Comment by AtelyPham** [comment]
Please consider adding tooltips to the balance buttons when they're enabled. These could potentially include external links to our documentation, explaining the concepts of both the 'shielded balance' and 'wallet balance'. cc @monaiuu.
