### ISSUE TITLE
[UI] Enhance 'Add Token to Wallet' Process in the Faucet

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1736]
**Is your UI update related to a problem? Please describe.**

Currently, after successful fund requests on the EVM via the faucet, users are presented with an `Add token to Metamask` button. Upon clicking the button, the added token goes into Metamask. However, if users open their Metamask wallet, they may not see their balance because the active chain on Metamask does not match the chain of the requested fund.

**Describe the solution you'd like (include image or link to prototype)**

To alleviate this issue, the faucet should first prompt users to switch to (or add) the chain from which the funds were requested before adding the new token. This way, users should be able to see their requested balance.

We could provide a series of steps or tasks in the subsequent modal for users to follow to view their balance in Metamask. For instance:

1. Connect to your web3 wallet.
2. Switch to or add the `Tangle` chain to your wallet.
3. Add the `webbtTNT` token to your wallet.

![Modal Dialog](https://github.com/webb-tools/webb-dapp/assets/60747384/7c945f0a-eb04-4691-8cff-c723cfd08e84)

**Technical considerations**

While this solution would necessitate checks for wallet connection, among other wallet-related elements, it's worth noting that the `Add token to Wallet` function is only compatible with EVM wallets. Therefore, we might consider using [wagmi](https://wagmi.sh/) to streamline this process.

**Comment by monaiuu** [comment]
After user has connected to the correct MetaMask wallet account, and selects 'Switch to Tangle Testnet on MetaMask' , can we run a check for Tangle Testnet configuration and fetch if it is available, and/or if the switch fails from chain ID, we prompt the user to add Tangle Testnet directly on MetaMask (shown [here](https://miro.medium.com/v2/resize:fit:1400/format:webp/1*zYrmdS0m8LV3hCtixTB1xg.png))?

<img width="1195" alt="Screenshot 2023-10-04 at 7 54 46 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/a3b614d3-4fcd-4383-891e-e12e34b82856">
