### ISSUE TITLE
[BUG] Improve withdraw card amount input fields

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1754]
### Overview

Improvements and fixes needed for amount input fields in the bridge dapp's withdraw card:

**1. Update custom/fixed amount toggle according to the design.**

Current:

https://github.com/webb-tools/webb-dapp/assets/53374218/75946ebf-ebc7-49f1-9056-ee27959632cc

Design:

![CleanShot 2023-10-06 at 14 49 23@2x](https://github.com/webb-tools/webb-dapp/assets/53374218/50954177-80e5-42c7-883f-c8a9b474781a)

![CleanShot 2023-10-06 at 14 49 12@2x](https://github.com/webb-tools/webb-dapp/assets/53374218/0de4c566-0f57-4426-b5b5-c1c8dbb19bc5)

**2. Users should only be able to enter an amount up to their available balance in the custom/fixed amount input field. If the entered amount exceeds the available balance, feedback should be provided, prompting them to enter a number within the bounds of their available balance.**

Screen Recording:

https://github.com/webb-tools/webb-dapp/assets/53374218/c01d9806-5c57-477a-9ec0-bb63304078c8

**3. Currently, fixed amount increments are increasing by 0.01, but we should utilize a set of predefined values, such as 0.1, 0.5, 1.5, 2, etc. The selection of these fixed incremental values should be confirmed following a discussion.**

Screen Recording:

https://github.com/webb-tools/webb-dapp/assets/53374218/53842ad2-58e2-40f2-ba1f-523b2e93d938

**Comment by AtelyPham** [comment]
For the second review, as it stands, the bridge disables the withdraw button and changes the text to `Insufficient Balance` whenever users enter an amount that exceeds their available balance.

For the third review, I propose we shift the discussion to a separate issue to facilitate ongoing dialogue.
