### ISSUE TITLE
[BUG] transfer failed

### ISSUE THREAD

**Issue by dukangbtc** [webb-tools/webb-dapp#1756]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "key": executable file not found in $PATH: unknown.
when run
docker run --rm -it --platform linux/amd64 --network="host" -v "/var/lib/data" \
ghcr.io/webb-tools/tangle/tangle-standalone:main \
     key insert --base-path /var/lib/tangle/ \
    --chain /data/chainspecs/tangle-standalone.json \
    --scheme Sr25519 \
    --key-type acco

**Comment by AtelyPham** [comment]
If you encounter any issues while transferring on the bridge dapp, please consider taking a screenshot of the error or recording your screen when you reproduce the error. Then, re-open the issue with more information. This will be extremely helpful for us when it comes to reproducing, debugging, and fixing the issue.

**Comment by AtelyPham** [comment]
Moved https://github.com/webb-tools/tangle/issues/274.
