### ISSUE TITLE
[TASK] Implement Header Section with Breadcrumb & CTA

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1769]
@monaiuu to add detail here

What should appear after users click on the Button and the Icon on the left?

<img width="582" alt="Screenshot 2023-10-16 at 17 31 09" src="https://github.com/webb-tools/webb-dapp/assets/69841784/14ea55e2-c99e-44e3-90fd-e4d2ee79e66a">

**Comment by monaiuu** [comment]
For the breadcrumb component, since the "Faucet" page doesn't have multiple levels or subsections, it's reasonable for "Faucet" to be non-clickable since there isn't a hierarchical structure to navigate.

The rationale for including it is to ensure consistency across other pages from the side nav.

**Comment by vutuanlinh2k2** [comment]
@monaiuu Oh I mean on the right side, with the button and the "3 dots" icon, @monaiuu

**Comment by monaiuu** [comment]
For the icon, we can use the same dropdown component from [Hubble Bridge](https://app.webb.tools/) with the following items: 

Docs -> Tangle Docs (link once available)
[Help Center](https://t.me/webbprotocol)
[Request Features ](https://github.com/webb-tools/webb-dapp/issues/new?assignees=&labels=&template=feature_request.md&title=)
[Substrate Portal ](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-archive.tangle.tools#/explorer)
[About](https://www.tangle.tools/)
