### ISSUE TITLE
[FEAT] Redirect Users to Account Dashboard Upon Successful Transaction

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This is not exactly a problem, but rather a CTA improvement towards the Account Dashboard page after a transaction has been successfully completed.

Following user deposits into the pool, we propose to introduce a View Account button on the Transaction Progressor Dropdown component (reference image below). This button will redirect users to the Account Dashboard page. Once this redirection takes place, the transaction will be removed from the Transaction Progressor Dropdown. Moreover, is it possible to add a temporary highlight (akin to a hover state view) to the row of the shielded assets table that corresponds to the transacted asset?

In cases where users are already on the Account Dashboard page, the Dismiss button should be displayed by default.

**Comment by vutuanlinh2k2** [comment]
I don't think "adding a temporary highlight (akin to a hover state view) to the row of the shielded assets table that corresponds to the transacted asset" is necessary at the moment. The other part of this task is done by @AtelyPham in this [PR](https://github.com/webb-tools/webb-dapp/pull/1811)
