### ISSUE TITLE
[FEAT] Introduce Client-Side Storage for Transaction History on Account Dashboard Page

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The requirement at hand involves storing users' transaction histories on the account dashboard. However, after extensive research, it is apparent that our current GraphQL backend does not provide a viable means to host transaction history data based on individual user accounts. Consequently, I propose that we utilize client-side storage, specifically within the user's browser, to store this data.

### Describe the solution you'd like

The [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) seems to be an ideal fit for this task, as it can accommodate larger volumes of data compared to localStorage. You can learn more about its capabilities [here](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#other_web_technologies).

### Technical Implementation Details

The first step involves creating a new class, potentially named `TransactionManager`, dedicated to retrieving and storing user transactions. We would then instantiate a single instance of this class in the `WebbProvider` component, mirroring the current setup with `NoteManager`.

In this class, we'll need to provide support for multiple accounts simultaneously. The account key would correspond to the user's wallet address, which will map to a record of transactions for that account (with the transaction hash as the key and the actual transaction as the value).

For each transaction, we propose storing the following details:

- ID: Transaction hash
- Amount: Transaction amount
- Source Chain ID: The ID of the source chain involved in the transaction
- Destination Chain ID: The ID of the destination chain involved in the transaction
- Recipient: The recipient address linked to the transaction
- Created Time: The timestamp of the transaction (retrievable on-chain)
- Relayer: The relayer used for withdrawal or transfer transactions (retrievable on-chain)
- Relayer Fee: The fee associated with the relayer used for withdrawal or transfer transactions (retrievable on-chain)
- Input Notes
- Output Notes

**Comment by AtelyPham** [comment]
We would also consider associating the transaction records with the anchor identifier, as we simultaneously support multiple bridges. It wouldn't be logical for the currently active bridge to display transactions from other bridges.

**Comment by AtelyPham** [comment]
Consider utilizing the following library to interact with IndexedDB: [Dexie.js](https://dexie.org/docs/Tutorial/React).

**Comment by vutuanlinh2k2** [comment]
Closed in this [PR](https://github.com/webb-tools/webb-dapp/pull/1837)
