### ISSUE TITLE
[TASK] Update typescale in UI kit

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1838]
## Description

As per request, update the type scale for body text in UI kit to enhance readability with our existing designs. This update involves increasing the font size and line height for our body text classes. The new font sizes should be applied across all components in the UI kit where these body classes are used.

**Body01:**
Current: size `16px`; line height `24px`
Update to: size `18px`; line height `27px`

**Body02:**
Current: size `14px`; line height `21px`
Update to: size `16px`; line height `24px`

**Body03:**
Current: size `12px`; line height `18px`
Update to: size `14px`; line height `21px`

**Body04:**
Current: size `10px`; line height `15px`
Update to: size `12px`; line height `18px`

### [Figma Link](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=484%3A2006&mode=design&t=M1bkjklGyqb26Q8x-1)

Note: Post-update, some existing designs may require review and updating to ensure visual balance, this will be addressed iteratively.

**Comment by monaiuu** [comment]
archiving this as I believe we should transition typescale from `px` to `rem` for improved accessibility & ease of maintenance.

**Comment by monaiuu** [comment]
archiving this as I believe we should transition typescale from `px` to `rem` for improved accessibility & ease of maintenance.

**Comment by yurixander** [comment]
Is this still relevant 👀? @monaiuu
