### ISSUE TITLE
[UI] Refactor Leaderboard UI into a Reusable React Component

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your UI update related to a problem? Please describe.

We aim to refactor the Faucet UI to enable its reuse across various dApps (such as Bridge dApp, EVM Staking dApp, etc.). Note that this extraction pertains only to the UI; the API and authentication will remain reliant on the Faucet backend.

### Describe the solution you'd like (include image or link to prototype)

Our proposed solution is to transform the Faucet UI into a reusable React Component. This will facilitate its use across both React and Next.js apps.

**Comment by yurixander** [comment]
@AtelyPham this issue seems to be referencing something about the Faucet, but the title mentions the leaderboard UI? If this is being done with the purpose to embed the leaderboard on the marketing site (tangle.tools), I am handling that on #1866.

**Comment by AtelyPham** [comment]
Yeah, you can link this issue to your PR.
