### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Testnetnodes** [webb-tools/webb-dapp#1865]
When I request a token from faucet, I get an error " You have already requested within the specified time. Please wait 1 hour and 9 minutes before making another request"

**Comment by AtelyPham** [comment]
Hello,

Thank you for submitting your issue. Could you please provide more information about the transaction? This will enable us to assist you more effectively. 

- Have you received the token in your wallet?
- Which chain and token did you use to request from the faucet?
