### ISSUE TITLE
[TASK] Create airdrop statement HTML docs and add domain to cloudflare

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1877]
# Overview
We want to have documents such as https://statement.polkadot.network/regular.html, https://statement.polkadot.network/saft.html live on some subdomain such as `statement.tangle.tools/xyz.html`. It should just be a plain HTML doc with the statement for both.

**Comment by thomivy** [comment]
See repo for code
[https://github.com/thomivy/tnt-claim-statements](https://github.com/thomivy/tnt-claim-statements)

**Comment by thomivy** [comment]
Issues fixed and ready to deploy @drewstone

**Comment by drewstone** [comment]
Ok, likely it needs to be a directory in the dApp repo. @AtelyPham @vutuanlinh2k2 or @devpavan04 can we get these two files in Thom's GitHub into a hostable place in Webbs organization. Just needs to be a basic plain html file no CSS or design.

**Comment by AtelyPham** [comment]
Done: https://statement.tangle.tools/

- https://statement.tangle.tools/airdrop-statement
- https://statement.tangle.tools/safe-claim-statement
