### ISSUE TITLE
[BUG] Leaderboard thumbnail image has old copy

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://leaderboard.tangle.tools/ thumbnail in Slack/websites/Text/Discord show an old image
<img width="403" alt="image" src="https://github.com/webb-tools/webb-dapp/assets/13153687/cd36dea8-f090-441d-b5bd-1077f2dc8eda">

### Expected Behavior

All sites on tangle domain should use the same image, the tagline is "MPC as a service..." I would even suggest we update this CC @monaiuu @thomivy on the site and on the thumbnails to something more like
- "An MPC as a service restaking infrastructure for zero-knowledge and advanced cryptographic applications".
- "An restaking network for multi-party computations. Powering new advanced cryptographic applications."
Do we feel these or others could be stronger than what we currently have?

### Steps To Reproduce

Paste the link in proper environment.

**Comment by monaiuu** [comment]
We should keep it consistent with tangle.tools copy, unless we want to make any updates to below copy: 

![image](https://github.com/webb-tools/webb-dapp/assets/109539270/5d9236df-65e4-4437-b98b-cd8c7a9eaf2c)

@AtelyPham
