### ISSUE TITLE
[TASK] Add stop (Staking.chill) nomination flow

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1926]
### Overview

The current staking interface does not allow nominators to cease their role as a nominator. We should implement a flow that enables nominators to stop nominating and become inactive in staking by invoking the Staking.chill function on the precompiled contract.

### Flow on polkadot apps

https://github.com/webb-tools/webb-dapp/assets/53374218/7b495ad9-ba86-4a8b-8ae9-76d7a1c0d8b7

**Comment by devpavan04** [comment]
@monaiuu Could you suggest where to place the stop button? The appropriate locations might be either in the `nominator stats container` or the `manage dropdown`. We don't really need a flow design since it would be similar to other flows. However, if you think differently, please add the flow design for this feature.

![CleanShot 2024-01-02 at 06 27 08](https://github.com/webb-tools/webb-dapp/assets/53374218/bae805e2-7648-4e8a-b029-6b90642e2d45)

![CleanShot 2024-01-02 at 06 30 44](https://github.com/webb-tools/webb-dapp/assets/53374218/8f48fdfc-69a9-4bfc-be0e-192ae4580dcd)

**Comment by monaiuu** [comment]
### Handoff
Implement a dropdown option to allow users to stop all nominations, with a confirmation modal and subsequent update to the nominations table.

![Screenshot 2024-01-04 at 2 43 25 PM](https://github.com/webb-tools/webb-dapp/assets/109539270/8dce90a7-4b00-4c6b-9fec-6fb74df30bea)


### [Figma Link](https://www.figma.com/file/TxcBogcDFqMA9uuWWuLwI1/%F0%9F%8F%9B%EF%B8%8F-Staking-UI?type=design&node-id=1742%3A39915&mode=design&t=WAfmljqptfQqqAmt-1)
