### ISSUE TITLE
[UI] Add links to Dot Apps to Tangle Website, review menu links

### ISSUE THREAD

**Issue by thomivy** [webb-tools/webb-dapp#1934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by thomivy** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet-rpc.tangle.tools#/explorer

**Comment by monaiuu** [comment]
updated CTA in top nav to above comment link: https://www.tangle.tools/

will wait till we have EVM staking/nomination live to integrate Tangle dApps to top nav, since now we only have faucet/DKG stats.
