### ISSUE TITLE
[CHECKLIST] Extend EVM Staking DApp to Support Substrate Users

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1941]
### Overview

This specification outlines the extension of the EVM Staking DApp, which currently serves EVM wallet users, to also cater to Substrate wallet users. The goal is to enable users of Substrate wallets, such as SubWallet, Polkadot JS Extension, or Talisman, to nominate validators on the Tangle Network.

### Objectives

- Integrate support for Substrate wallets into the existing EVM Staking DApp. When users click the connect button, provide them with the option to select either an EVM wallet or a Substrate wallet. For implementation details, refer to [Airdrop Claims](https://github.com/webb-tools/webb-dapp/blob/f029c4df92e7669b351b848e785681d4ab7a2c8d/apps/tangle-dapp/app/claim/page.tsx#L171-L180) in the tangle-dapp.
- Ensure the maintenance of existing functionalities for EVM wallet users.
- Implement new functions similar to existing functionalities to enable transactions via the Polkadot API. For implementation details, refer to [Airdrop Claims](https://github.com/webb-tools/webb-dapp/blob/f029c4df92e7669b351b848e785681d4ab7a2c8d/apps/tangle-dapp/app/claim/EligibleSection.tsx#L69-L141) in the tangle-dapp and [PolkadotJS docs](https://polkadot.js.org/docs/api/start/api.tx).

### Key Features and Changes
- Substrate Wallet Integration
    - Connect with Substrate wallets (SubWallet, PolkadotJS, and Talisman).
    - Refactor account-related code (EVM & Substrate) after introducing Substrate-based wallet connection.
- User Interface Adaptation
    - Adapt the current UI to support interactions from both EVM and Substrate wallets.
    - Maintain consistency with the current staking dapp UI, except for the wallet connection UI, unless absolutely required.
- Cross-compatibility Testing
    - Ensure compatibility and provide a seamless user experience for both EVM and Substrate users.
    - Ensure that all functionalities, such as nominate, bond, bondExtra, chill, etc., work seamlessly for both types of wallets.

### Note
- Before implementing these changes, make sure to conduct transactions on the [PolkadotJS Apps Extrinsics](https://polkadot.js.org/apps/?rpc=wss://testnet-rpc.tangle.tools#/extrinsics) to become familiar with each API call.
- Convert the following tasks into individual issues and provide a detailed description of each task, along with any necessary information and references needed to complete it. Add @monaiuu to the tasks if any design-related updates or changes are required.

### Checklist

- [x] #1957
- [x] #1970
- [x] #1998 
- [x] #1999

**Comment by drewstone** [comment]
Is this done @vutuanlinh2k2 @devpavan04 ?
