### ISSUE TITLE
[BUG] UI should automatically change after some Nomination and Add Stake flow

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1943]
### Overview

In the current tangle-dapp's staking implementation, when a user successfully bonds some tokens, the wallet balance is not updated in real-time. The user has to reconnect the wallet to the dapp to see the balance change. This is a major UX issue and needs to be addressed.

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/843186c1-920d-4d74-a473-28792640e7b0

**Comment by vutuanlinh2k2** [comment]
After Nomination flow complete, the UI is also not updated 

- The Nominate button still appear
- There is no filter for the Nominations table
