### ISSUE TITLE
[BUG] Received jsob blob  on leaderboard site

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/webb-dapp#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can see some JSON blob while accessing [leaderboard.](https://leaderboard.tangle.tools/). This happens randomly for me

### Expected Behavior

Expected the site to display a leaderboard page all the time and not gibberish data.

### Steps To Reproduce

Open https://leaderboard.tangle.tools/  in new tab

### Screenshot

<img width="1151" alt="Screenshot 2024-01-18 at 9 26 13 AM" src="https://github.com/webb-tools/webb-dapp/assets/11256491/be1ce277-4c54-4cdc-9aef-90df72a3d154">

**Comment by yurixander** [comment]
It's happening to me as well when I open the site.
