### ISSUE TITLE
[TASK] Fix broken outbound & inbound links on webb.tools 

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#1961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some links that are down/misconfigured on [webb.tools](https://www.webb.tools/)'s footer:
- Token Faucet
- Help centre
- Tutorials
- Support
- Tangle EVM Explorer
- DKG Statistics

## Additional note
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/27973442-32ef-4d38-93d9-817d332f5f4f)
I also did this analysis on [an external tool](https://ahrefs.com/broken-link-checker), it seems that some sites are linking back to [Webb's old blog URL](https://www.webb.tools/blog), which is now displaying 404.

Might be worth to setup a redirect from that old URL to the new one if it has a lot of references elsewhere so that no traffic is lost.

### Describe the solution you'd like

Could invest some time in some automatic link checker if we don't have that already.

**Comment by monaiuu** [comment]
We have 195 broken inbound links as indicated in the below screenshot, most are from the migration of old Webb doc site to new Tangle doc site. Anyway we can set up 301 redirects to redirect old URL from Webb docs to Tangle Docs to resolve this? 

## Screenshot
![Screenshot 2024-01-26 at 11 54 19 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/faac61ed-7a95-4f62-a23c-dda81bb77710)

@thomivy @AtelyPham @drewstone

**Comment by thomivy** [comment]
I will submit a PR with these fixes this weekend.
