### ISSUE TITLE
[TASK] Update Tangle Side Navigation Component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1976]
## Description
Update current side navigation for improved visual experience, information hierarchy, and add new pages within the menu list.

### Checklist

- [ ] Move external links (polkadotJS & EVM explorer) to bottom bound
- [x] Update polkadotJS menu item icon to its logo
- [ ] Increase menu items side margins from `4px` to `8px` for improved alignment
- [ ] Remove DKG Stats, add Services (Dashboard, Restake), add Account item

### Screenshot
![Screenshot 2024-02-12 at 9 42 47 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/c2e56224-617e-4f4f-a8d7-e0bf51ad16ee)

**Comment by yurixander** [comment]
Note that this will require the modification of Webb UI's SideBar component, and may need to be adjusted on *all* dapps in terms of React component usage. This is because currently the `SideBar` component has no support for multiple links at the bottom/footer.

Because of this, this task will take more time to complete than what would be assumed.

**Comment by monaiuu** [comment]
> Note that this will require the modification of Webb UI's SideBar component, and may need to be adjusted on _all_ dapps in terms of React component usage. This is because currently the `SideBar` component has no support for multiple links at the bottom/footer.
> 
> Because of this, this task will take more time to complete than what would be assumed.

Ok let me know the status of this. @devpavan04 implemented the side-nav component in Webb UI kit, Pavan do you know if this is something that is doable?

**Comment by yurixander** [comment]
> > Note that this will require the modification of Webb UI's SideBar component, and may need to be adjusted on _all_ dapps in terms of React component usage. This is because currently the `SideBar` component has no support for multiple links at the bottom/footer.
> > Because of this, this task will take more time to complete than what would be assumed.
> 
> Ok let me know the status of this. @devpavan04 implemented the side-nav component in Webb UI kit, Pavan do you know if this is something that is doable?

I've put this on hold on my part for a while now since it requires ~1-2 day of work, but if anyone else would like to claim it feel free to do so!

**Comment by monaiuu** [comment]
Understood, it's not urgent but just wanted to checkin on its status. @devpavan04, when you have a moment, could you share the feasibility of the side navigation component changes, given your familiarity with it? Thanks!
