### ISSUE TITLE
[FEAT] Restake Independent Profile Setup Flow

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1988]
## Description
Implement functionality allowing users to select the 'Independent' profile type within the Restake UI. This flow will enable users to allocate variable amounts of their stake to each selected service independently.

### Key Points:
**Profile Selection:** 
- [x] Implement functionality allowing users to select the 'Independent' profile type within the Restake UI.

**Roles/ Amount Input Selection:**
- [x] Validate inputs to ensure they meet or exceed the minimum required amount for each role.
- [x] Allow users to select roles from a dropdown menu. Ensure that roles already selected are not displayed in the dropdown menu to prevent duplication.
- [x] Implement an error handling mechanism that prompts the user if the input amount is less than the minimum required for a role.
- [x] Disable the 'Add Role' button if the total input amount equals or exceeds the available amount for restaking.

**Dynamic Chart Component:**
- [x] If feasible, integrate a dynamic chart component that visually represents the distribution of stakes across selected roles. Ensure that the chart updates in real-time as users adjust their stake allocations.

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/987b2ad5-2a0b-4f2a-9c7f-bd93461bf433)

**Comment by yurixander** [comment]
>  Validate inputs to ensure they meet or exceed the minimum required amount for each role.

@drewstone *Is* there a minimum amount required per role? I currently seem to be able to set/update my profile with the role amounts being minimal (ie. 1), and looking around at Chain State query functions, under roles, nothing seems to provide the minimum amounts required for each role.

![Screenshot @Arc dJlLqsog](https://github.com/webb-tools/webb-dapp/assets/101931215/58060a38-e96c-46db-a2f2-f272bd3c982d)

**Comment by yurixander** [comment]
>  * Validate inputs to ensure they meet or exceed the minimum required amount for each role.
>  * Implement an error handling mechanism that prompts the user if the input amount is less than the minimum required for a role.

Note: From what I've found, it seems that the minimum restaking amount is not based on a per-role basis, but rather a global constant. So, I have adjusted the logic a bit to work for that instead of per-role.
