### ISSUE TITLE
[TASK] Independent Profile Update Flow

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1991]
## Description
Users who have initially set up their profile with independent restaking need the ability to update their profile. This task involves creating a user interface and logic to adjust the restake amount for each role and to add or remove roles, taking into account the activity status of each service role.

### Key Points:
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/0849f9c4-72ec-4319-84eb-0845d76a0508)
- Increase Stake for Any Role: 
  - [x] Users can add more stake to any role, `active` or `inactive`.
- Decrease Stake for Inactive Roles Only:
  - [x] Stake amounts can only be reduced for roles that currently have no active services.
  - [x] Adjustments to the stake must not fall below the minimum required amount for each role.
- Removing Roles:
  - [x] Users can remove roles only if there are no active services linked to those roles.

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/7961e8c3-5b5d-4c24-bb23-9cb96de5f338)

**Comment by yurixander** [comment]
I will be handling this closely tied to #1988, since the UI is essentially the same but with minor differences. The Substrate logic is also quite similar, if not nearly identical when making the transaction.
