### ISSUE TITLE
[TASK] Add # of Active Services and Restake Amount to Validators Table in Nomination

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1992]
## Description
Update the validators table in the Nomination interface to include additional columns for the number of active services and the restake amount associated with each validator. This enhancement aims to provide users with more detailed insights into the validators' engagement and commitments within the Tangle Network.

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/0f205569-688c-4581-a8a2-dbde93e82369)

### Dependency:
https://github.com/webb-tools/webb-dapp/issues/1986

**Comment by vutuanlinh2k2** [comment]
@1xstj @shekohex can we get the number of active services and restake amount  for each validator with the storage?
