### ISSUE TITLE
[TASK] Implement Validator's Role Distribution Pie Chart Section

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2001]
## Description
Implement a pie chart to visualize the distribution of different roles within the Tangle Network's services on Validator Profile Page for each Validator. The pie chart should be interactive, allowing users to hover over segments to see additional details of each role.

Related tasks and dependency: https://github.com/webb-tools/webb-dapp/issues/1982
[Here](https://www.highcharts.com/demo/highcharts/variable-radius-pie) and [here](https://www.chartjs.org/docs/latest/charts/doughnut.html) are examples of potential hover effect with legend tooltip on the pie chart, for specific implementation please find an appropriate chart library. The color distribution of the pie chart is TBD and can be discussed with design @monaiuu 

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/15e6cbce-940c-4480-8be0-fe39dd44b72a)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/1f9ab247-5e91-4f46-bcbd-4add7b2d5dc4)

**Comment by vutuanlinh2k2** [comment]
The chart for Shared Restake needs to be be added, there is only for Independent right now. Need to add on both Restake and Vadidator page

**Comment by vutuanlinh2k2** [comment]
Wait for @monaiuu to update the Pie Charts to match with real role distribution

**Comment by monaiuu** [comment]
### Chart Update
For all TSSaaS roles, use purple chips for identifier. Below is the breakdown of the color schemas used for each role: 

<img width="578" alt="Screenshot 2024-03-01 at 4 50 50 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/0a1aaa8d-a343-4f13-8581-833a0e22a69d">
<img width="2477" alt="Screenshot 2024-03-01 at 4 48 40 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/8616077f-b65a-460d-8db0-7b0727a694c6">

When listing the roles on legend, sort alphabetically for organization.

**Comment by monaiuu** [comment]
Currently, the above color scheme follows a [linear progression](https://coolors.co/gradient-palette/4b3aa4-b5a9f2?number=12) of colors from the darkest shade of purple (#4B3AA4) to the lightest shade (#B5A9F2), divided into 12 distinct colors (# of roles). Each color represents a step between the darkest and lightest shades, and each step is theoretically equidistant from the next in the color space. Each role is then assigned a color code based on its position in the sorted list in alphabetical order. 

Due to the dynamic nature of roles to be continuously added (and/or removed) over time, I am wondering the feasibility of aiming for a solution that automates the color assignment by developing a dynamic color assignment function, and map each role to a color based on its alphabetical position, with the first role getting the lightest and last getting the darkest? 

Let me know what you guys think is the best way to handle this. @vutuanlinh2k2 @yurixander 


* Also note that `Zengo GG20 secp256k1` can be removed from the list, as it is no longer applicable.
