### ISSUE TITLE
[FEAT] Implement 'Manage balances' table for Tangle dapp account page

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2009]
The manage balances table shown in the account page of Tangle dapp should display a balance breakdown of transferable balance, locked balance, and how much is locked in each category (staking/nominations, democracy, vesting, etc.).

## Checklist
- [x] Do not display balance row if that category has 0 locked balance
- [x] Vesting locked balance row
- [x] Democracy locked balance row
- [x] Staking locked balance row
- [x] Action to transfer tokens from transferable balance
- [x] Details of locked balances should be collapsible
- [x] View time estimates under the `Unlocking At` column
- [x] Disable Substrate-only actions for EVM accounts

**Comment by drewstone** [comment]
Nomination is equal to staking unless we make the distinction for validating (which can equally be seen as nominating yourself).
