### ISSUE TITLE
[BUG] Tangle dapp: `Extrinsic staking.bond expects 2 arguments, got 3`

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2036]
A strange type error is ocurring when calling Polkadot API's `api.staking.bond` function. Its complaining about a missing argument, but that shouldn't be the case. A 'temporary' workaround was done by @vutuanlinh2k2 (who was originally experiencing this issue) by importing `import '@webb-tools/tangle-substrate-types'` in the [apps/tangle-dapp/types/index.ts](https://github.com/webb-tools/webb-dapp/blob/develop/apps/tangle-dapp/types/index.ts#L1) file.

However, this issue might still be relevant as I just experienced the same issue, and the import **did not resolve the error** in my case (I had to revert some of my changes to get it compiling again). It might be worth to look into the exact cause behind this in the future, in case that it comes up again.

[See my recent PR where I spoke more about this issue](https://github.com/webb-tools/webb-dapp/pull/2035#issuecomment-1949482495).

**Comment by yurixander** [comment]
On this topic, I should note that the reason why `@webb-tools/tangle-substrate-types` being imported has an effect, is because it seems to be overriding function signatures from the Polkadot JS API.

This makes sense, as Tangle is built on top of Substrate, so overriding the function signatures  might be to account for chain custom functionality that has been added or modified.

Here's a screenshot of it declaring global modules:

![Screenshot @Visual Studio Code](https://github.com/webb-tools/webb-dapp/assets/101931215/3d01aa51-8949-4c97-9fcb-6f99447e7d77)

**Comment by AtelyPham** [comment]
Is this issue still present on the Tangle dApp, @yurixander? If so, please inform me if you have the bandwidth to address it. Otherwise, feel free to reassign it to me. If it is no longer considered a bug, you may proceed to close it. I think I've resolved the `tange-substrate-type` issue on the dApp.
