### ISSUE TITLE
[UI]The Marquee element is over the screen

### ISSUE THREAD

**Issue by ThugOG** [webb-tools/webb-dapp#2077]
### Is your UI update related to a problem? Please describe.

The Marquee element which shows the investors and contributers is extended outside the screen, it should be hidden if you scroll to the right it can be seen. 
You can visit here https://www.tangle.tools/mainnet-launch to check it
<img width="1512" alt="Screenshot 2024-03-01 at 4 16 29 PM" src="https://github.com/webb-tools/webb-dapp/assets/64457395/d2ccd6a4-5327-4c8c-85a6-a311b71b28c9">

<img width="1512" alt="Screenshot 2024-03-01 at 4 17 04 PM" src="https://github.com/webb-tools/webb-dapp/assets/64457395/1eb1d095-d04b-4cde-9e41-24dd79254cbc">

**Comment by yurixander** [comment]
cc @monaiuu

**Comment by monaiuu** [comment]
thanks for the review! @ThugOG

**Comment by ThugOG** [comment]
My pleasure.

**Comment by monaiuu** [comment]
@ThugOG I am unable to reproduce this on my end, but I have republished the site. Do you mind checking if this issue still persists on your end? 

<img width="1994" alt="Screenshot 2024-03-01 at 5 04 56 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/5f2d1b93-17e7-486c-849b-8297fc4fb094">

**Comment by ThugOG** [comment]
I am viewing it on a 15.4-inch screen. And am still having that thing. Check this video out. 
Also I am produce the error on my tablet.

https://github.com/webb-tools/webb-dapp/assets/64457395/0ba5366f-095c-440e-933f-b36d26094003

**Comment by ThugOG** [comment]
shall I close this, as the element is removed completely it seems.

**Comment by monaiuu** [comment]
> Closing this, as the element is removed completely it seems.

I temporarily removed it to troubleshoot in test environment. Will comment to get you review once fixed. Thanks again!

**Comment by ThugOG** [comment]
always ready to help man.

**Comment by ThugOG** [comment]
Hey

**Comment by monaiuu** [comment]
> Hey, its edited now and seems noice now, but if its the list of investors you forgot about Polychain Capital. Either way I am no one to talk about it but thought to inform you.

nice catch, Polychain Capital has been added into the list of investors.

**Comment by ThugOG** [comment]
I guess the issue is resolved time to close the ticket.

**Comment by monaiuu** [comment]
> I guess the issue is resolved time to close the ticket.

thanks again for your review.
