### ISSUE TITLE
[TASK] Dynamic Linear Color Assignment for Roles/Job Types with API Integration

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2086]
## Description

> This issue is to track the following comments: https://github.com/webb-tools/webb-dapp/issues/2001#issuecomment-1983871707 & https://github.com/webb-tools/webb-dapp/issues/2001#issuecomment-1974240303

Tangle's roles / job types, represented by a progression of colors from dark to light, are subject to change and may evolve over time. To accommodate this dynamism and avoid hardcoding, it's proposed to develop a solution that automatically updates role assignments and their corresponding color codes. 

Proposing the following:

- Adapt the color generation function to work with a variable number of roles, maintaining equidistant color steps between #4B3AA4 and #B5A9F2 for TSSaaS (purple), and similar approach for ZKSaaS (blue) & TX Relay (green).
- Automatically map each role to a color code based on its alphabetical position, adjusting for any changes in the number or names of roles.

The goal of using dynamic assignment is to ensure the system can easily adapt to changes of addition/removal or roles without requiring manual updates to the color scheme while maintaining consistency.  

Let me know your thoughts on this task and the best way to approach it. 

### Initial Comments
https://github.com/webb-tools/webb-dapp/issues/2001#issuecomment-1974240303
> ### Chart Update
> For all TSSaaS roles, use purple chips for identifier. Below is the breakdown of the color schemas used for each role:
> 
> <img alt="Screenshot 2024-03-01 at 4 50 50 PM" width="578" src="https://private-user-images.githubusercontent.com/109539270/309437082-0a1aaa8d-a343-4f13-8581-833a0e22a69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTU2MDksIm5iZiI6MTcxMDE5NTMwOSwicGF0aCI6Ii8xMDk1MzkyNzAvMzA5NDM3MDgyLTBhMWFhYThkLWEzNDMtNGYxMy04NTgxLTgzM2EwZTIyYTY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMjE1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWRiNTNlYmM3ODBkOTM2NWE1MjljNDRlMDM2MTNmZDBkOGZiZmI2MzMyYjY2ODI2MjZjYWQ4NTQ1ZWQwNTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sMJynWLqG-fH_WgsqGvrXpNkbXlBD1XlwkBSxO3ahLA"> <img alt="Screenshot 2024-03-01 at 4 48 40 PM" width="2000" src="https://private-user-images.githubusercontent.com/109539270/309437129-8616077f-b65a-460d-8db0-7b0727a694c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTU2MDksIm5iZiI6MTcxMDE5NTMwOSwicGF0aCI6Ii8xMDk1MzkyNzAvMzA5NDM3MTI5LTg2MTYwNzdmLWI2NWEtNDYwZC04ZGIwLTdiMDcyN2E2OTRjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMjE1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzNkMzVlMzhkNmE4M2M3MzViMzRmMmY5ZmRhOGE5YTBjYzIyZWJjMDI3YmU4MmZiODQyZTY5ZmI0ZDhhY2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-SrDwmXFTzYnLs_0n2h5leqkNPGyeZKPad_2UF3pt0">
> When listing the roles on legend, sort alphabetically for organization.

https://github.com/webb-tools/webb-dapp/issues/2001#issuecomment-1983871707
> Currently, the above color scheme follows a [linear progression](https://coolors.co/gradient-palette/4b3aa4-b5a9f2?number=12) of colors from the darkest shade of purple (#4B3AA4) to the lightest shade (#B5A9F2), divided into 12 distinct colors (# of roles). Each color represents a step between the darkest and lightest shades, and each step is theoretically equidistant from the next in the color space. Each role is then assigned a color code based on its position in the sorted list in alphabetical order.
> 
> Due to the dynamic nature of roles to be continuously added (and/or removed) over time, I am wondering the feasibility of aiming for a solution that automates the color assignment by developing a dynamic color assignment function, and map each role to a color based on its alphabetical position, with the first role getting the lightest and last getting the darkest?
> 
> Let me know what you guys think is the best way to handle this. @vutuanlinh2k2 @yurixander
> 
> * Also note that `Zengo GG20 secp256k1` can be removed from the list, as it is no longer applicable.

**Comment by yurixander** [comment]
Definitely implementable, one thing that concerns me is that when looking at the role chips visually on the screenshot, I can't tell the difference, perhaps it's just me? 😅

@monaiuu

**Comment by monaiuu** [comment]
@yurixander Yes I agree that distinguishing colors can be challenging. I attempted to broaden the color range with darker or lighter shades, but these adjustments compromise accessibility in dark & light themes due to the colors becoming too dark or too light against the respective backgrounds.

I am hoping that by adding hover tooltips to the pie, radial, and bar charts to display the role or job type when a user hovers over a segment, to give clarity without relying solely on color differentiation.

**Comment by yurixander** [comment]
> @yurixander Yes I agree that distinguishing colors can be challenging. I attempted to broaden the color range with darker or lighter shades, but these adjustments compromise accessibility in dark & light themes due to the colors becoming too dark or too light against the respective backgrounds. (although more experimentations can be done.)
> 
> 
> 
> I am hoping that by adding hover `tooltips` to the pie, radial, and bar charts to display the role or job type when a user hovers over a segment, it'll allow users to differentiate each role without relying solely on color variations.

Oh wait, maybe I was just looking at the chips which all have color variant purple, the colors in the right is what will be implemented?

**Comment by monaiuu** [comment]
> > @yurixander Yes I agree that distinguishing colors can be challenging. I attempted to broaden the color range with darker or lighter shades, but these adjustments compromise accessibility in dark & light themes due to the colors becoming too dark or too light against the respective backgrounds. (although more experimentations can be done.)
> > I am hoping that by adding hover `tooltips` to the pie, radial, and bar charts to display the role or job type when a user hovers over a segment, it'll allow users to differentiate each role without relying solely on color variations.
> 
> Oh wait, maybe I was just looking at the chips which all have color variant purple, the colors in the right is what will be implemented?

The chips have no color variations, the gradients colors proposed are only used for charts display.
