### ISSUE TITLE
[TASK] Update & Standardize Tangle Token Icon Display in Account Dashboard

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2105]
## Description
Currently, the TNT token display on Account Dashboard does not match the standard backdrop for Tangle Token Display. If the correct Tangle Token icon isn't part of the UI Kit yet, let's add it to ensure all dApps feature Tangle Token Icon with a uniform background color  `#F2F3FF`, mirroring the chain icon. Similarly, update the account dashboard's token display in both light and dark mode.

### Screenshots
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/372414ec-1690-4143-b8ad-b5ceac4988dc)

**Comment by vutuanlinh2k2** [comment]
Claiming this one @yurixander

**Comment by monaiuu** [comment]
@vutuanlinh2k2 sorry quick edit: should be `#F2F3FF` (instead of `E7E2FF `)

token asset can be found [here](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=4802%3A102230&mode=design&t=zZoJhy9sFMKFJGbQ-1)
