### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Accounts page

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2112]
- [x] Address doesn’t change when switching accounts w/ Polkadot Extension wallet in Account page
- [x] Clickable area around certain buttons isn’t 100% (e.g. Transfer action)
- [x] Transfer modal doesn’t work: Doesn't actually process the Substrate transaction
- [x] Network switching problems in light theme
- [x] Incorrect token balances (linked #2122 solves transferrable incorrection)
- [x] Update copy/tooltip text of balance explanations (total, free, locked, etc.)
- [x] Fix incorrect capitalization of `Airdrop` throughout the app to `airdrop`
- [ ] ⚠️ **COULD NOT REPLICATE**: Metamask auto switching/connect to Tangle testnet when I’m on custom network (doing internal launch testing)
- [x] With Polkadot account, sending vesting tx via the locked balances details' button doesn’t have any TX confirmation loader, etc. (it can also be used anytime; even before any vesting has occurred)
- [x] List & display all vesting schedules, each row including the **original locked amount** and **amount vested thus far**.
- [x] Fix issue where locked balance details remains visible after disconnecting wallet/active account.
- [x] **Incorrect token balances when vesting**: As you can see below, the vesting schedules BOTH have balances, but the first schedule is reading as if it all is sent on the first schedule. Need to assume that there can be multiple vesting schedules, and list proper balances for each.
  <img width="491" alt="image" src="https://github.com/webb-tools/webb-dapp/assets/13153687/ab672deb-6afb-45ab-a44f-8eaa7ea48210">
  <img width="696" alt="image" src="https://github.com/webb-tools/webb-dapp/assets/13153687/446e690a-b51f-4b86-83ff-08c19b2787fa">

**Comment by monaiuu** [comment]
- [ ] Ensure breadcrumb is updated correctly


https://github.com/webb-tools/webb-dapp/assets/109539270/7920e5be-dd39-4a0e-8cad-b38752e03c5a

**Comment by yurixander** [comment]
> As you can see the vesting schedules BOTH have balances, but the first schedule is reading as if it all is sent on the first schedule.

Side note on this, I'm under the assumption that there can only be a single active vesting schedule per account, onchain? cc @1xstj

**Comment by yurixander** [comment]
@drewstone An unfortunate compromise for vesting schedule listings: Can only show the original locked amount for each vesting schedule, can't really show 'amount vested but not released'  per-vesting schedule row.

The reason for this is because when you call the `vest` extrinsic, it releases **all** vested balance from **all** vesting schedules. Because of this, to my knowledge, there is no reasonable/straightforward way to track it per-schedule.

If this is not acceptable, the alternative would be to have a single row displaying aggregate information about **all** vesting schedules, which would allow to track 'amount vested but not released.'

**Comment by yurixander** [comment]
@monaiuu Idea: Green status indicator color for when vesting has completed for a specific vesting schedule, and blue for in-progress? Currently, it looks like the screenshots below: All use the blue color variant.

Also, in case you'd like to adjust the design: I added another status indicator showing **how many tokens have vested of the total**:
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/312bec31-8c59-4f2e-b295-cfa521429989)
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/6f96a3b3-52aa-4185-8f4f-c5edec1ac163)
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/4f68ccb8-c6af-4ff0-97b3-4b5bad248c31)

**Comment by monaiuu** [comment]
@yurixander I will mock this up and let you know any adjustments needed. But sounds good with using diff indicator colors for various statuses.
