### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Nominations page: Bonding

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2114]
- [x] Units are not validating correctly in add/unbond
- [x] Not always listening to cancel hook on add bond transaction (maybe on others), tx spinner goes infinite
- [ ] Decimals don’t work in add bond (maybe in other inputs)
- [ ] Units aren’t present in add bond (maybe in other inputs)
- [ ] Amount inputs: Cannot delete the `0` value, should have a way to have the input be empty
- [ ] Error validation is like extremely optimistic (in that it triggers when it shouldn’t)
- [ ] Check implementation for [minimum_nominator_bond ](https://github.com/webb-tools/tangle/blob/1e443cfa886f716a39529498c15cb54a839458d3/pallets/staking/src/pallet/impls.rs#L1667)

**Comment by yurixander** [comment]
For the amount inputs: I've created an improved version of the `AmountInput` component which essentially solves all the common input problems including units and also validation & min/max amounts; we may be able to use that for this task to solve most of the issues outlined here.

**Comment by yurixander** [comment]
@vutuanlinh2k2 is this done or are you actively working on this?

**Comment by vutuanlinh2k2** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/69841784?s=64&amp;u=305745f0f4b5981b0225f23cca93ba833ae36506&amp;v=4">@vutuanlinh2k2](https://github.com/vutuanlinh2k2) is this done or are you actively working on this?

Just merged your PR that contains `AmountInput`. I will try to implement them to fix the problems with the inputs related to Bond

**Comment by drewstone** [comment]
Linked similar issue https://github.com/orgs/webb-tools/projects/7/views/8?pane=issue&itemId=58048941
