### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Nominations page: Nominate

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2115]
- [x] Visual hover highlight of selecting validators in nomination action is a bit off
- [x] Checklist buttons are not implemented nicely on Nomination validator listing
- [x] We don’t need sort by status in Nomination validator listing
- [x] Ensure `Learn More` button has consistent paddings as the rest of the buttons

**Comment by monaiuu** [comment]
I have a few adjustments I'll like to get in for the Nominate flow, specifically as follows:

- [ ] Setup Nomination (1/3)
  - Update modal buttons copy: `Learn More`; `Next`
  - Align texts with inputs 
- [ ] Setup Nomination (2/3)
  - Update modal buttons copy: `Back`; `Next`
  - Remove texts on the right side for simplicity (users can reference to doc site instead), make scrollable menu list for validators selection fill-width
  - Move `copy` icon adjacent to validator identity
  - Fix `copy` tooltips lagginess
  - Update chips components to use monochrome chips
- [ ] Nominate (3/3): 
  - Implement min height for modal
  - Update modal buttons copy: `Back`; `Confirm Transaction`

**Comment by monaiuu** [comment]
Added addition task here: https://github.com/webb-tools/webb-dapp/issues/2143

**Comment by vutuanlinh2k2** [comment]
I'm taking this @devpavan04
