### ISSUE TITLE
[TASK] Retrieve Restaking Profile Overview Data

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2131]
The aim of this task is to retrieve profile overview data for the restaking UI. The data includes:

- Total restaked amount
- Available for restake amount
- Total earnings amount
- AYP value

We can use `api.query.roles.ledger` to obtain the `total restaked amount` and `available for restake amount`, and `api.query.roles.erasRestakeRewardPoints` for the `total earnings amount` value.

### Screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/29b1b948-848e-4efa-9e79-63b1eb1a0d30)

**Comment by AtelyPham** [comment]
I don't know how to calculate the APY value on the Restaking page. Do you have any idea? @drewstone @yurixander.

**Comment by drewstone** [comment]
Reopening this since the APY calc is still missing @AtelyPham
