### ISSUE TITLE
[TASK] Obtain Restaking Role Earnings Chart Data

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2133]
Presently, we can utilize the `api.query.roles.erasRestakeRewardPoints` API to retrieve reward data (also referred to as earnings data) for each era.

To obtain the user's reward for each era, we can iterate through all eras and filter by the user's address. The pending task involves converting the era number to a timestamp.

### Screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/e1b80704-addc-4057-b307-15cd40431f6c)

**Comment by drewstone** [comment]
@AtelyPham the points are not the earnings exactly, CC @1xstj can you describe to @AtelyPham how to get the earnings from the points? Maybe there's an easier way here.

**Comment by AtelyPham** [comment]
We determined the staking reward of a validator using the following formula:

`Validator's reward` = (`Era's total reward` * `Validator's points`) / `Era's total points`

Therefore, we'll apply the same methodology to compute the restaking reward.
