### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Add Open Graph site meta

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2140]
Currently the Open Graph site meta information is basic and it is important for SEO to have this be as extensive as possible. It also gives it more professionalism when pasting & embedding links to the site.

![image](https://github.com/webb-tools/webb-dapp/assets/101931215/e21409fe-d3af-4197-bb17-b5d1253eadf3)

**Comment by yurixander** [comment]
cc @monaiuu or @thomivy this could be a good opportunity for some high-quality copy/text for the site's description and other SEO information 🙂

**Comment by monaiuu** [comment]
on this topic, we should also update the SEO image; currently it is using the old Webb SEO image.

**Comment by monaiuu** [comment]
What about the following:

> Explore Tangle dApp: Your portal to managing Tangle Network assets and MPC services, kickstarting advanced cryptographic developments and innovations in blockchain.

**Comment by monaiuu** [comment]
cc @thomivy @drewstone
