### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Airdrop claim audit

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2148]
- [ ] Show information about vesting schedule amount + liquid amount on the Claim Airdrop page
- [x] IMPORTANT BUG: After claiming, when you navigate back to the Claim Airdrop page, it still shows as if the user is eligible to receive the Airdrop. This resolves itself when reloading the page.
- [x] Some typos on ineligible page (`$ TNT`, with an extra space)
- [x] Remove `secondary button`, keep `primary button` (Try Another Account) to remove redundancy. 
- [x] Open Explorer link on Success Claim page must based on current chain's explorer, not Tangle Native Testnet 
  <img width="687" alt="Screenshot 2024-03-27 at 2 43 29 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/71656dcc-3d3c-447b-953c-77586c633a47">

**Comment by monaiuu** [comment]
- [ ] Ensure avatar icons displayed are consistent in account dashboard & airdrop claims
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/b4af82d6-025e-4d48-9686-f2d0178d44e0)
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/f31b02b1-93e8-415d-be9d-c6276e3bbcaf)

**Comment by vutuanlinh2k2** [comment]
Create a separate task for showing information about vesting schedule amount + liquid amount on the Claim Airdrop page here: #2170
