### ISSUE TITLE
Chain switching from withdraw broken on some chains (perhaps missing integrations)

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#215]
**Describe the bug**
On withdraw from Ropsten to Optimism, switch chain button fails, potentially due to missing chain addition to the switcher.

**To Reproduce**
1. Make a deposit on Ropsten
2. Add note to withdraw page.
3. Click switch chains, no modal is presented.

**Expected behavior**
User should be prompted to switch.

**Comment by nepoche** [comment]
Not sure I am seeing then same issue. Please let me know if I missed something that you did to reproduce the behavior:

https://user-images.githubusercontent.com/16654909/145390971-71dfe02a-9147-494f-a466-3e92b222771c.mov
