### ISSUE TITLE
[BUG] 🚀 Pre-launch audit: Nomination Page Transaction Modal Fails to Close on Completion

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2155]
## Current Behaviour
On the Nomination page, when a transaction is processed, the UI updates to reflect the completed transaction, indicating that balances have been updated beneath the modal overlay. However, the modal dialogue that initiates the transaction fails to close, and the initiating button remains in a loading state. This behavior leads to confusion about the transaction's completion status.

## Expected Behaviour
 The modal should close immediately after the transaction has successfully completed, followed by a display of the transaction success notification and an update to the displayed amount. This sequence will provide clear feedback to the user that the transaction has been processed without ambiguity.

## Screen Recording
https://github.com/webb-tools/webb-dapp/assets/109539270/8c4b2358-6d4a-470d-9ae1-7026fdb05f14

https://github.com/webb-tools/webb-dapp/assets/109539270/4c5dfc9e-12e0-4e69-9fa8-28679edf5579

https://github.com/webb-tools/webb-dapp/assets/109539270/04bae148-e82f-4c94-a394-4e8b77ac3e1d

**Comment by vutuanlinh2k2** [comment]
Closed my mistake
