### ISSUE TITLE
Deposits w/ Arbitrum destination not being relayed by relayers

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#216]
**Describe the bug**
Deposits so far from Rinkeby or Ropsten are not being caught or relayed by the relayers. Deposit not yet available continues after minutes, hours, etc.

**To Reproduce**
1. Make a deposit with Arbitrum as the destination
2. Make a withdraw
3. Get stuck with deposit not yet available.

**Expected behavior**
Withdraw gets relayed and works.

**Comment by nepoche** [comment]
This should be fixed with additional relayers listening for events
