### ISSUE TITLE
[BUG] 🚀 Pre-launch audit: Perpetual Loading State During Nomination w/Insufficient Balance

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2167]
## Current Behaviour
When attempting to nominate without a sufficient balance to cover transaction fees, both the modal and button enter a perpetual loading state. This behavior occurs without providing any feedback to the user about the underlying issue.

## Expected Behavior
Instead of entering a perpetual loading state, it should display an error message to the user, indicating the inability to execute the transaction due to insufficient balance. 

## Screen Recording
https://github.com/webb-tools/webb-dapp/assets/109539270/d03b63cd-b7a1-4b9d-a7db-1c93f5277280

**Comment by vutuanlinh2k2** [comment]
@yurixander @monaiuu I fixed this in this [PR](https://github.com/webb-tools/webb-dapp/pull/2199)
