### ISSUE TITLE
[TASK] Switching networks does not cause MetaMask or other EVM wallets to also switch chains

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2186]
When the active network is changed via the network selector, if there is an active EVM account, it should be requested for that wallet (ie. MetaMask) to also switch networks to the new network.

The tricky part would be that MetaMask works off chain ids, and testnet and local development nets currently have the same chain ids, so that may prove challenging.

This may be accomplished with something like this:
```ts
// Request to switch to the network (if it's already configured in the wallet).
await window.ethereum.request({
      method: 'wallet_switchEthereumChain',
      params: [{ chainId: network.chainId.toString() }],
    });

// Or if the network is not added to the wallet, request to add it.
await window.ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: network.chainId.toString(),
            rpcUrls: [network.rpcEndpoint],
            chainName: network.name,
            // TODO: Any other network params?
          },
        ],
      });
```
 
## Checklist
 - [x] MetaMask is using Tangle testnet network even though the network switcher has changed networks
 - [x] MetaMask should switch to local & mainnet networks when the network selection changes
 - [x] MetaMask should prompt to ADD the network if it doesn't exist when switching
 - [ ] The same functionality should both be tested and apply to the Rainbow EVM wallet

**Comment by AtelyPham** [comment]
You can reference [this implementation](https://github.com/webb-tools/webb-dapp/blob/develop/apps/bridge-dapp/src/components/Header/ActiveChainDropdown.tsx) to see how the EVM wallet is triggered to switch chains when the user changes the active chain in the dApp.

File path in the repository: apps/bridge-dapp/src/components/Header/ActiveChainDropdown.tsx
