### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Update 'View Explorer' Link on Mainnet

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2188]
## Description
- Ensure the 'View Explorer' link within the Account Dashboard points to https://explorer.tangle.tools/ when switched to Mainnet in EVM environment.
- Verify and redirect all block explorer links related to EVM mainnet to the new explorer site.

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/2fbbddda-3295-4090-ac0f-a0c99974b42a)

**Comment by vutuanlinh2k2** [comment]
Closed in https://github.com/webb-tools/webb-dapp/pull/2205
