### ISSUE TITLE
[BUG] Transfer transaction will FAIL if attempting to send all transferrable balance

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2221]
This can be reproduced when using the `Max` button.

This is likely because transaction fees are deducted from the transferrable balance itself, meaning there would need to be some left to cover the transaction fees.

There is an alternative `transferAll` method available apart from the `transferAllowDeath` function currently being used, that is likely what we want as I suspect that it covers that specific case of transaction fees on the network/chain itself.

- [ ] Utilize `transferAll` if `amount = maxAmount`
- [ ] Otherwise, default to the current transfer call (`transferAllowDeath`)

**Comment by AtelyPham** [comment]
Duplicate of https://github.com/webb-tools/webb-dapp/issues/2215.

**Comment by yurixander** [comment]
> Duplicate of #2215

Great catch! Closing this duplicate.
