### ISSUE TITLE
[TASK] Update getExplorerURI function for substrate transaction and address + Making sure all tx links on Tangle Dapp are correct

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2224]
### Description 

On PolkadotJs Dashboard there is no way for the users to query for the info of a specific tx or address. We need to use update the `getExplorerURI` as well as the polkadotExplorerUrl for Tangle Mainnet & Testnet to use Statescan
- Mainnet: https://tangle.statescan.io/#/
- Testnet: https://tangle-testnet.statescan.io/

```
export const getExplorerURI = (
  explorerUri: string,
  addOrTxHash: string,
  variant: 'tx' | 'address',
  txProviderType: WebbProviderType
): URL => {
  switch (txProviderType) {
    case 'web3':
      return new URL(`${variant}/${addOrTxHash}`, explorerUri);

    case 'polkadot': {
      const path = variant === 'tx' ? `#/explorer/query/${addOrTxHash}` : '';
      return new URL(`${path}`, explorerUri);
    }

    default:
      return new URL('');
  }
};
```

**Comment by monaiuu** [comment]
@vutuanlinh2k2 on the account dashboard the `view explorer` link redirect users to PolkadotJS currently, can we redirect to Blockscout for EVM wallets, and Statescan for Substrate wallets?

Reference: https://github.com/webb-tools/webb-dapp/issues/2188

**Comment by vutuanlinh2k2** [comment]
> @vutuanlinh2k2 on the account dashboard the `view explorer` link redirect users to PolkadotJS currently, can we redirect to Blockscout for EVM wallets, and Statescan for Substrate wallets?
> 
> Reference: #2188

Yes this task is for handling all the tx explorer link correctly!
