### ISSUE TITLE
[TASK] Notifications for Transfer Tx need more details

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2235]
### Description

Currently, after successfully made a transfer tx, the user only get a notification to inform that tx is completed. It should display more details about the tx like amount, recipient and have a explorer link for the user to navigate too

### Screenshot

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/cc078646-cbd1-478f-b749-ab05248b953f)

**Comment by drewstone** [comment]
Consider also improving error messaging on these toasts.

**Comment by yurixander** [comment]
@vutuanlinh2k2 Just wondering since it is relevant to my active PR -- was this already implemented or not yet? I think I saw some updated and more detailed notification toast success messages
