### ISSUE TITLE
[TASK] Resolve console errors and cleanup console

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2253]
There are a bunch of errors thrown into the console that should be resolved; some of them are coming from Webb UI library (relayers), but most of them directly from the Tangle dapp:

![image](https://github.com/webb-tools/webb-dapp/assets/101931215/9c278668-3e0f-4572-bedf-be1eb65015db)

**Comment by vutuanlinh2k2** [comment]
OFAC Filter Error:
![CleanShot 2024-04-19 at 11 47 03@2x](https://github.com/webb-tools/webb-dapp/assets/69841784/d9cb7225-3e8b-4f76-be9d-5576bdd624be)

**Comment by vutuanlinh2k2** [comment]
> Wallet Config + Wallet Connect
> 
> ![Image](https://private-user-images.githubusercontent.com/69841784/332028316-b4750f1f-3eef-49ab-880e-d2657dbf3038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM0NzQsIm5iZiI6MTcxNjI2MzE3NCwicGF0aCI6Ii82OTg0MTc4NC8zMzIwMjgzMTYtYjQ3NTBmMWYtM2VlZi00OWFiLTg4MGUtZDI2NTdkYmYzMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzNDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZTFkYmY3OGMzNGQ1MDk3YTNmYzQ2Mzc1MWY2NWU0MThlZjQ2YzYzMWFhOTQ1Mzc3NGNkY2JjNzFiYmJiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbBQrRGCC3yYnBZZqXI39ztE6gx0rNAvmBvXipQcLTM)
> 
> Socket: ![Image](https://private-user-images.githubusercontent.com/69841784/332028492-2c5373eb-a5d0-424e-8b21-f33aa65fddbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNjM0NzQsIm5iZiI6MTcxNjI2MzE3NCwicGF0aCI6Ii82OTg0MTc4NC8zMzIwMjg0OTItMmM1MzczZWItYTVkMC00MjRlLThiMjEtZjMzYWE2NWZkZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAzNDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYmU5NTg4NGJkMzgyNjg5NjA4MTQyZmY2MmE4NWVlNTM4ZWMxN2ZhNTNkYTJkYzM2MjljNGE2ZWY4MWMzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pXgFTQr8xi-mSq7GCNM37YXx8MeXD2XjV0WW5KsVLc)

@AtelyPham will handle this in this task
