### ISSUE TITLE
[TASK] Update Errors Messages for Improved UX

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2254]
## Description
Improve the error messages presented to users in toast component by replacing generic system error text from Viem error modules with more informative, user-friendly language. Go through the Viem documentation: https://viem.sh/docs/glossary/errors#errors, evaluate current error messages and corresponding Viem error codes, and rewrite the error messages using plain language that can be easily understood by the user without technical jargon, and replace with new error messages in the system.

Reference: https://viem.sh/docs/error-handling

**Comment by yurixander** [comment]
This has been completed already by @vutuanlinh2k2; closing
