### ISSUE TITLE
[SPEC] Improving multi-asset handling

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#226]
# Overview
Simplify and improve how the dApp handles assets and balances.

# Motivation
The dApp deals with multiple types of assets/balances
1. ERC20 tokens
2. Substrate tokens
3. Substrate ORML tokens
4. Native tokens
5. Wrapped assets

What do we have now?
Those forms of assets are mapped to a type [CurrencyContent](https://github.com/webb-tools/webb-dapp/blob/0288ad7825deba31fbf78fabf5424d84b44a2d80/packages/react-environment/src/types/currency.ts#L19)
for displaying.

# Spec

Moving backward, what is needed by the UI?
-  Listing assets.	 
	- Asset name
	- Symbol
	- Image if any
	- Asset identifier
	- and the asset type
-  Get the balances of an asset with an account/address.
- Determine whether an action is supported on a token (Ex bridge: can this asset moved between chains)
- Determine what chain the asset lives in
- Determine if an asset can be wrapped /unwrapped
- ...

# Resources

- https://github.com/makerdao/multicall
- https://github.com/cavanmflynn/ethers-multicall

**Comment by dutterbutter** [comment]
@nepoche can you update to include context for dynamic currency implementation.
