### ISSUE TITLE
[CHECKLIST] Add Bridge to Tangle dApp

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2270]
# Overview
We'll be integrating bridges soon for Tangle to other chains. We should have a UI in the Tangle dApp that allows people to bridge in our dApp.

### Resources
- https://github.com/sygmaprotocol/sygma-sdk/tree/main/examples
- https://github.com/Phala-Network/apps/tree/main/apps/subbridge

### Tasks
- [x] #2305

#### Before Tangle added to Sygma SDK
When Tangle is not implemented in the Sygma SDK, we can utilize the SDK with their provided testnet to set up the logic for the bridge. When Tangle is officially added to the SDK, then we just need to add its config to the current logic
- [x] #2325
- [x] #2330
- [x] #2363
- [x] #2372
- [x] #2376 
- [x] #2326
- [x] #2385
- [x] #2393

**Comment by vutuanlinh2k2** [comment]
After doing some research on `Sygma SDK` and the code of **Subridge**, here is what I found:

Here is how **Subbridge** handles all tx at the moment, there are 4 types: 
- [**EVMSigma**](https://github.com/Phala-Network/apps/blob/e2d2526/apps/subbridge/lib/transferByEvmSygma.ts): tx from EVM chain, supported by `Sygma SDK`
- [**EVM Other**](https://github.com/Phala-Network/apps/blob/e2d2526/apps/subbridge/lib/transferByEvmXTokens.ts): tx from EVM that, not supported by `Sygma SDK`, done by calling a smart contract function from the source chain
- [**Substrate Phala**](https://github.com/Phala-Network/apps/blob/e2d2526/apps/subbridge/lib/transferByPhalaXTransfer.ts): tx from Phala (their native token). Done by calling an api function supported by Phala
- [**Substrate non-Phala**](https://github.com/Phala-Network/apps/blob/e2d2526/apps/subbridge/lib/transferByPolkadotXTokens.ts): Also done by calling api function of the source chain, requirement: the chain must have functions that supports the transfer of a specific token we want to target

Here are the problems we are having right now:
1. `Sygma SDK` does not support us on any tx at the moment. [Here](https://docs.buildwithsygma.com/environments/mainnet/#registered-routes-and-associated-fee-schemes) is the list of what they are supporting.
2. For **EVM-related** tx, `Sygma SDK` only [supports](https://docs.buildwithsygma.com/ecosystem/new-token/) `ERC20` and `ERC721` at the moment, while `TNT` is the native token of `Tangle EVM`
3. The api for **Tangle** currently does not support bridging tx to any other chain
4. Presumably there are also no Substrate chains that have api functions to transfer assets to **Tangle**

Here are the things we can do:
1. Make a request with Sygma SDK to see what tx they can help us with. Are we requesting them right now? @drewstone  
2. For tx from, we might need to create smart contracts for cases that `Sygma SDK` cannot help us
3. Create bridge tx on **Tangle** to bridge assets to other chains
4. Request other chains to add `TNT` to their bridge function
