### ISSUE TITLE
[BUG] The Transferable balance Error

### ISSUE THREAD

**Issue by ThugOG** [webb-tools/webb-dapp#2280]
As I transferred TNT from one account to another, I had 1.4TNT before sending and I sent 1. So the balance should be 0.4 TNT. Instead it should show me 400 TNT.

Should handle the denominations

<img width="1512" alt="Screenshot 2024-04-30 at 12 32 19 PM" src="https://github.com/webb-tools/webb-dapp/assets/64457395/6de6c67d-231b-495a-8718-61f2fd0ee114">
<img width="1512" alt="Screenshot 2024-04-30 at 12 34 12 PM" src="https://github.com/webb-tools/webb-dapp/assets/64457395/8198af91-84d8-474c-8451-30f9b2a60fe0">

**Comment by AtelyPham** [comment]
It is displaying 377.9999 mTNT (377.9999 milli-TNT, approximately 0.377999 TNT). You can verify this by hovering over the tooltip next to the balance.

Please confirm if this information is clear to you, or if you require further assistance from the team.

**Comment by AtelyPham** [comment]
The formatting of the balance display definitely needs some improvement. I agree that it's a bit confusing. I'll work on fixing it soon.

**Comment by ThugOG** [comment]
Also the values on the polkadot website and tangle dapp are quite off.
![image](https://github.com/webb-tools/webb-dapp/assets/64457395/90e6101e-1d4c-443c-a320-704282fdf685)
![image](https://github.com/webb-tools/webb-dapp/assets/64457395/980b80de-1cf9-490d-8b72-990669e15709)

**Comment by AtelyPham** [comment]
> Also the values on the polkadot website and tangle dapp are quite off. ![image](https://private-user-images.githubusercontent.com/64457395/327351981-90e6101e-1d4c-443c-a320-704282fdf685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTgyNDksIm5iZiI6MTcxNDgxNzk0OSwicGF0aCI6Ii82NDQ1NzM5NS8zMjczNTE5ODEtOTBlNjEwMWUtMWQ0Yy00NDNjLWEzMjAtNzA0MjgyZmRmNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEwMTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YzRkYWQwODgwMWFhZGI5YWNhZTk4ZTVjMjFjZGJiMDBiOGU2MzU2YjI3MWU0YTAxN2NmZDc5OWJlMzAwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HWpBcf8MKy-os-REbE2GGMD4Lr_-Y6Y6p4v14Q5Y2jA) ![image](https://private-user-images.githubusercontent.com/64457395/327352087-980b80de-1cf9-490d-8b72-990669e15709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTgyNDksIm5iZiI6MTcxNDgxNzk0OSwicGF0aCI6Ii82NDQ1NzM5NS8zMjczNTIwODctOTgwYjgwZGUtMWNmOS00OTBkLThiNzItOTkwNjY5ZTE1NzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEwMTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNjVkMjYzNGY0YWY5Y2RiMWRlOTQxZDYwOTg5ZTI4Yzg3YzAyZTliNGU5MTFiMWQ2MzgyYjY5MjQ0NmIzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAIG6ZOsxwo3Sr9d25ZdfqciHVqJtPZQsapW2t-2WwA)

Could you please verify whether your account on both the Tangle dApp site and the Polkadot UI is the same? I've noticed that the balance displayed on my end is correct.

**Comment by ThugOG** [comment]
Yes the account is same.

**Comment by AtelyPham** [comment]
Could you please capture the entire webpage that displays the account address within the wallet button? This way, we can verify that it corresponds to the same account.
