### ISSUE TITLE
[BUG] Active Nomination shows Zero, while it is not zero

### ISSUE THREAD

**Issue by shekohex** [webb-tools/webb-dapp#2302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It shows `0 / 367` of Active/Nomination

### Expected Behavior

It should show the correct value as in Polkadot UI `346 / 367` Active/Nomination

### Steps To Reproduce

1. Go to https://app.tangle.tools/nomination
2. You will notice `Active/Nomination` being `0 / XYZ`

### Screenshot

Current Behavior:
![image](https://github.com/webb-tools/webb-dapp/assets/14620076/1d3c5039-a4c7-43f2-bd9c-97be6bce5cef)
On Polkadot UI:
![image](https://github.com/webb-tools/webb-dapp/assets/14620076/f175afce-0c5d-422e-97ad-3f84f88069c0)

**Comment by shekohex** [comment]
Maybe related to #2295

**Comment by AtelyPham** [comment]
This is fixed on the [develop](https://develop--tangle-dapp.netlify.app/nomination) branch, I will release this soon.
