### ISSUE TITLE
[TASK] Handle logic Sygma Bridge Tx with EVM Source Chain

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2326]
### Description
Handle the logic of bridging assets from EVM chain to a Substrate chain

### Solution
Since Tangle is not added to the Sygma SDK at the moment, we will use [testnet](https://docs.buildwithsygma.com/environments/testnet/#supported-networks) provided by them at the moment. 

[Here](https://github.com/sygmaprotocol/sygma-sdk/blob/main/examples/substrate-to-evm-fungible-transfer/src/transfer.ts) is an example of implementing this logic. We will try to replicate this into our code.

**Comment by drewstone** [comment]
- Only change networks right before we are signing the transaction (so let the user play around with their bridge tx without forcing them to switch chains).
- If you need to connect to the source chain without switching networks, create an RPC connection _on-the-fly_. Once the tx is ready to sign, then switch chains.
