### ISSUE TITLE
[FEAT] Stake card to mint VTokens (ie. from `DOT` to `tgDOT`)

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2333]
## Description
Develop the staking flow (stake, bond, mint) for converting `DOT` to `tgDOT`. This flow should be generalized for other tokens (i.e., `GLMR` to `tgGLMR`, `MANTA` to `tgMANTA`, `ASTR` to `tgASTR` etc.) The Stake/Unstake interface/components can be reused from the Hubble Bridge UI. 

### Requirements
**Parachain Selection:**
- User can select their source parachain via a dropdown icon. This selection will determine the display of the token that is being staked.

**Dynamic Rendering of tgTokens:**
- Post chain selection and amount input, the interface should dynamically calculate and display the estimated LST (Liquid Staking Token) that the user will receive on the Tangle Parachain.

**Tx Details Section:**
- The 'Details Section' above the stake button must display the staking 'Rates', 'Cross-chain Fees', and the 'Unstake Period' clearly for user reference.

**Transaction Process:**
- The staking process will consist of two key transactions:
  - Cross-in Transaction: Users sign to transfer tokens from the source parachain (e.g., Polkadot) to the Tangle Parachain. **EDIT**: This will be done as part of Sygma bridge.
  - Staking Transaction: Users stake the transferred tokens on the Tangle Parachain to mint tgTokens (e.g., tgDOT).

**Overview Card:**
- **Staking:** Display the total amount of tokens currently being staked (e.g., `DOTs`) on Tangle Parachain. 
- **Available:** Show the total amount of liquid tokens (e.g., tgDOTs) that have been minted from staking and are presently available on the Tangle Parachain. It is imperative that this amount adjusts dynamically if tokens are being bridged out of Tangle Parachain to the Tangle Mainnet, reflecting real-time availability.
- **Unstaking:** the total amount of tokens that are currently in the process of unstaking or unbonding. This gives users a clear view of assets that are exiting the staking process but are not yet fully liquid.
- **APY:** Provide the current Annual Percentage Yield (APY) associated with the token. We can consider displaying a historical view in future iteration. 
- **Explorer Button:** provide users with the ability to view detailed tgToken information via a direct link to the blockchain explorer.
- After successful transactions, the Overview Card must refresh to show updated balances including the newly minted LST amounts.

**Error Handling:**
- Implement comprehensive error handling strategies to manage and inform users of insufficient balances, invalid inputs, or transaction failures. Confirmation dialogs and success messages should confirm the completion of each transaction stage.

## Screenshot
<img width="1448" alt="Screenshot 2024-05-27 at 7 27 38 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/8eb7b996-ed29-453d-805e-6addac73958d">

**Comment by yurixander** [comment]
Claiming this one if you don't mind! 🙂 @devpavan04
