### ISSUE TITLE
[FEAT] Validator selection UI & logic for LST

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2334]
## Description
Tangle Liquid Staking mints individualized liquid staked tokens (LSTs) for selected validator(s). These LSTs, known as tgTokens, represent the stake and rewards unique to a specific validator pool.

### Requirements
- Users can select which validator(s) they want to stake to, rather than being funneled into a pre-determined set of validators. This allows users to make informed decisions based on the performance and reliability of individual validators.
- Each validator pool selection has its unique 'Vault', which mints validator(s)-specific tgTokens.  So if user selected validator A & B, it will mint tgToken_AB, whereas if user selected validator B & C, tgToken_BC will be minted. 
- Switching network should render new set of validators option.

**Validator Details:**
- Users should be able to view detailed information about each validator by clicking an 'external' icon next to the validator’s name. This action should redirect them to an external explorer site (e.g., Subscan).
- User can also view the historical performance of the validator on Polkadot-JS. 

## Checklist
- [x] Load validators from selected chain and list them
- [x] Show identities if available instead of raw addresses
- [ ] Show each validator's APY
- [ ] Show each validator's historical data on Polkadot JS ([example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftangle-mainnet-rpc.dwellir.com#/staking/query/tgGmfGBjoCSy3FE6CAj6rYwGCRU1pFmjJtu35swjzD4MzmzVc)) 

## Screenshot
<img width="1131" alt="Screenshot 2024-06-20 at 11 48 37 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/def8714e-9a9d-427d-b98b-6edea48a6844">

**Comment by monaiuu** [comment]
(updated the descriptions)

**Comment by drewstone** [comment]
@devpavan04 for chains where the stake operation is different from a validator, please update the text to change properly. For example, Astar has dApp staking so we will want to say "Select DApp" instead of "Select Validator(s)". For chain's where the operation is a single selection we should ensure we remove the plural (s).
