### ISSUE TITLE
Broken link on the Tangle Dapp

### ISSUE THREAD

**Issue by ThugOG** [webb-tools/webb-dapp#2377]
![image](https://github.com/webb-tools/webb-dapp/assets/64457395/85fc4f12-be6e-4a3f-bbba-67e52b4932e1)
The Learn More button leads to a 404 docs page.

**Comment by yurixander** [comment]
Thank you for reporting this! 🙂

I believe it has been fixed but yet to be released, however I will double check and issue a fix if that's not the case.

**Comment by yurixander** [comment]
I can confirm this has been fixed, but has yet to be released.
