### ISSUE TITLE
[TASK] Fetch or calculate APY to display in the overview page

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2381]
## Screenshot
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/9a249fae-234c-44ea-b554-362765872b15)

**Comment by monaiuu** [comment]
Note: the APY would be determined by the validator(s) selected; need to figure out how to determine the APY should the user select more than one validator. 

May not necessary to display APY on the overview page(?), since user may have multiple txs with various validator pools.
