### ISSUE TITLE
[FEAT] Staking information card

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2384]
## Checklist
- [x] Fetch all balances via `tokens.accounts` subscription
- [ ] Fetch and display: available amount
- [ ] Fetch and display: staked amount
- [ ] Fetch and display: unstaking amount
- [ ] Fetch or calculate and display: APY
- [ ] Clicking `Restake` takes the user to the corresponding restaking page
- [ ] Clicking `View Token` takes the user to the corresponding token page

## Screenshot
![image](https://github.com/webb-tools/webb-dapp/assets/101931215/17aa24ea-39c5-4a1f-b3d7-34feebe62719)

**Comment by monaiuu** [comment]
this UI component is no longer needed; but would still be good to fetch these data.
