### ISSUE TITLE
[TASK] Implement logic/UI that allows for delegating one's tokens to an operator

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2404]
The UI contains:

- A select button that allows users to select an operator to delegate the asset to.
	- An operator selection card that shows the list of operators in the system for users to select.
- A select button that allows users to select an asset to delegate to an operator.
- An amount input that allows users to enter a delegate amount.

### Screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/1c7c96b4-fd3e-44f2-905a-d43dc3717f10)

**Comment by drewstone** [comment]
"Estimated undelegate delay"
