### ISSUE TITLE
[BUG] dApp operations impacting DNS/ web rankings

### ISSUE THREAD

**Issue by meshi6** [webb-tools/webb-dapp#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Problem: Our dApp and website share the same DNS and web address: tangle.tools. As a result, dApp errors and server timeouts negatively impact our website’s ranking on Google Search because these issues affect the web vitals that Google considers for ranking.

### Expected Behavior

Solution: Instruct Google to disregard the dApp URLs and their web vitals.
TASK 1
Add a robots.txt file with the appropriate instructions to the root level of the CNAME app.tangle.tools. Specifically, place it at[ https://app.tangle.tools/robots.txt](https://app.tangle.tools/robots.txt).
Here’s the content for the file:
makefile
Copy code

User-agent: *
Disallow: /
https://www.app.tools/
https://www.app.tools/
https://app.tools/
https://app.tools/
https://app.tangle.tools/nomination?tab=Nominations
http://app.tangle.tools/nomination
http://app.tangle.tools/nomination/
http://app.tangle.tools/claim
http://app.tangle.tools/claim/

### Screenshot

<img width="771" alt="img" src="https://github.com/webb-tools/webb-dapp/assets/15804416/83eb1a50-8ee4-4d87-9e4f-1b49500fe235">

**Comment by AtelyPham** [comment]
We need to update the `robots.txt` file for tangle.tools. cc @monaiuu.

```txt
User-agent: *

# Ensure important content accessibility
Allow: /

# Specify sitemap location
Sitemap: https://www.tangle.tools/sitemap.xml
```

The current file appears incorrect.

![CleanShot 2024-07-06 at 01 50 47@2x](https://github.com/webb-tools/webb-dapp/assets/60747384/df8ea58b-7716-4416-b2eb-933fcf2936ef)

**Comment by monaiuu** [comment]
Double checking on the removal of all disallow links

cc @meshi6

**Comment by monaiuu** [comment]
Updated: 
<img width="742" alt="Screenshot 2024-07-15 at 9 20 18 PM" src="https://github.com/user-attachments/assets/64abebcb-5a7a-431c-977f-ff61bbfd8842">
