### ISSUE TITLE
[TASK] Implement logic/UI for undelegating funds from operator

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2407]
The task aims to implement the unstake (or undelegating) flow on the restake page.

- [x] Develop UI and logic for users to request an unstake with the corresponding amount and operator.
- [x] Create a UI to query and display users' unstake requests in a table.
- [x] Implement UI and logic to cancel one or more unstake requests.
- [x] Build UI and logic to execute one or more unstake requests.

### Design references

- [Figma design flow](https://www.figma.com/design/RnObGwrZiftdH85WowJsy6/%F0%9F%91%A5--Restake?node-id=2435-61208&t=GQdsvgzN6AKtGo6r-11).

**Comment by drewstone** [comment]
@AtelyPham is there a companion task for the Withdraw flows or will that be included in this task/PR?

**Comment by AtelyPham** [comment]
> @AtelyPham is there a companion task for the Withdraw flows or will that be included in this task/PR?

It's a separate issue: https://github.com/webb-tools/webb-dapp/issues/2408. I'll address it this sprint.
