### ISSUE TITLE
[TASK] Implement New Design for Restake

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#2418]
A new version of the restake feature includes:

- [ ] The restake card with inputs and tags. <details><summary>Screenshot</summary><img src="https://github.com/webb-tools/webb-dapp/assets/60747384/0d8b2941-e4c2-499d-8789-f2eb716293be" alt="image-1" width="512px" /></details>
- [ ] The asset info card to show the current selected asset information. <details><summary>Screenshot</summary><img src="https://github.com/webb-tools/webb-dapp/assets/60747384/fbcfd87c-57e0-46a2-8a46-37372c9e3e3f" alt="image-2" width="512px" /></details>
- [ ] The operator info card to display the current selected operator information. <details><summary>Screenshot</summary><img src="https://github.com/webb-tools/webb-dapp/assets/60747384/ecfb3700-3307-4958-9467-62a5e51f3444" alt="image-3" width="512px" /></details>
- [ ] The onboarding card that explains and shows the steps of the restake feature. <details><summary>Screenshot</summary><img src="https://github.com/webb-tools/webb-dapp/assets/60747384/1efdfdbc-f1b0-4308-84eb-72d03a7c5777" alt="image-4" width="512px" /></details>
- [ ] Logic for batching the bridge + deposit + delegate into 1 transaciton.

### Full page screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/60747384/823c95ce-7cf2-44ca-a83b-13ba816dd9a9)

**Comment by monaiuu** [comment]
### Update
For finalized approved design, the below components are no longer needs to be implemented:

- The asset info card to show the current selected asset information.
- The operator info card to display the current selected operator information.
- The onboarding card that explains and shows the steps of the restake feature.

For the restake dapp, we will have single column for deposit and stake, and switch to two columns for unstake and withdrawal based on @drewstone 's request. 

### Screen Recording
https://github.com/user-attachments/assets/01a5f375-044c-4c1b-8e8a-e98c1a72e157
