### ISSUE TITLE
[FEAT] Implement updated & more advanced overview page

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2444]
- [x] #2511
- [ ] #2512

![CleanShot 2024-07-25 at 20 27 25@2x](https://github.com/user-attachments/assets/b5d5bf3e-f08d-4920-bbc8-9865f9f70e75)

**Comment by devpavan04** [comment]
Show assets I have balance in main page.

**Comment by yurixander** [comment]
@devpavan04 Closing this as we'll be merging the overview page with the liquid staking page (see #2568) CC @monaiuu
