### ISSUE TITLE
[BUG] Fix table component header alignment issue

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#2449]
### Overview

The table component header view is misaligned, causing the headers not to properly match the columns below them.

### Screenshots

![CleanShot 2024-07-23 at 19 44 47@2x](https://github.com/user-attachments/assets/9d4d608d-5664-45c7-a157-0a1b85d850c9)

![CleanShot 2024-07-23 at 19 53 22@2x](https://github.com/user-attachments/assets/0fac8c69-9cd2-4b29-ba25-94cf390fa234)

**Comment by yurixander** [comment]
Relevant:
- https://github.com/webb-tools/webb-dapp/pull/2415#issuecomment-2242626403
- https://github.com/webb-tools/webb-dapp/pull/2436/files#diff-30d098f31a500198214f302ec731582cf2d64d0a4a72e85d9ef3e73308d90b78
