### ISSUE TITLE
[FEAT] Ability to prefill from & to tokens, and amounts using the URL parameters in the liquid staking page

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2450]
- Adding the ability to pre-fill form information via URL parameters is a useful feature for shareability of links.
- This allows users to share prepared/pre-filled links with others, expediting forms.
- Be careful with what data is allowed to be pre-filled.
- In terms of implementation, one idea is that it could be implemented via a reusable hook to define and parse URL params, something like `usePrefillParams<ParamTypesHere>(...)`.

**Comment by drewstone** [comment]
CC @vutuanlinh2k2 @vutuanlinh2k2 @devpavan04 this is something I think we should be doing all across the flows too. It allows us to pass around links that will auto-fill details as needed. All things can be configured from the URL for LST, Restaking pages
- Connected chain ("from")
- Destination chain ("to")
- Token
- Amount
- Operator selected
- etc
