### ISSUE TITLE
[BUG]Black Screen Error after the initial load

### ISSUE THREAD

**Issue by ThugOG** [webb-tools/webb-dapp#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to load the Tangle dApp at https://app.tangle.tools/, the site fails to display any content and instead shows a black screen.

### Expected Behavior

The Tangle dApp should load properly, displaying the user interface for managing Tangle Network assets and AVS Blueprints.

### Steps To Reproduce

1. Navigate to https://app.tangle.tools/.
2. Observe the screen after the site attempts to load.

### Screenshot

![image](https://github.com/user-attachments/assets/f4f71350-7561-44e4-9e49-19e31ad4da88)

**Comment by AtelyPham** [comment]
This is resolved on https://github.com/webb-tools/webb-dapp/pull/2452 and will be release soon.
