### ISSUE TITLE
[TASK] Update Checkboxes component on webb-ui-components lib

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2457]
### Description 
Update the UI of Checkbox component based on the new design in Figma

![CleanShot 2024-07-25 at 21 06 34@2x](https://github.com/user-attachments/assets/bf1c85ec-2fb8-40eb-8786-ca90538f3597)

**Comment by vutuanlinh2k2** [comment]
@monaiuu 

I notice the colors here are still used from Material UI, not from our color palette. Will there be any updates on this?


![Image](https://github.com/user-attachments/assets/150b0b95-e5ab-4be6-9d83-22be8be995c8)

**Comment by monaiuu** [comment]
Sorry for the confusion; I was using material UI as reference to improve the checkbox components, let me finalize them quickly.

**Comment by monaiuu** [comment]
@vutuanlinh2k2 see [here](https://www.figma.com/design/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=164-4922&m=dev) for finalized version of updated Tangle checkbox components. I did not include error/indeterminate variants for simplicity. 

The hover overlays are `purple/50` in various opacities. 

<img width="969" alt="Screenshot 2024-07-29 at 4 40 15 PM" src="https://github.com/user-attachments/assets/4c8e0e27-d7a9-4aa6-bb8b-08475abf5745">
