### ISSUE TITLE
[TASK] Update Chain selection menu dropdown

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2458]
### Description

Update the UI for the Chain Selection Dropdown based on the Figma design

![CleanShot 2024-07-25 at 21 17 50@2x](https://github.com/user-attachments/assets/f92020f4-17a8-4081-a6b2-8b7fa528dbed)

**Comment by monaiuu** [comment]
just FYI this chain selection list is pertaining to chain selection modal, which I believe has already been added in the UI kit here: https://webb-tools.github.io/webb-dapp/?path=/docs/design-system-v2-wip-templates-chainlistcard--docs
