### ISSUE TITLE
[SPEC] Integrate granular steps into the withdrawing modal UI

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb-dapp#246]
### Business logic

Currently, we have a state for `GeneratingZk` which is responsible for displaying the withdrawing modal.

Change the WithdrawState enum in mixer-withdraw.ts:

- `GeneratingZk` state should change to `StartingWithdraw`. It will serve the same purpose for displaying the withdraw modal.

Then, augment the WithdrawState enum with the following states:

- `GeneratingWitness` state to enter immediately before the call to `generateWitness()` in `webb-anchor.ts`
- `FetchingKeyFromIPFS` state to enter immediately before the call to `fetchKeyForEdges()` in `webb-utils.ts`
- `ProvingWitness` state to enter immediately before the call to `groth16.prove()` in `webb-utils.ts`
- `VerifyingProof` state to enter immediately before the call to `groth16.verify()` in `webb-utils.ts`

In order to emit these events, a reference of the BridgeWithdraw / MixerWithdraw needs to be added to the function signature for webb-anchor.ts function `generateZKP()` and webb-utils.ts function `proofAndVerify()`.

### UI Updates

Update the appropriate status text in the withdraw modal with the new states.

**Comment by dutterbutter** [comment]
Related to: #395
