### ISSUE TITLE
[TASK] Implement Blueprints Overview Page

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2464]
## Description
The Blueprint Overview Page serves as the central hub for discovering and exploring various Blueprints available on the Tangle Network. This page provides a comprehensive view of all Blueprints, offering detailed information and metrics to help users make informed decisions about which Blueprints to use in their projects.

### Sections/Features:
**Banner Section:**
- Encourages new developers to create and deploy their first Blueprint.
- Includes a call-to-action button linking to a step-by-step guide on the documentation site.

**Search and Category:**
- A search bar allows users to find specific Blueprints by name or keyword.
- Blueprints are organized into categories for easier navigation.

**Blueprint Cards:**
- Each Blueprint is represented by a card that provides essential information at a glance.
- Cards are categorized as either Default or Boosted (incentivized) Blueprints.
- Card Details:
  - Avatar image representing the Blueprint.
  - Name and address of the Blueprint.
  - Description outlining the Blueprint's functionality.
  - Key metrics such as the number of restakers, operators, and Total Value Locked (TVL).
  - Interactive hover states, with selection on card redirects to the Blueprint's detailed page.

### Screenshot
<img width="1202" alt="Screenshot 2024-07-29 at 10 16 29 AM" src="https://github.com/user-attachments/assets/1a7ba1a0-0f1a-4ecc-a5fb-6cecdbfe14b5">
<img width="1445" alt="Screenshot 2024-07-28 at 7 25 34 PM" src="https://github.com/user-attachments/assets/76a9ddf0-d396-4ed9-a334-107b37cfb3c3">

### [Figma Link](https://www.figma.com/design/gjR270TYEOiOwOu7IGrivp/%F0%9F%8C%90--Blueprints?node-id=38-14584&m=dev)

**Comment by drewstone** [comment]
I would still suggest adding some higher contrast to all cards (maybe test out borders and share) as well as adding a much much higher contrast wrapper over the "incentivized" blueprints. Can be done with a bigger top bar indicative of it or something else. I would make the "Boosted" thing a LOT more visible. LEAN IN @monaiuu!
