### ISSUE TITLE
[TASK] Visual Treatments of tgTOKENs

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2465]
## Description
Implement a unified visual treatment for all `tgTOKENs` by applying a Tangle-branded gradient border around each token icon. Ensure the treatment is applied uniformly across all pages. 

Ensure the token icons with the gradient border are flexible enough to be displayed in various sizes. There is no need to apply specific size variants; the icons should adapt seamlessly to different dimensions.

Implement the gradient border treatment in a way that it can easily extend to future token icons as the list of tgTOKENs grows.

### Screenshot
![Image](https://github.com/user-attachments/assets/8356179d-b970-4b4a-87f0-12bbe154a60d)

**Comment by drewstone** [comment]
I think we need at least 1 more concentric circle before this looks like not just a normal border @monaiuu

**Comment by vutuanlinh2k2** [comment]
> I think we need at least 1 more concentric circle before this looks like not just a normal border [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/109539270?u=c818e1e33b450548449a5bfa6574d15b34aca789&amp;v=4&amp;size=48">@monaiuu](https://github.com/monaiuu)

will there be any updates on the design @monaiuu?
