### ISSUE TITLE
[TASK] Implement Blueprint Details Page

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2466]
## Description
Develop the Blueprint Details Page to provide users with an in-depth overview and interaction options for each Blueprint on the Tangle Network.

### Sections/Features
**Blueprint Overview Header**
- Display key information about each Blueprint: name, contract address, github link, description, social directs
- Metrics: # of operators, # of restakers, TVL, active instances
- Deploy Button:  directs users to a step-by-step process for deploying instances of the Blueprint (the deployment flow is WIP).

**TVL Table**
- Display details related to the Total Value Locked (TVL) for the Blueprint.
- Include a ‘Restake’ button that appears when users hover over the table rows.
  - The ‘Restake’ button should direct users to deposit and stake the associated token.

**Operators Table**
- Display a list of operators running the Blueprint, alongside with the key info and metrics.
- On hover, each row should render:
  - ‘View’ button: Directs users to view more details about the operator (Operator Profile Page).
  - ‘Restake’ button: Allows users to restake with the operator (pre-load operator in Restake Tx Card if feasible).

### Screenshots
<img width="1721" alt="Screenshot 2024-07-29 at 10 16 15 AM" src="https://github.com/user-attachments/assets/50f4d4d6-85a1-4965-920f-90571e74471d">
<img width="1734" alt="Screenshot 2024-07-28 at 8 37 10 PM" src="https://github.com/user-attachments/assets/5f4f62fc-e959-425e-b466-0ad198c2f5d9">
<img width="1731" alt="Screenshot 2024-07-28 at 8 38 18 PM" src="https://github.com/user-attachments/assets/64a10477-804d-487f-8f22-9c5372849860">

### [Figma Link](https://www.figma.com/design/gjR270TYEOiOwOu7IGrivp/%F0%9F%8C%90--Blueprints?node-id=20-9700&m=dev)

**Comment by drewstone** [comment]
I think we need greater separation of colors here. Specifically, there doesn't appear to be any between the main background and the background of this container where the other components are being displayed. Wdyt @monaiuu?

<img width="71" alt="image" src="https://github.com/user-attachments/assets/f493f79e-7f56-4a4a-b0f0-85695d93dcc5">
