### ISSUE TITLE
[TASK] Operators Table on Restake Overview Page

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2468]
## Description
Develop the Operators Table on the Restake dashboard to provide users with detailed information about operators and facilitate restaking actions.

### Sections
**Operators Table:** display the following information for each operator:
- Identity: The name or identifier of the operator.
- Address: The unique address of the operator.
- Number of Restakers: The current number of users staking/delegating on the operator.
- Restake Concentration: The percentage or amount of total stakes concentrated on the operator.
- Total Liquidity: The total liquidity managed by the operator.
- Vaults: Display the vaults associated with the operator using stacked token icons.

**Table Row Hover States:** when hovering over an operator row, display the following buttons:
- View: Redirects users to the Operator Profile Page.
- Restake: Redirects users to the Restake page with the operator pre-loaded if possible.

**Search Functionality:** add a search bar to the Operators Table.
- Enable users to search for operators by name or address. The search functionality should similar to the nomination table displaying the list of validators.

### Screenshot
<img width="1588" alt="Screenshot 2024-07-29 at 11 25 23 AM" src="https://github.com/user-attachments/assets/4ad56a7f-a4fd-4099-b8dc-3c12a5d4621d">

### [Figma Link](https://www.figma.com/design/RnObGwrZiftdH85WowJsy6/%F0%9F%91%A5--Restake?node-id=3965-158065&t=WQWXqwzBFhZrYdaG-1)

**Comment by drewstone** [comment]
Looks great @monaiuu. I suggest for this display we don't keep writing `XYZ Liquid Token` let's just use `tgXYZ`
<img width="382" alt="image" src="https://github.com/user-attachments/assets/f07e9497-c4dc-44fc-9357-b03799cd7fad">

**Comment by yurixander** [comment]
Yes, `tgXYZ` makes sense
