### ISSUE TITLE
[TASK] Display Active Service Instances

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2472]
# Overview
An active service instance is a requested instance of a Blueprint by a user. The active services should be query-able by blueprint and displayed.

## Subtasks
- Create hooks to fetch active service instances for each blueprint and for all blueprints.
- Create UI to display CC @monaiuu to link to designs.

**Comment by monaiuu** [comment]
UI to do: @monaiuu

**Comment by AtelyPham** [comment]
Closed in favor of relocating to Tangle Cloud.
