### ISSUE TITLE
[TASK] Service Instance Deployment Flow

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2473]
# Overview
The service instance deployment flow is the process by which a user will request/deploy a service. This requires some general configuration decisions as well as potentially specific configuration decisions based on the blueprint.

The general configuration decisions that we know to be true will be
- Selecting the operators involved (displaying whether they require approval or not)
- Selecting the asset(s) involved
- Selecting the duration of the service instance (time-to-live (TTL)).

**Comment by drewstone** [comment]
CC @shekohex based on the existing blueprint and your future thoughts, will there be specific configuration parameters that need to be set by a service instance requester? Will there be an automated logic for identifying what params these are? i.e. (t,n) for threshold systems, etc.? We would benefit if this was something we could build a reusable/automated logic for onchain.

**Comment by shekohex** [comment]
> will there be specific configuration parameters that need to be set by a service instance requester?

Yes! In most cases it would be an empty list of parameters.

> Will there be an automated logic for identifying what params these are?

Currently, only the types, no names of these parameters.

 > We would benefit if this was something we could build a reusable/automated logic for onchain.

Absolutely! We could augment the hooks with more metadata and documation from the blueprint itself, so it is easier to show it in the UI.

**Comment by AtelyPham** [comment]
Closed in favor of relocating to Tangle Cloud https://github.com/webb-tools/webb-dapp/issues/2546.
