### ISSUE TITLE
[TASK] Update Radios component in UI Kit

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2478]

**Comment by monaiuu** [comment]
## Description
To maintain consistency, align the updates of the radio components with the recent updates to the checkbox components. Refer to the updates in this pull request: [webb-tools/webb-dapp#2489](https://github.com/webb-tools/webb-dapp/pull/2489#pullrequestreview-2207048510).

### Screenshot
<img width="702" alt="Screenshot 2024-07-30 at 4 33 57 PM" src="https://github.com/user-attachments/assets/8c490cdc-6ddd-40a2-aca1-500aa9a71c65">

### [Figma Link](https://www.figma.com/design/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=3396-37319&t=fV0xNmOSrsDs3qU4-1)
