### ISSUE TITLE
[TASK] Restake Vaults Table on Restake Overview Page

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#2520]
## Description
To display a table on the Restake Overview Page that provides users with insights into the list of available tokens currently being restaked, and provide essential information such as Asset ID, Token, TVL (Total Value Locked), and the user's stake.

### Screenshot
<img width="941" alt="Screenshot 2024-08-23 at 6 27 04 PM" src="https://github.com/user-attachments/assets/c3aec51d-7666-44fa-a8e2-fd3b91d5070c">

**Comment by AtelyPham** [comment]
The UI resembles the example in https://github.com/webb-tools/webb-dapp/issues/2444. I will consult with @devpavan04 when I begin this task to prevent duplication.
