### ISSUE TITLE
dApp doesn't fail gracefully when modules don't exist on default chain.

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#26]
**Describe the bug**
Upon opening the dApp, if the chain doesn't contain the `anon` modules then it fails ungracefully.

**To Reproduce**
1. Checkout `master` branch of `anon` and build/start a chain.
2. Checkout `master` branch of `webb-dapp` and run `yarn start:dapp`

**Expected behavior**
If the modules don't exist then we should:
1. Check if the modules exist before trying to load certain pages.
2. Show a page with messaging indicating the lack of these modules.
3. Signal to the user to switch chains (to development)

**Screenshots**
![image](https://user-images.githubusercontent.com/13153687/107542789-8bd21700-6b96-11eb-944e-3c3fa0042739.png)

**Comment by AhmedKorim** [comment]
![image](https://user-images.githubusercontent.com/35463181/108892565-af767200-7618-11eb-8c5b-189b956ef8d5.png)
Error after chain connection is dropped
