### ISSUE TITLE
Cancel Mixer creation 

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#28]
currently, we are calling the Mixer `.init` to get asynchronous instance, The mixer uses `WebWroker` which is terminated once the Mixer `.destory` is called

```javascript
const mixer = await Mixer.init(new Worker(), mixerAssetGroup);

```

There is no clean way to cancel the current mixer creation before it is created or to change the `AssetGroups`

Checking the array length didn't work.

```javascript
useEffect(() =>{
	  const mixerCancelation = Mixer.cancelationToken();
	  const mixer = await Mixer.init(new Worker(), mixerAssetGroup ,mixerCancelation) // Promise<Mixer>;
	  
	  return () =>{
	  
	   mixerCancelation.cancel() // this should cancel all the work on progress and terminate the worker
	   
	  } // the mixer needs to be terminated before initializing  or a new mixer should be created
}, [mixerAssetGroup])

```

**Comment by drewstone** [comment]
We should have a spec for this more deeply because I'm not convinced we've arrived at an efficient solution.

**Comment by drewstone** [comment]
We can grab the mixer info before we talk to the wasm-utils and present the components before we get stuck loading the wasm mixer.

This would enable us to present the page before the WASM mixer is loaded and the user will have time to look at the UI and not wait before it loads as it currently is.

**Comment by drewstone** [comment]
1. First grab this `MixerInfo`
```
pub struct MixerInfo<T: Config> {
	pub minimum_deposit_length_for_reward: T::BlockNumber,
	pub fixed_deposit_size: BalanceOf<T>,
	pub leaves: Vec<Data>,
}
```
2. Then render the UI
3. Then send the leaves to the WASM mixer to rebuild.
