### ISSUE TITLE
Query anchors from `api.tx.anchorBn254.anchorList` mutate the state object with anchors

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#314]

**Comment by AhmedKorim** [comment]
Implemented on `polkadot-bridge-api`
[SRC](https://github.com/webb-tools/webb-dapp/blob/74ea4bf60b46dcf9895cef17fe473d6f97760c94/packages/react-environment/src/api-providers/polkadot/polkadot-bridge-api.ts#L17-L17)
