### ISSUE TITLE
[SPEC] Integrate `ORML` assets and `Currency`

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#321]
# Overview
In the dApp, the `Currency` is used to represent an asset it's a wrapper around the `CurrencyConfig` which is hardcoded
The goal is to make the `Currency` more flexible to fit dynamic assets (EX ORML assets ..)

# Spec

## `Currency` inner value

```typescript
 type CurrencyInner ={
	    addresses: Map<ChainId, string>;
	    role: CurrencyRole;
	    id: WebbCurrencyId;
	    icon: ReturnType<typeof createElement>;
	    type: CurrencyType;
	    name: string;
	    color?: string;
	    symbol: string;
    }
```
This works fine for EVM and hardcoded configs
## keys to be changed

- `addresses:Map<ChainId, string>`  
For the substrate side there are no `addresses` (this could be replaced with  `locations` .. maybe?  )
So the `Map` value will be the Contract address for EVM currency and for substrate could be the id of the asset
- `id:WebbCurrencyId`
For dynamic assets, the enum `WebbCurrencyId` won't fit. as this is used to identify an asset this id could be replaced with a string 
```typescript
export enum CurrencyType {
  ERC20,
  NATIVE,
  ORML,
}
type AssetId = `${CurrencyType}-${string|WebbCurrencyId}`

const ethId:AssetId =`${CurrencyType.ERC20}-${WebbCurrencyId.ETH}`// valid;
const wethId:AssetId = `any-${WebbCurrencyId.WETH}` // invalid; 
const ormlNative:AssetId  = `${CurrencyType.NATIVE}-${WebbCurrencyId.WEBB}` // WEBB currency native chain
const ormlNativeWithId = `${CurrencyType.ORML}-${String(0)}` // WEBB currency native chain
const ormlForeign :AssetId = `${CurrencyType.ORML}-${String(15)}` // WEBB currency on another chain given that this id is `15` on another chain

```

**Comment by drewstone** [comment]
I don't think we should add chain info to the tokens. We can also keep the IPFS icons hardcoded on the dApp.
