### ISSUE TITLE
[BUG] MetaMask request wont cancel if the user switched to a Pokadot-js based chain

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#325]
# Overview

If the dApp interacted with MetaMask for network switching or usage access the request will be fullfiled even if the user decided to use another network that uses substrate/polkadot-js

**Comment by AhmedKorim** [comment]
This is the current behavior if we allowed the user to cancel the switching while it's being processed, we aren't allowing that though
https://user-images.githubusercontent.com/35463181/182346402-92c99c4b-d84b-41b3-86f0-d6c75ccf0be9.mp4

Is it okay to disable the cancelation of network switching if it's in the process? thus this isn't a bug,
and I guess This is connected to the extra web3-provider notification.

**Comment by dutterbutter** [comment]
@AhmedKorim https://github.com/webb-tools/webb-dapp/issues/444 related to this issue, I guess?
