### ISSUE TITLE
Assets don't show properly , withdraw select currency input don't select

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#35]
- some currencies Aren't showing properly
- For withdraw, The currency isn't selectable!

Should we remove any? if so how to judge what to remove

![image](https://user-images.githubusercontent.com/35463181/108134965-dd5f3200-70bf-11eb-9ece-11c225e5f78a.png)

**Comment by shekohex** [comment]
remove everything and keep `EDG` for now.
