### ISSUE TITLE
[SPEC] Optimize leaf fetching in `ApiProvider`

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#413]
## Overview

The current flow `ApiProvider` function consists of:

1. Group utxos by insertion chain
2. Fetch leaves for all insertion chains
3. Create `VAnchorPMSetupInput` and send to `sdk-core` for a proof

The fetching of leaves operation should be reviewed and a new optimized approach should be considered. One potential solution discussed was add multi-threaded support. 

- [ ] Outline potential optimized solutions
- [ ] Benchmark existing approach vs new approach

**Comment by dutterbutter** [comment]
@nepoche please provide any additional details to this task as you see fit. Thanks.

**Comment by nepoche** [comment]
Currently for proof generation with multiple different source chains, leaves are fetched sequentially instead of at the same time. We should fetch leaves from all source chains at the same time as an optimization.
