### ISSUE TITLE
[DX]  [BUG] Hot module replacement isn't work on the DApp

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#424]
**Describe the bug**
Webpack hot module replacement doesn't work on the dApp which makes a bad developer experience, and increases the development time of UI/features

**To Reproduce**
Change the dApp code, the changes require browser full reload

**Expected behavior**
- At least the UI component should update without a full reload

**Comment by dutterbutter** [comment]
Closed in #530
