### ISSUE TITLE
[SPEC] Cross-chain VAnchor Flows for Substrate

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb-dapp#437]
# Overview

This is intended to be a core flow for our application, so we should have a way to test this functionality. The currently available runtimes which integrate webb pallets are `protocol-substrate` and `eggnet`.

# Issues / Open Questions

- How can we test the cross-chain flow:
    - manually?
    - In CI?

**Comment by dutterbutter** [comment]
@AhmedKorim please provide context to what the blocker is, and any other relevant findings.
