### ISSUE TITLE
Implement our own IP API

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#45]
can we implement our own IP API, it's trivial to implement and we don't share our app cookies since we care about privacy.

The current one fails due to CORS error.

**Comment by shekohex** [comment]
I strongly agree with this, but how to get the users real-IP without a server?

**Comment by drewstone** [comment]
I support this long term.

**Comment by drewstone** [comment]
I guess one other question is how our solution will be any "more" private to the outside observer. Is there a trustless way to handle this
