### ISSUE TITLE
[TASK] Enable the Drawer component to go full screen

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#605]
**Is your UI update related to a problem? Please describe.**
The Drawer component  doesn't go fullscreen

**Describe the solution you'd like (include image or link to prototype)**
The full-screen button doesn't go fullscreen
![image](https://user-images.githubusercontent.com/35463181/191532787-8ad753f6-7dd5-409b-89c4-8b7cdd3d6b5c.png)

**Comment by dutterbutter** [comment]
Yes that is correct @AtelyPham
