### ISSUE TITLE
[BUG] The `useDarkMode` hook not work correctly

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#618]
**Describe the bug**
The [`useDarkMode`](https://github.com/webb-tools/webb-dapp/blob/0992195e9191a76c6701449e27ddceab2fe65215/packages/webb-ui-components/src/hooks/useDarkMode.ts#L55) hook right now not working correctly in some components. In the ThemeSwitcher component, the hook works fine (we can see the icon for the theme change each time we hit the theme button). But in other components like [`DonutChartContainer`](https://github.com/webb-tools/webb-dapp/blob/30c9a7ca3ef20674efe9f153a2147562fb34d1d1/packages/page-statistics/src/containers/DonutChartContainer/DonutChartContainer.tsx#L16), the hook does not work correctly.

I have spent some time debugging. The state inside the hook changes each time we hit the toggle theme button, but the components which are using the hook do not re-render.

**To Reproduce**
1. Go to `Proposals Page` on the statistic app.
2. Try to switch the theme a few times.
3. We can see the donut chart does not update colors correctly when we update the theme.

**Expected behavior**
The `useDarkMode` hook should trigger a re-render inside components that are using the hook.

**Screenshots**

https://user-images.githubusercontent.com/60747384/192588477-a82511ea-1a86-4664-a1ff-9caf06e5a505.mp4

**Comment by devpavan04** [comment]
<img width="1112" alt="Screenshot 2022-12-15 at 4 20 54 PM" src="https://user-images.githubusercontent.com/53374218/207993881-b24b9eb4-147a-4556-8386-7e473d6ed9bd.png">
