### ISSUE TITLE
[TXButton] Extract the login so we can split the flow for more steps

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#62]
Right now TXButton is calling the mixer to generate a `Leaf` and it issues the RPC calls ..etc.
to enable this #9.
we need to generate the leaf to show it to the user first or downlaod it

**Comment by drewstone** [comment]
well we can just handle it now by moving the TxButton into the modal and replacing it with the button to show the modal and generate the note.

**Comment by AhmedKorim** [comment]
This work as the note is in the function that returns the params for TXButton, which is called by the button.

so this won't work , we could show the note before depositing.

This is fixed anyway
