### ISSUE TITLE
[TASK] Update footer links in stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#622]
## Overview
The current stats page footer is using dummy links, we need to update and remove some links accordingly. 

**Company**
- About Us:  https://www.webb.tools/
- Jobs: https://angel.co/company/webb-4/jobs

**Resources**
- Community: https://docs.webb.tools/v1/getting-started/overview/#join-the-community

**Developer**
- Documentation: https://docs.webb.tools/v1/getting-started/overview/
- Code: https://github.com/webb-tools
- Remove whitepaper for now 

**Network**
- Tangle Network: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstandalone.webb.tools#/explorer
- Statistics: https://www.stats-dev.webb.tools/
- remove governance for now

**dapp**
- bridge: https://app.webb.tools/#/bridge
-  wrap: https://app.webb.tools/#/wrap-unwrap
- Remove crowdloan for now

Social links:
- Discord: https://discord.com/invite/cv8EfJu3Tn
- Telegram: https://t.me/webbprotocol
- Twitter: https://twitter.com/webbprotocol
- Commonwealth: https://commonwealth.im/webb
- GitHub: https://github.com/webb-tools

**Comment by AtelyPham** [comment]
How about links in the below section? @dutterbutter 
<img width="1192" alt="CleanShot 2022-09-30 at 23 31 07@2x" src="https://user-images.githubusercontent.com/60747384/193315972-40fb6fbc-c10a-4428-a00f-02a0bfa49043.png">
