### ISSUE TITLE
[BUG] Active and Next key seems to inverted 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#665]
## Overview 

The Active and Next key seems to inverted on existing stats dapp page. 

### Screenshot
<img width="1192" alt="image (3)" src="https://user-images.githubusercontent.com/29983536/198330988-ebb9b69a-1bbd-4298-9c4d-c3f2d62aab8a.png">

Whereas the active key should be the below key, but it is currently labelled as next key. 

```
[
  835
  0x02a6ea746a80f29bb95f20fd86e3fe70499692197e03766fe9ad3ab486be5a4986
]
```

**Comment by AhmedKorim** [comment]
This is related to the data being older on the stats, The key in the issues is for session 835 while in the stats it's for 139
This is related to https://github.com/webb-tools/webb-subql/issues/35

**Comment by AhmedKorim** [comment]
Adding to the prev comment, the dkg was settled resolved in both the https://github.com/webb-tools/webb-subql/issues/35 , and #656
