### ISSUE TITLE
[BUG] Proposal drawer crashed stats page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#669]
## Overview

When you navigate to Proposals > details the stats dapp crashes. We need to cover more edge cases to ensure the resiliency of the stats dapp. 

### Error

<img width="795" alt="CleanShot 2022-10-31 at 21 25 38@2x" src="https://user-images.githubusercontent.com/29983536/199032646-75827003-9021-4479-93f6-9fa96ab8fc5b.png">

**Comment by dutterbutter** [comment]
Related to: https://github.com/webb-tools/webb-subql/issues/29

**Comment by AhmedKorim** [comment]
This is related to the cryptic types and should be closed with #621

**Comment by dutterbutter** [comment]
Reopening as it seems this was not fully resolved in #656. Specifically when you go to "Details" from a proposal that is NOT `ProposerSetUpdateProposal` it still crashes. For example, if you click 'Details' for `RefreshVote` proposal the dApp crashes. 


<img width="1057" alt="Screen Shot 2022-11-09 at 2 39 28 PM" src="https://user-images.githubusercontent.com/29983536/200937445-4040f1c0-0b1c-41ec-9be5-8bc50b7bbd9c.png">
