### ISSUE TITLE
Labels of the TokenRing component should be static

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#679]
**Is your UI update related to a problem? Please describe.**

The TokenRing component currently has dynamic labels based on the source chain and the destination, it makes the height of the component larger and affects the height of the ConfirmationCard component. That makes the ConfirmationCard height inconsistent with other cards.

**Describe the solution you'd like (include image or link to prototype)**

We should make labels static, then make token icons dynamic in the TokenRing.

**Additional context**

Screenshots describe the solution

**_Polkadot_** to **_Polygon_**

![image](https://user-images.githubusercontent.com/60747384/200039272-50050887-f95f-4119-b573-43f257497c3f.png)

**_Avalanche_** to **_Optimism_**

![image](https://user-images.githubusercontent.com/60747384/200039326-22be548b-6d2e-45db-8eb7-db2ec1e9ddb5.png)

**Comment by dutterbutter** [comment]
We also want to query the bridge instance to only show the token icons of the deployed chains. For example, if we only have eth and polygon deployed we should only show those two icons.
