### ISSUE TITLE
[BUG] Fix uptime / location / reputation being reported from stats dApp 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#685]
## Overview

This issue was originally reported in #619 but being reposted for new QA session. Currently the stats dApp reports the authorities uptime, location, and reputation inaccurately. We need to ensure the accuracy of these fields and in cases where location is not provided we should display 'Unknown'. 

This task depends on the `im-online` pallet working as intended. 

Furthermore, we should include tooltips for each of the authorities table headers that outline the formula used to calculate uptime / reputation with example.

**Comment by AhmedKorim** [comment]
The chain id is `0` for internal proposals and we are displaying the Webb logo in the table, other than that we display the logo for the chain `typedChaindId` -> `logo` from the chain config in the dApp

**Comment by dutterbutter** [comment]
Closed in #701
