### ISSUE TITLE
[BUG] chain does not match between table data and detail

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#686]
## Overview

The chain does not match between table data and detail. 

https://user-images.githubusercontent.com/60747384/200587838-01709319-6a72-4e0f-b914-4e9d8bd27820.mp4

**Comment by dutterbutter** [comment]
A bit confused about your response @AhmedKorim. Shouldn't we want to display the actual chainID for the given chain, in this case it would Tangle Networks chanID?

**Comment by AhmedKorim** [comment]
Internal proposals has the `WebbProposalsHeaderTypedChainId::None` so we can match on the SubQuery API data source and render the right logo for the data source network
