### ISSUE TITLE
[Withdraw] withdraw feedback, spinners and messages

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#71]
It's required for withdrawal action to have the following feedback

1. - [ ] 	Show whether the mixer is initialized or not
2. - [ ] 	After clicking withdraw the button should be disabled and a spinner is shown
3. - [ ] 	For each step show a notification

**Comment by drewstone** [comment]
Also on deposit success, the withdraw note modal should close. Additionally we should require the user to click a checkbox that they have saved the note before allowing them to click `deposit` TX.
