### ISSUE TITLE
[TASK] Add link to etherscan transactions

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#728]
## Overview

We need to add a link to etherscan of the transaction. This link should exist as the 'Details' link in the transaction card (See below image). Currently that is a dead link but we should be able to click and send to etherscan to view the tx there. 

![Screen Shot 2022-11-24 at 7 55 02 AM](https://user-images.githubusercontent.com/29983536/204542469-ab5c5c19-84c7-4502-8d71-b43d998428cd.png)

**Comment by AhmedKorim** [comment]
### Checklist
- [ ] The `Transaction` will contain the tx hash once it's ready
- [ ] in the txQueue hook the write explorer link can be built out from the tx hash or the address of the recipient
- [ ] Details button should be disabled till the explorer link is available
