### ISSUE TITLE
[TASK] Improved error messaging for user

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#732]
## Overview

They're a series of cases that we need to inform the user of. Specifically in cases where they are misusing the dapp. This task should act as a collection of those various cases that we need to handle. This list will be appended as more cases are discovered.

### Cases

- On withdraw, if a user enters an amount where they have insufficient funds we need to distinguish between not having sufficient funds entirely, and not having sufficient funds on the chain in which they are currently connected to. For instance, a user may have an available balance to be withdrawn on Sepolia but is actively connected to Goerli and have no balance. Currently, the dApp simply inform the user "Insufficient balance" whereas, we should indicate _"Insufficient balance on <CHAIN_NAME> please switch to a chain that has a sufficient balance"_ . 
- Similarly on deposit, when the deposit button is disabled we need to inform the user _why_ it is disabled and where applicable surface the chain in which they are connected to.

**Comment by dutterbutter** [comment]
@AhmedKorim please add proposed approach here.

**Comment by monaiuu** [comment]
Addressed in V2.
