### ISSUE TITLE
Bridge Design Audit

### ISSUE THREAD

**Issue by seeddisperser** [webb-tools/webb-dapp#749]
This Issue captures a number of UI edits required for the bridge.
- [x] Lists should extend to the bottom of the card. Overflow should only be hidden if the bottom of the card is reached. 
![list](https://user-images.githubusercontent.com/109543061/204881317-33578a54-07ee-45da-a947-6675b71407c8.png)
- [x] Unavailable tokens must be disabled. See the disabled state for [list items](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1365%3A36152&t=d3fov5lnObt56esD-1). 
![Screen Shot 2022-11-30 at 10 41 24 AM (2)](https://user-images.githubusercontent.com/109543061/204881752-fff8b9ac-f31e-4532-9796-a748724a005f.png)
- [x] There are two different sizes of small all-caps text being used. These both need to be `12px, Bold, Uppercase`
- [x] "Try another wallet" should open the connect wallet modal
- [ ] need to add tooltips to the transaction details.
- [x] transaction cards have a `max-height` of `700px`
- [x] transaction cards should be `align-items: space-between` so that the button is sticky to the bottom. 
- [x] Inputs such as amount need to be in a disabled state until the user is actually able to interact with them. [See the inputs page](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=49%3A7738&t=d3fov5lnObt56esD-1). 
![Screen Shot 2022-11-30 at 10 36 43 AM (2)](https://user-images.githubusercontent.com/109543061/204880893-8f1aad97-40ce-4e3c-a283-e583b6b6132f.png)

@monaiuu using this I feel like hover states are needed for the transaction inputs. Even just a little movement of the arrow icon would help indicate that the element can be interacted with. Thoughts? 

I'll continue to add edits as I find them.

**Comment by monaiuu** [comment]
A few more edits found for Bridge UI:

- In the `amount input`, users should only be able to input numbers (currently, users can input letters).
![Screenshot 2022-11-30 at 2 08 06 PM](https://user-images.githubusercontent.com/109539270/204918659-a6fb0193-fd14-4db0-9974-aceeb3f23e38.png)

- When users select a different chain, the wallet-connection modal appears although the user has already connected a wallet. We can remove the wallet-connection modal and have metamask prompt (add-chain or switch chain)
![Screenshot 2022-11-30 at 2 10 04 PM](https://user-images.githubusercontent.com/109539270/204919253-076dc993-dfdb-4a91-82bb-1db162ac1450.png)

**Comment by AtelyPham** [comment]
Can you add more screenshots or Figma links for the UI stuff, please? That would be very helpful and save time. Thank you 🙏

**Comment by AtelyPham** [comment]
- [ ] [TASK] If the user has not connected their wallet, the button at the bottom of the transfer and withdraw tabs should prompt the user to connect their wallet, as implemented in the deposit tab.

**Comment by dutterbutter** [comment]
Closed in #777
