### ISSUE TITLE
[BUG] Max button don't work for wrap and deposit

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#774]
## Overview
Amount input has a button to set the amount as the current account balance, this button doesn't work as expected for wrap and deposit flow

https://user-images.githubusercontent.com/35463181/205646987-fe4468bf-fe28-4204-899b-519ce1ff1dc0.mp4

**Comment by dutterbutter** [comment]
In a wrap state we should utilize 'weth' in this case as the max amount, but in unwrap state utilize bridged asset.
