### ISSUE TITLE
[TASK] Add missing link to download selected wallet

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#778]
## Overview 

In our wallet connect component there is a link to "Download now" which is currently a dead link in the dApp. We need to add the appropriate link so users may download the MetaMask / Wallet Connect extension if they do not have one installed. 

### Referred Wallet Component 

<img width="701" alt="wallet-component-dark copy" src="https://user-images.githubusercontent.com/29983536/205964445-ea6b07b6-afb3-4dea-81c1-0433ea9746e2.png">

**Download Now link**
<img width="406" alt="Screen Shot 2022-12-01 at 8 09 34 PM" src="https://user-images.githubusercontent.com/29983536/205964538-bb87a2c1-572b-4275-84be-d0cdf58cae3b.png">

**Comment by AtelyPham** [comment]
I think we need to update the design here for the `DOWNLOAD NOW` button. It's a bit confusing because when a user hits this button, which wallet do we choose to redirect the user to download?

**Comment by dutterbutter** [comment]
@AtelyPham for now let's navigate the user to download MetaMask. @seeddisperser @monaiuu not high priority but it would be good to address the comment above. We intend to support multiple wallets so it would be good to address this concern eventually.
