### ISSUE TITLE
[BUG] hitting the max button from quick transfer action  crashes the dApp

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#789]
**Describe the bug**

fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)

**To Reproduce**
1. Go to Shielded assets Table 
2. Click on the transfer action button for a note
3. Click the max button
4. fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35463181/206521641-a65c9bb6-6980-418a-86c6-44fcb7fa53b1.png)
https://www.loom.com/share/7f3d3b18978f46baab369a3d0eec20da

**Comment by dutterbutter** [comment]
Closed in #880
