### ISSUE TITLE
[BUG] All relayer addresses are displaying the exact same address

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#818]
## Overview

I am not entirely sure if this is a BUG or not but it seems odd that the relayer selection component is displaying the same address for all relayers even though each of those relayers have different keys. You can replicate this by reviewing the deployment preview or checking out the branch and running the dApp locally from this [PR](https://github.com/webb-tools/webb-dapp/pull/796).

### Screenshot

<img width="521" alt="Screen Shot 2022-12-13 at 10 36 49 PM" src="https://user-images.githubusercontent.com/29983536/207514995-8c08a22a-5de2-4e03-8dbc-a95c58621910.png">

### Task Checklist 

- [ ] Investigate why all relayers are displaying the same address

**Comment by AtelyPham** [comment]
I guess because all these relayers are using the same private key, you can check by the route `/api/v1/info` and check the `beneficiary` values, they're the same right now.
