### ISSUE TITLE
[TASK] Use proper gas limit for each network

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#821]
**Is your feature request related to a problem? Please describe.**
Different networks have different gas limits. We should avoid hardcoding it always to the same value.

**Describe the solution you'd like**
We should have a map from chains to their hardcoded gas limits.

**Describe alternatives you've considered**
Really just need hardcoded value for **_each_** chain rather than 1 hardcoded value for all chains.

**Comment by AtelyPham** [comment]
Move this issue to https://github.com/webb-tools/protocol-solidity/issues/241
