### ISSUE TITLE
[BUG] Overflow Label on Deposit Confirm Card

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#834]
**Describe the bug**
The source and dest chain label on the `DepositConfirm` card overflowed when users choose the same source and destination chain. (See the image below)

**To Reproduce**
1. Go to the `Deposit` tab
2. Fill in all inputs (the source chain and dest chain should be the same)
3. Click the `Deposit` button to show the `DepositConfirm` Card
4. See the overflowed label.

**Expected behavior**
The labels shouldn’t be overflowed.

Once we fix the issue on the `Deposit` flow, make sure to test the `Withdraw` and `Transfer` flow too.

**Screenshots**

<img
	src="https://user-images.githubusercontent.com/60747384/208930991-b02318d5-0c89-42a5-bab0-32e5419ab5b1.png"
	alt="screenshots"
	width="500"
/>

**Comment by devpavan04** [comment]
#888 resolves this.
