### ISSUE TITLE
[TASK] Chevron icon to switch between custom/fixed amount on the withdraw should be improved

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#838]
**Is your UI update related to a problem? Please describe.**
The Chevron icon on the `amount` input in the Withdraw tab which is used to switch between custom/fixed amounts should be improved. The user has to hover for a while to open the switch modal.

**Describe the solution you'd like (include image or link to prototype)**
We should improve the UI somehow more clearly to let the user knows he/she can click or hover to change the amount type (custom/fixed).

**Describe alternatives you've considered**
For a quick fix, we can remove the delay time of the pop-up modal. In other words, we should open the modal immediately if a user hovers into the `Chevron` icon.

![CleanShot 2022-12-21 at 23 38 25@2x](https://user-images.githubusercontent.com/60747384/208957642-e4bc91cc-7ddc-4734-9c59-96e64878b2bc.png)

**Comment by dutterbutter** [comment]
Closing in favour of https://github.com/webb-tools/webb-dapp/issues/863
