### ISSUE TITLE
[BUG] Prompts SubWallet & Talisman to connect when trying to connect with Polkadot.js

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#852]
### Overview
Connecting wallet using `Polkadot.js` prompts `SubWallet` and `Talisman` to connect instead of prompting `Polkadot.js` to connect.

### Steps to reproduce

1. Select Source Chain
2. Select Polkadot/Kusama chain to connect
3. Select Polkadot.js
4. Prompts `SubWallet` and `Talisman` to connect 

### Loom video
https://www.loom.com/share/e255de16d3ea4183843bbe0108fd8f81

Tested on branch: https://github.com/webb-tools/webb-dapp/pull/850

**Comment by dutterbutter** [comment]
Closed in #876
