### ISSUE TITLE
[BUG] Bridge dApp crash after few minutes of inactivity

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#853]
### Overview
`Bridge dApp` crashed during QA after few minutes of inactivity.

### Issue screenshot
<img width="1419" alt="Screenshot 2023-01-09 at 5 44 20 AM" src="https://user-images.githubusercontent.com/53374218/211322102-ac1cbd73-249b-4922-b86a-82ca95001b0f.png">

Tested on branch: https://github.com/webb-tools/webb-dapp/pull/850

**Comment by drewstone** [comment]
@devpavan04 can you identify where this TX is being somehow executed? It's weird this bug exists because it seems to be that we're trying to make a transaction without any user input.

**Comment by devpavan04** [comment]
This issue could not be reproduced and has not been found with latest deployments.

**Comment by dutterbutter** [comment]
Reopening as it seems we are still experiencing this issue. It looks like we are trying to make a transaction, either with an empty inputs, or with inputs in the component yet we haven't initiated the tx intentionally. Perhaps worth investigating our `TransactionQueueApi` but further investigation is required. 

@devpavan04 @AtelyPham
