### ISSUE TITLE
[TASK] Polling leaves is not needed on deposits

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#855]
**Is your feature request related to a problem? Please describe.**
We are currently polling leaves when trying to make deposits. This is not necessary. Instead we just need to fill in the proof values with dummy inputs (dummy UTXO inputs, dummy merkle proofs and indices for those dummy inputs). Deposits shouldn't need to verify those values in the circuit.

**Describe the solution you'd like**
We should check the type of transaction being made. If it is a deposit, we shouldn't block the flow to poll leaves. Instead we should make the tx and poll leaves in parallel if anything.

**Comment by dutterbutter** [comment]
Closed in #880
