### ISSUE TITLE
[TASK] Have backup RPC urls and rotate when requests fail

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#857]
# Overview
Currently we experience request rate-limiting on some of the networks we deal with. We should have backup API keys (not pushed to the repo but in .env or github .env). When the requests fail we need to gracefully handle this and rotate to a new unused API url.

**Comment by AtelyPham** [comment]
Close in favor of https://github.com/webb-tools/webb-dapp/issues/1226. Because `wagmi` and `viem` library support auto-rotate when a request failed (due to rate limit issue).
