### ISSUE TITLE
[TASK] Improve Note Account Key and Public Key term usage

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#892]
## Overview
The current wallet component surfaces the users 'Note Account Key' but describes it as **PUB KEY**. This is quite misleading / confusing in comparison to a users crypto address which many consider their public key. 

**What is an adequate term to describe a users 'Note Account Key'?**  

I am not convinced that the term  'Note Account Key' is even the best way to describe to users. Any suggestions here? 

### Screenshot 
![CleanShot 2023-01-13 at 15 21 26](https://user-images.githubusercontent.com/29983536/212421545-ba57f39d-aa07-4c58-b10f-36fc8d243afe.png)

**Comment by devpavan04** [comment]
@drewstone Any suggestions here?

**Comment by drewstone** [comment]
I'm OK with Note Account Key truly, I just think we need to have a bit of a bigger font / separation below "Metamask" that signals its a different kind of key maybe.

We could also go with
- Secret Account Public Key
- Note Account Public Key
- Webb ZK Public Key
- zkAddress
- Webb ZK Address

**Comment by devpavan04** [comment]
Okay, I'll make the font size and spacing changes. I think `Note Account Public Key` is a better choice here as the user will be familiar with Note account from the creating a note account flow.

**Comment by monaiuu** [comment]
In reference to the above issue, I have updated the account component UI as follows. This change has also been updated in the Figma Account File. 

### Screenshot:
<img width="947" alt="Screenshot 2023-01-24 at 9 14 29 AM" src="https://user-images.githubusercontent.com/109539270/214181281-10a1ccdf-e63d-49ad-9a02-7be9aa855135.png">

### File Access:
https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=1834%3A18286&t=Pi0Ry914uZp0WVyV-1
