### ISSUE TITLE
[UI] Chain selection component should categorize different chain types / networks

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#894]
## Overview
The current chain selection component groups all chains together regardless of their purpose or ecosystem. For instance, dev, test, and live networks are all displayed in the same list. We should categorize the chains on purpose, and perhaps (needs to examined more closely) by ecosystem, and have the live networks listed first as users in a production env will be selecting them rather than test or dev networks. 

**Proposed division:**
- Live
- Test
- Dev

We could go one step deeper and categorize by ecosystem as well which could be helpful when we support more chains / ecosystems. For instance:
- Live
  - EVM
  - Polkadot 
  - Kusama 
  - Cosmos
- Test ...

### Screenshot
![CleanShot 2023-01-13 at 15 35 24](https://user-images.githubusercontent.com/29983536/212423878-6a81c6ce-e4f6-4b2e-aa1b-860af41502ab.png)

**Comment by monaiuu** [comment]
In response to the above issue, what are your thoughts on using radio buttons to enable users to switch between live networks, Testnets, and dev networks? The rationale behind this decision is that users would not be able to transact between say Dev networks and live networks. Please see below screenshot for reference. 

<img width="885" alt="Screenshot 2023-01-14 at 10 07 29 AM" src="https://user-images.githubusercontent.com/109539270/212443406-32751823-a625-449d-ab83-c35711b26f72.png">

@dutterbutter @seeddisperser @drewstone

**Comment by dutterbutter** [comment]
I like the usage of radio buttons, and alphabetical ordering. 👍

**Comment by monaiuu** [comment]
sounds good, I will update the chain selector component in bridge UI figma file, and add radio components to the design system.

**Comment by dutterbutter** [comment]
Closing in favour of #902
