### ISSUE TITLE
[BUG] UI flickers/moves when switching tabs back to Keys

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#910]
# Overview
In the stats dApp, when switching from any tab to "Keys" the entire UI seems to flicker more aggressively than when switching between other tabs exclusively.

**Comment by dutterbutter** [comment]
To be more precise, it appears the keygen table does not render immediately pushing the footer up, and then re-renders quickly to load the table and its elements. 

We could make the table a fixed height, and just have the loading spinner appear in the middle while it loads up the data for the table.
