### ISSUE TITLE
[UI-COMPONENTS] Update labels and title text case and font size to match with the design

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#926]
### Changes required

- [ ] All the labels and title text should be `capitalized` in withdraw/transfer/deposit components to match with the design.
- [ ] All the text font size needs to be updated (bigger fonts) according to the design in withdraw/transfer/deposit components.
- [ ] Spacing between the labels and input value and input fields padding should be checked and updated to match with the design.
- [ ] All the input fields should have the same height in deposit container component.

### Expected
<img width="493" alt="Screenshot 2023-01-27 at 10 21 23 AM" src="https://user-images.githubusercontent.com/53374218/215165377-b9ca5d15-6b9b-434c-992e-bcee8ee0db89.png">

### Current
<img width="437" alt="Screenshot 2023-01-27 at 10 21 38 AM" src="https://user-images.githubusercontent.com/53374218/215165428-75fad35f-037c-498e-a0f4-7f0d731d5a9b.png">

**Comment by dutterbutter** [comment]
Closing in favour of #1027
