### ISSUE TITLE
[BUG] Withdraw fixed amount background in dark mode not present

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#962]
## Overview
The background on the fixed amount component is not present in dark mode. 

![withdraw](https://user-images.githubusercontent.com/29983536/215848155-a1921f68-e7af-451f-9112-a615d90bc481.png)

**Comment by AtelyPham** [comment]
The initial state of the card is matched with the design [here](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI?node-id=940%3A165148&t=7jhq7U0sug24dDLe-11). Users have to select the token in order to enable the amount input @dutterbutter.

**Comment by dutterbutter** [comment]
I see I see @AtelyPham

**Comment by devpavan04** [comment]
@dutterbutter 

After selecting a token

<img width="439" alt="Screenshot 2023-01-31 at 10 25 23 AM" src="https://user-images.githubusercontent.com/53374218/215849639-810dfa96-f8e8-4c00-a9c7-fc90767f89af.png">
