### ISSUE TITLE
[FEAT] Interactive Feedback Component

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#974]
**Is your feature request related to a problem? Please describe.**
After the migration to RadixUI and TailwindCSS, we removed the InteractiveFeedback components, but we still have the logic and states for the interactive feedback on the bridge. So right now, we need a new interactive feedback component to consume the existing logic and states.

**Describe the solution you'd like**
It's a pop-up modal with a header and the content, `json` or list on the body, the footer contains buttons for actions.

**Describe alternatives you've considered**
A simple version of these components was created in https://github.com/webb-tools/webb-dapp/pull/938 (path `apps/bridge-dapp/src/components/InteractiveFeedbackView`).

**Additional context**
The new component should be added to the `webb-ui-component` lib and only depends on [`InteractiveFeedback.ts`](https://github.com/webb-tools/webb-dapp/blob/714943309389779fdb19763915d6b9c7eaede58f/libs/dapp-types/src/InteractiveFeedback.ts#L0-L1) file.

**Comment by AtelyPham** [comment]
We still need a design for this component @monaiuu @seeddisperser.

**Comment by seeddisperser** [comment]
I'm a little confused about what is being asked. I don't understand what component is needed @AtelyPham

**Comment by AtelyPham** [comment]
Sorry because the confusion, here is an example of that component @seeddisperser 

https://user-images.githubusercontent.com/60747384/216451482-b8dac03f-5a7e-4489-83db-50dc86ca200e.mp4

**Comment by seeddisperser** [comment]
So a modular modal component that can support a variety of messages and actions is needed?

**Comment by AtelyPham** [comment]
Yes, that's right 👍

**Comment by seeddisperser** [comment]
awesome! thanks

**Comment by monaiuu** [comment]
Referencing this issue for inspo https://github.com/Uniswap/interface/issues/2627

**Comment by monaiuu** [comment]
inspo: https://medium.com/@JonCrabb/defi-design-tips-vol-4-b533f9ed3d3a

**Comment by monaiuu** [comment]
To do @monaiuu 
![Screenshot 2024-01-18 at 10 02 18 AM](https://github.com/webb-tools/webb-dapp/assets/109539270/154d27d1-0393-4f3c-b1ba-c4810b940841)
