### ISSUE TITLE
[BUG] Bridge dApp crash after few minutes of inactivity

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#987]
### Overview
Bridge dApp crashed after few minutes of inactivity.

### Screenshot
<img width="1261" alt="Screenshot 2023-02-06 at 7 17 04 AM" src="https://user-images.githubusercontent.com/53374218/217010897-9c15a62e-667e-4017-aacf-99b62682dce3.png">

**Comment by AtelyPham** [comment]
Personally, I think it only occurs in the development environment, when you make new changes, then save -> webpack make a hot refresh -> the dapp queries data (wrappable currencies, balances, etc, etc) -> then we make another save while the dapp is still querying -> that triggers another hot refresh -> new data querying -> error…

**Comment by dutterbutter** [comment]
Closed in #985 and due to rate limiting being tracked in #857
