### ISSUE TITLE
[UI] Improve webbsite image rendering 

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#989]
### Overview
When Webbsite goes below `768px`, images in the below section become distorted/cropped off. Expected behavior: the images should fill the container for the bridge tab section, and for the stats tab section image should render full height. 

### Screenshots
<img width="602" alt="Screenshot 2023-02-07 at 4 36 32 AM" src="https://user-images.githubusercontent.com/109539270/217068007-2c611c9a-4894-4a3e-b2db-435508ce8f3a.png">
<img width="643" alt="Screenshot 2023-02-07 at 4 21 10 AM" src="https://user-images.githubusercontent.com/109539270/217067991-38820a1d-3727-4c2f-8f42-6dfebfacbe8a.png">

**Comment by dutterbutter** [comment]
@devpavan04 can you tackle this before we deploy to `main` ?
